/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_GOV_V1_COSMOS_GOV_V1_GOV_PB_H_INCLUDED
#define PB_COSMOS_GOV_V1_COSMOS_GOV_V1_GOV_PB_H_INCLUDED
#include <pb.h>

#include "amino/amino.pb.h"
#include "cosmos/base/v1beta1/coin.pb.h"
#include "cosmos_proto/cosmos.pb.h"
#include "gogoproto/gogo.pb.h"
#include "google/protobuf/any.pb.h"
#include "google/protobuf/duration.pb.h"
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* VoteOption enumerates the valid vote options for a given governance proposal. */
typedef enum _cosmos_gov_v1_VoteOption {
    /* VOTE_OPTION_UNSPECIFIED defines a no-op vote option. */
    cosmos_gov_v1_VoteOption_VOTE_OPTION_UNSPECIFIED = 0,
    /* VOTE_OPTION_YES defines a yes vote option. */
    cosmos_gov_v1_VoteOption_VOTE_OPTION_YES = 1,
    /* VOTE_OPTION_ABSTAIN defines an abstain vote option. */
    cosmos_gov_v1_VoteOption_VOTE_OPTION_ABSTAIN = 2,
    /* VOTE_OPTION_NO defines a no vote option. */
    cosmos_gov_v1_VoteOption_VOTE_OPTION_NO = 3,
    /* VOTE_OPTION_NO_WITH_VETO defines a no with veto vote option. */
    cosmos_gov_v1_VoteOption_VOTE_OPTION_NO_WITH_VETO = 4
} cosmos_gov_v1_VoteOption;

/* ProposalStatus enumerates the valid statuses of a proposal. */
typedef enum _cosmos_gov_v1_ProposalStatus {
    /* PROPOSAL_STATUS_UNSPECIFIED defines the default proposal status. */
    cosmos_gov_v1_ProposalStatus_PROPOSAL_STATUS_UNSPECIFIED = 0,
    /* PROPOSAL_STATUS_DEPOSIT_PERIOD defines a proposal status during the deposit
 period. */
    cosmos_gov_v1_ProposalStatus_PROPOSAL_STATUS_DEPOSIT_PERIOD = 1,
    /* PROPOSAL_STATUS_VOTING_PERIOD defines a proposal status during the voting
 period. */
    cosmos_gov_v1_ProposalStatus_PROPOSAL_STATUS_VOTING_PERIOD = 2,
    /* PROPOSAL_STATUS_PASSED defines a proposal status of a proposal that has
 passed. */
    cosmos_gov_v1_ProposalStatus_PROPOSAL_STATUS_PASSED = 3,
    /* PROPOSAL_STATUS_REJECTED defines a proposal status of a proposal that has
 been rejected. */
    cosmos_gov_v1_ProposalStatus_PROPOSAL_STATUS_REJECTED = 4,
    /* PROPOSAL_STATUS_FAILED defines a proposal status of a proposal that has
 failed. */
    cosmos_gov_v1_ProposalStatus_PROPOSAL_STATUS_FAILED = 5
} cosmos_gov_v1_ProposalStatus;

/* Struct definitions */
/* WeightedVoteOption defines a unit of vote for vote split. */
typedef struct _cosmos_gov_v1_WeightedVoteOption {
    /* option defines the valid vote options, it must not contain duplicate vote options. */
    cosmos_gov_v1_VoteOption option;
    /* weight is the vote weight associated with the vote option. */
    pb_callback_t weight;
} cosmos_gov_v1_WeightedVoteOption;

/* Deposit defines an amount deposited by an account address to an active
 proposal. */
typedef struct _cosmos_gov_v1_Deposit {
    /* proposal_id defines the unique id of the proposal. */
    uint64_t proposal_id;
    /* depositor defines the deposit addresses from the proposals. */
    pb_callback_t depositor;
    /* amount to be deposited by depositor. */
    pb_callback_t amount;
} cosmos_gov_v1_Deposit;

/* TallyResult defines a standard tally for a governance proposal. */
typedef struct _cosmos_gov_v1_TallyResult {
    /* yes_count is the number of yes votes on a proposal. */
    pb_callback_t yes_count;
    /* abstain_count is the number of abstain votes on a proposal. */
    pb_callback_t abstain_count;
    /* no_count is the number of no votes on a proposal. */
    pb_callback_t no_count;
    /* no_with_veto_count is the number of no with veto votes on a proposal. */
    pb_callback_t no_with_veto_count;
} cosmos_gov_v1_TallyResult;

/* Proposal defines the core field members of a governance proposal. */
typedef struct _cosmos_gov_v1_Proposal {
    /* id defines the unique id of the proposal. */
    uint64_t id;
    /* messages are the arbitrary messages to be executed if the proposal passes. */
    pb_callback_t messages;
    /* status defines the proposal status. */
    cosmos_gov_v1_ProposalStatus status;
    /* final_tally_result is the final tally result of the proposal. When
 querying a proposal via gRPC, this field is not populated until the
 proposal's voting period has ended. */
    bool has_final_tally_result;
    cosmos_gov_v1_TallyResult final_tally_result;
    /* submit_time is the time of proposal submission. */
    bool has_submit_time;
    google_protobuf_Timestamp submit_time;
    /* deposit_end_time is the end time for deposition. */
    bool has_deposit_end_time;
    google_protobuf_Timestamp deposit_end_time;
    /* total_deposit is the total deposit on the proposal. */
    pb_callback_t total_deposit;
    /* voting_start_time is the starting time to vote on a proposal. */
    bool has_voting_start_time;
    google_protobuf_Timestamp voting_start_time;
    /* voting_end_time is the end time of voting on a proposal. */
    bool has_voting_end_time;
    google_protobuf_Timestamp voting_end_time;
    /* metadata is any arbitrary metadata attached to the proposal.
 the recommended format of the metadata is to be found here: https://docs.cosmos.network/v0.47/modules/gov#proposal-3 */
    pb_callback_t metadata;
    /* title is the title of the proposal

 Since: cosmos-sdk 0.47 */
    pb_callback_t title;
    /* summary is a short summary of the proposal

 Since: cosmos-sdk 0.47 */
    pb_callback_t summary;
    /* proposer is the address of the proposal sumbitter

 Since: cosmos-sdk 0.47 */
    pb_callback_t proposer;
    /* expedited defines if the proposal is expedited

 Since: cosmos-sdk 0.48 */
    bool expedited;
} cosmos_gov_v1_Proposal;

/* Vote defines a vote on a governance proposal.
 A Vote consists of a proposal ID, the voter, and the vote option. */
typedef struct _cosmos_gov_v1_Vote {
    /* proposal_id defines the unique id of the proposal. */
    uint64_t proposal_id;
    /* voter is the voter address of the proposal. */
    pb_callback_t voter;
    /* options is the weighted vote options. */
    pb_callback_t options;
    /* metadata is any arbitrary metadata to attached to the vote.
 the recommended format of the metadata is to be found here: https://docs.cosmos.network/v0.47/modules/gov#vote-5 */
    pb_callback_t metadata;
} cosmos_gov_v1_Vote;

/* DepositParams defines the params for deposits on governance proposals. */
typedef struct _cosmos_gov_v1_DepositParams {
    /* Minimum deposit for a proposal to enter voting period. */
    pb_callback_t min_deposit;
    /* Maximum period for Atom holders to deposit on a proposal. Initial value: 2
 months. */
    bool has_max_deposit_period;
    google_protobuf_Duration max_deposit_period;
} cosmos_gov_v1_DepositParams;

/* VotingParams defines the params for voting on governance proposals. */
typedef struct _cosmos_gov_v1_VotingParams {
    /* Duration of the voting period. */
    bool has_voting_period;
    google_protobuf_Duration voting_period;
} cosmos_gov_v1_VotingParams;

/* TallyParams defines the params for tallying votes on governance proposals. */
typedef struct _cosmos_gov_v1_TallyParams {
    /* Minimum percentage of total stake needed to vote for a result to be
 considered valid. */
    pb_callback_t quorum;
    /* Minimum proportion of Yes votes for proposal to pass. Default value: 0.5. */
    pb_callback_t threshold;
    /* Minimum value of Veto votes to Total votes ratio for proposal to be
 vetoed. Default value: 1/3. */
    pb_callback_t veto_threshold;
} cosmos_gov_v1_TallyParams;

/* Params defines the parameters for the x/gov module.

 Since: cosmos-sdk 0.47 */
typedef struct _cosmos_gov_v1_Params {
    /* Minimum deposit for a proposal to enter voting period. */
    pb_callback_t min_deposit;
    /* Maximum period for Atom holders to deposit on a proposal. Initial value: 2
 months. */
    bool has_max_deposit_period;
    google_protobuf_Duration max_deposit_period;
    /* Duration of the voting period. */
    bool has_voting_period;
    google_protobuf_Duration voting_period;
    /* Minimum percentage of total stake needed to vote for a result to be
  considered valid. */
    pb_callback_t quorum;
    /* Minimum proportion of Yes votes for proposal to pass. Default value: 0.5. */
    pb_callback_t threshold;
    /* Minimum value of Veto votes to Total votes ratio for proposal to be
  vetoed. Default value: 1/3. */
    pb_callback_t veto_threshold;
    /* The ratio representing the proportion of the deposit value that must be paid at proposal submission. */
    pb_callback_t min_initial_deposit_ratio;
    /* The cancel ratio which will not be returned back to the depositors when a proposal is cancelled.

 Since: cosmos-sdk 0.48 */
    pb_callback_t proposal_cancel_ratio;
    /* The address which will receive (proposal_cancel_ratio * deposit) proposal deposits.
 If empty, the (proposal_cancel_ratio * deposit) proposal deposits will be burned.

 Since: cosmos-sdk 0.48 */
    pb_callback_t proposal_cancel_dest;
    /* Duration of the voting period of an expedited proposal.

 Since: cosmos-sdk 0.48 */
    bool has_expedited_voting_period;
    google_protobuf_Duration expedited_voting_period;
    /* Minimum proportion of Yes votes for proposal to pass. Default value: 0.67.

 Since: cosmos-sdk 0.48 */
    pb_callback_t expedited_threshold;
    /* Minimum expedited deposit for a proposal to enter voting period. */
    pb_callback_t expedited_min_deposit;
    /* burn deposits if a proposal does not meet quorum */
    bool burn_vote_quorum;
    /* burn deposits if the proposal does not enter voting period */
    bool burn_proposal_deposit_prevote;
    /* burn deposits if quorum with vote type no_veto is met */
    bool burn_vote_veto;
} cosmos_gov_v1_Params;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _cosmos_gov_v1_VoteOption_MIN cosmos_gov_v1_VoteOption_VOTE_OPTION_UNSPECIFIED
#define _cosmos_gov_v1_VoteOption_MAX cosmos_gov_v1_VoteOption_VOTE_OPTION_NO_WITH_VETO
#define _cosmos_gov_v1_VoteOption_ARRAYSIZE \
    ((cosmos_gov_v1_VoteOption)(cosmos_gov_v1_VoteOption_VOTE_OPTION_NO_WITH_VETO + 1))

#define _cosmos_gov_v1_ProposalStatus_MIN cosmos_gov_v1_ProposalStatus_PROPOSAL_STATUS_UNSPECIFIED
#define _cosmos_gov_v1_ProposalStatus_MAX cosmos_gov_v1_ProposalStatus_PROPOSAL_STATUS_FAILED
#define _cosmos_gov_v1_ProposalStatus_ARRAYSIZE \
    ((cosmos_gov_v1_ProposalStatus)(cosmos_gov_v1_ProposalStatus_PROPOSAL_STATUS_FAILED + 1))

#define cosmos_gov_v1_WeightedVoteOption_option_ENUMTYPE cosmos_gov_v1_VoteOption

#define cosmos_gov_v1_Proposal_status_ENUMTYPE cosmos_gov_v1_ProposalStatus

/* Initializer values for message structs */
#define cosmos_gov_v1_WeightedVoteOption_init_default   \
    {                                                   \
        _cosmos_gov_v1_VoteOption_MIN, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_Deposit_init_default  \
    {                                       \
        0, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_Proposal_init_default                                                                               \
    {                                                                                                                     \
        0, {{NULL}, NULL}, _cosmos_gov_v1_ProposalStatus_MIN, false, cosmos_gov_v1_TallyResult_init_default, false,       \
            google_protobuf_Timestamp_init_default, false, google_protobuf_Timestamp_init_default, {{NULL}, NULL}, false, \
            google_protobuf_Timestamp_init_default, false, google_protobuf_Timestamp_init_default, {{NULL}, NULL},        \
            {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0                                                             \
    }
#define cosmos_gov_v1_TallyResult_init_default                           \
    {                                                                    \
        {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_Vote_init_default                     \
    {                                                       \
        0, {{NULL}, NULL}, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_DepositParams_init_default \
    { {{NULL}, NULL}, false, google_protobuf_Duration_init_default }
#define cosmos_gov_v1_VotingParams_init_default \
    { false, google_protobuf_Duration_init_default }
#define cosmos_gov_v1_TallyParams_init_default           \
    {                                                    \
        {{NULL}, NULL}, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_Params_init_default                                                                           \
    {                                                                                                               \
        {{NULL}, NULL}, false, google_protobuf_Duration_init_default, false, google_protobuf_Duration_init_default, \
            {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false,  \
            google_protobuf_Duration_init_default, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0                          \
    }
#define cosmos_gov_v1_WeightedVoteOption_init_zero      \
    {                                                   \
        _cosmos_gov_v1_VoteOption_MIN, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_Deposit_init_zero     \
    {                                       \
        0, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_Proposal_init_zero                                                                            \
    {                                                                                                               \
        0, {{NULL}, NULL}, _cosmos_gov_v1_ProposalStatus_MIN, false, cosmos_gov_v1_TallyResult_init_zero, false,    \
            google_protobuf_Timestamp_init_zero, false, google_protobuf_Timestamp_init_zero, {{NULL}, NULL}, false, \
            google_protobuf_Timestamp_init_zero, false, google_protobuf_Timestamp_init_zero, {{NULL}, NULL},        \
            {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0                                                       \
    }
#define cosmos_gov_v1_TallyResult_init_zero                              \
    {                                                                    \
        {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_Vote_init_zero                        \
    {                                                       \
        0, {{NULL}, NULL}, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_DepositParams_init_zero \
    { {{NULL}, NULL}, false, google_protobuf_Duration_init_zero }
#define cosmos_gov_v1_VotingParams_init_zero \
    { false, google_protobuf_Duration_init_zero }
#define cosmos_gov_v1_TallyParams_init_zero              \
    {                                                    \
        {{NULL}, NULL}, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define cosmos_gov_v1_Params_init_zero                                                                             \
    {                                                                                                              \
        {{NULL}, NULL}, false, google_protobuf_Duration_init_zero, false, google_protobuf_Duration_init_zero,      \
            {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, \
            google_protobuf_Duration_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0                            \
    }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_gov_v1_WeightedVoteOption_option_tag 1
#define cosmos_gov_v1_WeightedVoteOption_weight_tag 2
#define cosmos_gov_v1_Deposit_proposal_id_tag 1
#define cosmos_gov_v1_Deposit_depositor_tag 2
#define cosmos_gov_v1_Deposit_amount_tag 3
#define cosmos_gov_v1_TallyResult_yes_count_tag 1
#define cosmos_gov_v1_TallyResult_abstain_count_tag 2
#define cosmos_gov_v1_TallyResult_no_count_tag 3
#define cosmos_gov_v1_TallyResult_no_with_veto_count_tag 4
#define cosmos_gov_v1_Proposal_id_tag 1
#define cosmos_gov_v1_Proposal_messages_tag 2
#define cosmos_gov_v1_Proposal_status_tag 3
#define cosmos_gov_v1_Proposal_final_tally_result_tag 4
#define cosmos_gov_v1_Proposal_submit_time_tag 5
#define cosmos_gov_v1_Proposal_deposit_end_time_tag 6
#define cosmos_gov_v1_Proposal_total_deposit_tag 7
#define cosmos_gov_v1_Proposal_voting_start_time_tag 8
#define cosmos_gov_v1_Proposal_voting_end_time_tag 9
#define cosmos_gov_v1_Proposal_metadata_tag 10
#define cosmos_gov_v1_Proposal_title_tag 11
#define cosmos_gov_v1_Proposal_summary_tag 12
#define cosmos_gov_v1_Proposal_proposer_tag 13
#define cosmos_gov_v1_Proposal_expedited_tag 14
#define cosmos_gov_v1_Vote_proposal_id_tag 1
#define cosmos_gov_v1_Vote_voter_tag 2
#define cosmos_gov_v1_Vote_options_tag 4
#define cosmos_gov_v1_Vote_metadata_tag 5
#define cosmos_gov_v1_DepositParams_min_deposit_tag 1
#define cosmos_gov_v1_DepositParams_max_deposit_period_tag 2
#define cosmos_gov_v1_VotingParams_voting_period_tag 1
#define cosmos_gov_v1_TallyParams_quorum_tag 1
#define cosmos_gov_v1_TallyParams_threshold_tag 2
#define cosmos_gov_v1_TallyParams_veto_threshold_tag 3
#define cosmos_gov_v1_Params_min_deposit_tag 1
#define cosmos_gov_v1_Params_max_deposit_period_tag 2
#define cosmos_gov_v1_Params_voting_period_tag 3
#define cosmos_gov_v1_Params_quorum_tag 4
#define cosmos_gov_v1_Params_threshold_tag 5
#define cosmos_gov_v1_Params_veto_threshold_tag 6
#define cosmos_gov_v1_Params_min_initial_deposit_ratio_tag 7
#define cosmos_gov_v1_Params_proposal_cancel_ratio_tag 8
#define cosmos_gov_v1_Params_proposal_cancel_dest_tag 9
#define cosmos_gov_v1_Params_expedited_voting_period_tag 10
#define cosmos_gov_v1_Params_expedited_threshold_tag 11
#define cosmos_gov_v1_Params_expedited_min_deposit_tag 12
#define cosmos_gov_v1_Params_burn_vote_quorum_tag 13
#define cosmos_gov_v1_Params_burn_proposal_deposit_prevote_tag 14
#define cosmos_gov_v1_Params_burn_vote_veto_tag 15

/* Struct field encoding specification for nanopb */
#define cosmos_gov_v1_WeightedVoteOption_FIELDLIST(X, a) \
    X(a, STATIC, SINGULAR, UENUM, option, 1)             \
    X(a, CALLBACK, SINGULAR, STRING, weight, 2)
#define cosmos_gov_v1_WeightedVoteOption_CALLBACK pb_default_field_callback
#define cosmos_gov_v1_WeightedVoteOption_DEFAULT NULL

#define cosmos_gov_v1_Deposit_FIELDLIST(X, a)      \
    X(a, STATIC, SINGULAR, UINT64, proposal_id, 1) \
    X(a, CALLBACK, SINGULAR, STRING, depositor, 2) \
    X(a, CALLBACK, REPEATED, MESSAGE, amount, 3)
#define cosmos_gov_v1_Deposit_CALLBACK pb_default_field_callback
#define cosmos_gov_v1_Deposit_DEFAULT NULL
#define cosmos_gov_v1_Deposit_amount_MSGTYPE cosmos_base_v1beta1_Coin

#define cosmos_gov_v1_Proposal_FIELDLIST(X, a)             \
    X(a, STATIC, SINGULAR, UINT64, id, 1)                  \
    X(a, CALLBACK, REPEATED, MESSAGE, messages, 2)         \
    X(a, STATIC, SINGULAR, UENUM, status, 3)               \
    X(a, STATIC, OPTIONAL, MESSAGE, final_tally_result, 4) \
    X(a, STATIC, OPTIONAL, MESSAGE, submit_time, 5)        \
    X(a, STATIC, OPTIONAL, MESSAGE, deposit_end_time, 6)   \
    X(a, CALLBACK, REPEATED, MESSAGE, total_deposit, 7)    \
    X(a, STATIC, OPTIONAL, MESSAGE, voting_start_time, 8)  \
    X(a, STATIC, OPTIONAL, MESSAGE, voting_end_time, 9)    \
    X(a, CALLBACK, SINGULAR, STRING, metadata, 10)         \
    X(a, CALLBACK, SINGULAR, STRING, title, 11)            \
    X(a, CALLBACK, SINGULAR, STRING, summary, 12)          \
    X(a, CALLBACK, SINGULAR, STRING, proposer, 13)         \
    X(a, STATIC, SINGULAR, BOOL, expedited, 14)
#define cosmos_gov_v1_Proposal_CALLBACK pb_default_field_callback
#define cosmos_gov_v1_Proposal_DEFAULT NULL
#define cosmos_gov_v1_Proposal_messages_MSGTYPE google_protobuf_Any
#define cosmos_gov_v1_Proposal_final_tally_result_MSGTYPE cosmos_gov_v1_TallyResult
#define cosmos_gov_v1_Proposal_submit_time_MSGTYPE google_protobuf_Timestamp
#define cosmos_gov_v1_Proposal_deposit_end_time_MSGTYPE google_protobuf_Timestamp
#define cosmos_gov_v1_Proposal_total_deposit_MSGTYPE cosmos_base_v1beta1_Coin
#define cosmos_gov_v1_Proposal_voting_start_time_MSGTYPE google_protobuf_Timestamp
#define cosmos_gov_v1_Proposal_voting_end_time_MSGTYPE google_protobuf_Timestamp

#define cosmos_gov_v1_TallyResult_FIELDLIST(X, a)      \
    X(a, CALLBACK, SINGULAR, STRING, yes_count, 1)     \
    X(a, CALLBACK, SINGULAR, STRING, abstain_count, 2) \
    X(a, CALLBACK, SINGULAR, STRING, no_count, 3)      \
    X(a, CALLBACK, SINGULAR, STRING, no_with_veto_count, 4)
#define cosmos_gov_v1_TallyResult_CALLBACK pb_default_field_callback
#define cosmos_gov_v1_TallyResult_DEFAULT NULL

#define cosmos_gov_v1_Vote_FIELDLIST(X, a)         \
    X(a, STATIC, SINGULAR, UINT64, proposal_id, 1) \
    X(a, CALLBACK, SINGULAR, STRING, voter, 2)     \
    X(a, CALLBACK, REPEATED, MESSAGE, options, 4)  \
    X(a, CALLBACK, SINGULAR, STRING, metadata, 5)
#define cosmos_gov_v1_Vote_CALLBACK pb_default_field_callback
#define cosmos_gov_v1_Vote_DEFAULT NULL
#define cosmos_gov_v1_Vote_options_MSGTYPE cosmos_gov_v1_WeightedVoteOption

#define cosmos_gov_v1_DepositParams_FIELDLIST(X, a)   \
    X(a, CALLBACK, REPEATED, MESSAGE, min_deposit, 1) \
    X(a, STATIC, OPTIONAL, MESSAGE, max_deposit_period, 2)
#define cosmos_gov_v1_DepositParams_CALLBACK pb_default_field_callback
#define cosmos_gov_v1_DepositParams_DEFAULT NULL
#define cosmos_gov_v1_DepositParams_min_deposit_MSGTYPE cosmos_base_v1beta1_Coin
#define cosmos_gov_v1_DepositParams_max_deposit_period_MSGTYPE google_protobuf_Duration

#define cosmos_gov_v1_VotingParams_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, voting_period, 1)
#define cosmos_gov_v1_VotingParams_CALLBACK NULL
#define cosmos_gov_v1_VotingParams_DEFAULT NULL
#define cosmos_gov_v1_VotingParams_voting_period_MSGTYPE google_protobuf_Duration

#define cosmos_gov_v1_TallyParams_FIELDLIST(X, a)  \
    X(a, CALLBACK, SINGULAR, STRING, quorum, 1)    \
    X(a, CALLBACK, SINGULAR, STRING, threshold, 2) \
    X(a, CALLBACK, SINGULAR, STRING, veto_threshold, 3)
#define cosmos_gov_v1_TallyParams_CALLBACK pb_default_field_callback
#define cosmos_gov_v1_TallyParams_DEFAULT NULL

#define cosmos_gov_v1_Params_FIELDLIST(X, a)                        \
    X(a, CALLBACK, REPEATED, MESSAGE, min_deposit, 1)               \
    X(a, STATIC, OPTIONAL, MESSAGE, max_deposit_period, 2)          \
    X(a, STATIC, OPTIONAL, MESSAGE, voting_period, 3)               \
    X(a, CALLBACK, SINGULAR, STRING, quorum, 4)                     \
    X(a, CALLBACK, SINGULAR, STRING, threshold, 5)                  \
    X(a, CALLBACK, SINGULAR, STRING, veto_threshold, 6)             \
    X(a, CALLBACK, SINGULAR, STRING, min_initial_deposit_ratio, 7)  \
    X(a, CALLBACK, SINGULAR, STRING, proposal_cancel_ratio, 8)      \
    X(a, CALLBACK, SINGULAR, STRING, proposal_cancel_dest, 9)       \
    X(a, STATIC, OPTIONAL, MESSAGE, expedited_voting_period, 10)    \
    X(a, CALLBACK, SINGULAR, STRING, expedited_threshold, 11)       \
    X(a, CALLBACK, REPEATED, MESSAGE, expedited_min_deposit, 12)    \
    X(a, STATIC, SINGULAR, BOOL, burn_vote_quorum, 13)              \
    X(a, STATIC, SINGULAR, BOOL, burn_proposal_deposit_prevote, 14) \
    X(a, STATIC, SINGULAR, BOOL, burn_vote_veto, 15)
#define cosmos_gov_v1_Params_CALLBACK pb_default_field_callback
#define cosmos_gov_v1_Params_DEFAULT NULL
#define cosmos_gov_v1_Params_min_deposit_MSGTYPE cosmos_base_v1beta1_Coin
#define cosmos_gov_v1_Params_max_deposit_period_MSGTYPE google_protobuf_Duration
#define cosmos_gov_v1_Params_voting_period_MSGTYPE google_protobuf_Duration
#define cosmos_gov_v1_Params_expedited_voting_period_MSGTYPE google_protobuf_Duration
#define cosmos_gov_v1_Params_expedited_min_deposit_MSGTYPE cosmos_base_v1beta1_Coin

extern const pb_msgdesc_t cosmos_gov_v1_WeightedVoteOption_msg;
extern const pb_msgdesc_t cosmos_gov_v1_Deposit_msg;
extern const pb_msgdesc_t cosmos_gov_v1_Proposal_msg;
extern const pb_msgdesc_t cosmos_gov_v1_TallyResult_msg;
extern const pb_msgdesc_t cosmos_gov_v1_Vote_msg;
extern const pb_msgdesc_t cosmos_gov_v1_DepositParams_msg;
extern const pb_msgdesc_t cosmos_gov_v1_VotingParams_msg;
extern const pb_msgdesc_t cosmos_gov_v1_TallyParams_msg;
extern const pb_msgdesc_t cosmos_gov_v1_Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_gov_v1_WeightedVoteOption_fields &cosmos_gov_v1_WeightedVoteOption_msg
#define cosmos_gov_v1_Deposit_fields &cosmos_gov_v1_Deposit_msg
#define cosmos_gov_v1_Proposal_fields &cosmos_gov_v1_Proposal_msg
#define cosmos_gov_v1_TallyResult_fields &cosmos_gov_v1_TallyResult_msg
#define cosmos_gov_v1_Vote_fields &cosmos_gov_v1_Vote_msg
#define cosmos_gov_v1_DepositParams_fields &cosmos_gov_v1_DepositParams_msg
#define cosmos_gov_v1_VotingParams_fields &cosmos_gov_v1_VotingParams_msg
#define cosmos_gov_v1_TallyParams_fields &cosmos_gov_v1_TallyParams_msg
#define cosmos_gov_v1_Params_fields &cosmos_gov_v1_Params_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_gov_v1_WeightedVoteOption_size depends on runtime parameters */
/* cosmos_gov_v1_Deposit_size depends on runtime parameters */
/* cosmos_gov_v1_Proposal_size depends on runtime parameters */
/* cosmos_gov_v1_TallyResult_size depends on runtime parameters */
/* cosmos_gov_v1_Vote_size depends on runtime parameters */
/* cosmos_gov_v1_DepositParams_size depends on runtime parameters */
/* cosmos_gov_v1_TallyParams_size depends on runtime parameters */
/* cosmos_gov_v1_Params_size depends on runtime parameters */
#define COSMOS_GOV_V1_COSMOS_GOV_V1_GOV_PB_H_MAX_SIZE cosmos_gov_v1_VotingParams_size
#define cosmos_gov_v1_VotingParams_size 24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
