/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/gov/v1/gov.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_gov_v1_WeightedVoteOption, cosmos_gov_v1_WeightedVoteOption, AUTO)

PB_BIND(cosmos_gov_v1_Deposit, cosmos_gov_v1_Deposit, AUTO)

PB_BIND(cosmos_gov_v1_Proposal, cosmos_gov_v1_Proposal, 2)

PB_BIND(cosmos_gov_v1_TallyResult, cosmos_gov_v1_TallyResult, AUTO)

PB_BIND(cosmos_gov_v1_Vote, cosmos_gov_v1_Vote, AUTO)

PB_BIND(cosmos_gov_v1_DepositParams, cosmos_gov_v1_DepositParams, AUTO)

PB_BIND(cosmos_gov_v1_VotingParams, cosmos_gov_v1_VotingParams, AUTO)

PB_BIND(cosmos_gov_v1_TallyParams, cosmos_gov_v1_TallyParams, AUTO)

PB_BIND(cosmos_gov_v1_Params, cosmos_gov_v1_Params, AUTO)
