/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_CRYPTO_HD_V1_COSMOS_CRYPTO_HD_V1_HD_PB_H_INCLUDED
#define PB_COSMOS_CRYPTO_HD_V1_COSMOS_CRYPTO_HD_V1_HD_PB_H_INCLUDED
#include <pb.h>

#include "amino/amino.pb.h"
#include "gogoproto/gogo.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* BIP44Params is used as path field in ledger item in Record. */
typedef struct _cosmos_crypto_hd_v1_BIP44Params {
    /* purpose is a constant set to 44' (or 0x8000002C) following the BIP43 recommendation */
    uint32_t purpose;
    /* coin_type is a constant that improves privacy */
    uint32_t coin_type;
    /* account splits the key space into independent user identities */
    uint32_t account;
    /* change is a constant used for public derivation. Constant 0 is used for external chain and constant 1 for internal
 chain. */
    bool change;
    /* address_index is used as child index in BIP32 derivation */
    uint32_t address_index;
} cosmos_crypto_hd_v1_BIP44Params;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_crypto_hd_v1_BIP44Params_init_default \
    { 0, 0, 0, 0, 0 }
#define cosmos_crypto_hd_v1_BIP44Params_init_zero \
    { 0, 0, 0, 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_crypto_hd_v1_BIP44Params_purpose_tag 1
#define cosmos_crypto_hd_v1_BIP44Params_coin_type_tag 2
#define cosmos_crypto_hd_v1_BIP44Params_account_tag 3
#define cosmos_crypto_hd_v1_BIP44Params_change_tag 4
#define cosmos_crypto_hd_v1_BIP44Params_address_index_tag 5

/* Struct field encoding specification for nanopb */
#define cosmos_crypto_hd_v1_BIP44Params_FIELDLIST(X, a) \
    X(a, STATIC, SINGULAR, UINT32, purpose, 1)          \
    X(a, STATIC, SINGULAR, UINT32, coin_type, 2)        \
    X(a, STATIC, SINGULAR, UINT32, account, 3)          \
    X(a, STATIC, SINGULAR, BOOL, change, 4)             \
    X(a, STATIC, SINGULAR, UINT32, address_index, 5)
#define cosmos_crypto_hd_v1_BIP44Params_CALLBACK NULL
#define cosmos_crypto_hd_v1_BIP44Params_DEFAULT NULL

extern const pb_msgdesc_t cosmos_crypto_hd_v1_BIP44Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_crypto_hd_v1_BIP44Params_fields &cosmos_crypto_hd_v1_BIP44Params_msg

/* Maximum encoded size of messages (where known) */
#define COSMOS_CRYPTO_HD_V1_COSMOS_CRYPTO_HD_V1_HD_PB_H_MAX_SIZE cosmos_crypto_hd_v1_BIP44Params_size
#define cosmos_crypto_hd_v1_BIP44Params_size 26

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
