/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_CRYPTO_MULTISIG_COSMOS_CRYPTO_MULTISIG_KEYS_PB_H_INCLUDED
#define PB_COSMOS_CRYPTO_MULTISIG_COSMOS_CRYPTO_MULTISIG_KEYS_PB_H_INCLUDED
#include <pb.h>

#include "amino/amino.pb.h"
#include "gogoproto/gogo.pb.h"
#include "google/protobuf/any.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* LegacyAminoPubKey specifies a public key type
 which nests multiple public keys and a threshold,
 it uses legacy amino address rules. */
typedef struct _cosmos_crypto_multisig_LegacyAminoPubKey {
    uint32_t threshold;
    pb_callback_t public_keys;
} cosmos_crypto_multisig_LegacyAminoPubKey;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_crypto_multisig_LegacyAminoPubKey_init_default \
    {                                                         \
        0, { {NULL}, NULL }                                   \
    }
#define cosmos_crypto_multisig_LegacyAminoPubKey_init_zero \
    {                                                      \
        0, { {NULL}, NULL }                                \
    }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_crypto_multisig_LegacyAminoPubKey_threshold_tag 1
#define cosmos_crypto_multisig_LegacyAminoPubKey_public_keys_tag 2

/* Struct field encoding specification for nanopb */
#define cosmos_crypto_multisig_LegacyAminoPubKey_FIELDLIST(X, a) \
    X(a, STATIC, SINGULAR, UINT32, threshold, 1)                 \
    X(a, CALLBACK, REPEATED, MESSAGE, public_keys, 2)
#define cosmos_crypto_multisig_LegacyAminoPubKey_CALLBACK pb_default_field_callback
#define cosmos_crypto_multisig_LegacyAminoPubKey_DEFAULT NULL
#define cosmos_crypto_multisig_LegacyAminoPubKey_public_keys_MSGTYPE google_protobuf_Any

extern const pb_msgdesc_t cosmos_crypto_multisig_LegacyAminoPubKey_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_crypto_multisig_LegacyAminoPubKey_fields &cosmos_crypto_multisig_LegacyAminoPubKey_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_crypto_multisig_LegacyAminoPubKey_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
