/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/store/internal/kv/v1beta1/kv.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_store_internal_kv_v1beta1_Pairs, cosmos_store_internal_kv_v1beta1_Pairs, AUTO)

PB_BIND(cosmos_store_internal_kv_v1beta1_Pair, cosmos_store_internal_kv_v1beta1_Pair, AUTO)
