/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_IBC_APPLICATIONS_TRANSFER_V1_IBC_APPLICATIONS_TRANSFER_V1_QUERY_PB_H_INCLUDED
#define PB_IBC_APPLICATIONS_TRANSFER_V1_IBC_APPLICATIONS_TRANSFER_V1_QUERY_PB_H_INCLUDED
#include <pb.h>

#include "cosmos/base/query/v1beta1/pagination.pb.h"
#include "cosmos/base/v1beta1/coin.pb.h"
#include "gogoproto/gogo.pb.h"
#include "google/api/annotations.pb.h"
#include "ibc/applications/transfer/v1/transfer.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* QueryDenomTraceRequest is the request type for the Query/DenomTrace RPC
 method */
typedef struct _ibc_applications_transfer_v1_QueryDenomTraceRequest {
    /* hash (in hex format) or denom (full denom with ibc prefix) of the denomination trace information. */
    pb_callback_t hash;
} ibc_applications_transfer_v1_QueryDenomTraceRequest;

/* QueryDenomTraceResponse is the response type for the Query/DenomTrace RPC
 method. */
typedef struct _ibc_applications_transfer_v1_QueryDenomTraceResponse {
    /* denom_trace returns the requested denomination trace information. */
    bool has_denom_trace;
    ibc_applications_transfer_v1_DenomTrace denom_trace;
} ibc_applications_transfer_v1_QueryDenomTraceResponse;

/* QueryConnectionsRequest is the request type for the Query/DenomTraces RPC
 method */
typedef struct _ibc_applications_transfer_v1_QueryDenomTracesRequest {
    /* pagination defines an optional pagination for the request. */
    bool has_pagination;
    cosmos_base_query_v1beta1_PageRequest pagination;
} ibc_applications_transfer_v1_QueryDenomTracesRequest;

/* QueryConnectionsResponse is the response type for the Query/DenomTraces RPC
 method. */
typedef struct _ibc_applications_transfer_v1_QueryDenomTracesResponse {
    /* denom_traces returns all denominations trace information. */
    pb_callback_t denom_traces;
    /* pagination defines the pagination in the response. */
    bool has_pagination;
    cosmos_base_query_v1beta1_PageResponse pagination;
} ibc_applications_transfer_v1_QueryDenomTracesResponse;

/* QueryParamsRequest is the request type for the Query/Params RPC method. */
typedef struct _ibc_applications_transfer_v1_QueryParamsRequest {
    char dummy_field;
} ibc_applications_transfer_v1_QueryParamsRequest;

/* QueryParamsResponse is the response type for the Query/Params RPC method. */
typedef struct _ibc_applications_transfer_v1_QueryParamsResponse {
    /* params defines the parameters of the module. */
    bool has_params;
    ibc_applications_transfer_v1_Params params;
} ibc_applications_transfer_v1_QueryParamsResponse;

/* QueryDenomHashRequest is the request type for the Query/DenomHash RPC
 method */
typedef struct _ibc_applications_transfer_v1_QueryDenomHashRequest {
    /* The denomination trace ([port_id]/[channel_id])+/[denom] */
    pb_callback_t trace;
} ibc_applications_transfer_v1_QueryDenomHashRequest;

/* QueryDenomHashResponse is the response type for the Query/DenomHash RPC
 method. */
typedef struct _ibc_applications_transfer_v1_QueryDenomHashResponse {
    /* hash (in hex format) of the denomination trace information. */
    pb_callback_t hash;
} ibc_applications_transfer_v1_QueryDenomHashResponse;

/* QueryEscrowAddressRequest is the request type for the EscrowAddress RPC method. */
typedef struct _ibc_applications_transfer_v1_QueryEscrowAddressRequest {
    /* unique port identifier */
    pb_callback_t port_id;
    /* unique channel identifier */
    pb_callback_t channel_id;
} ibc_applications_transfer_v1_QueryEscrowAddressRequest;

/* QueryEscrowAddressResponse is the response type of the EscrowAddress RPC method. */
typedef struct _ibc_applications_transfer_v1_QueryEscrowAddressResponse {
    /* the escrow account address */
    pb_callback_t escrow_address;
} ibc_applications_transfer_v1_QueryEscrowAddressResponse;

/* QueryTotalEscrowForDenomRequest is the request type for TotalEscrowForDenom RPC method. */
typedef struct _ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest {
    pb_callback_t denom;
} ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest;

/* QueryTotalEscrowForDenomResponse is the response type for TotalEscrowForDenom RPC method. */
typedef struct _ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse {
    bool has_amount;
    cosmos_base_v1beta1_Coin amount;
} ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ibc_applications_transfer_v1_QueryDenomTraceRequest_init_default \
    {                                                                    \
        { {NULL}, NULL }                                                 \
    }
#define ibc_applications_transfer_v1_QueryDenomTraceResponse_init_default \
    { false, ibc_applications_transfer_v1_DenomTrace_init_default }
#define ibc_applications_transfer_v1_QueryDenomTracesRequest_init_default \
    { false, cosmos_base_query_v1beta1_PageRequest_init_default }
#define ibc_applications_transfer_v1_QueryDenomTracesResponse_init_default \
    { {{NULL}, NULL}, false, cosmos_base_query_v1beta1_PageResponse_init_default }
#define ibc_applications_transfer_v1_QueryParamsRequest_init_default \
    { 0 }
#define ibc_applications_transfer_v1_QueryParamsResponse_init_default \
    { false, ibc_applications_transfer_v1_Params_init_default }
#define ibc_applications_transfer_v1_QueryDenomHashRequest_init_default \
    {                                                                   \
        { {NULL}, NULL }                                                \
    }
#define ibc_applications_transfer_v1_QueryDenomHashResponse_init_default \
    {                                                                    \
        { {NULL}, NULL }                                                 \
    }
#define ibc_applications_transfer_v1_QueryEscrowAddressRequest_init_default \
    {                                                                       \
        {{NULL}, NULL}, { {NULL}, NULL }                                    \
    }
#define ibc_applications_transfer_v1_QueryEscrowAddressResponse_init_default \
    {                                                                        \
        { {NULL}, NULL }                                                     \
    }
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_init_default \
    {                                                                             \
        { {NULL}, NULL }                                                          \
    }
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_init_default \
    { false, cosmos_base_v1beta1_Coin_init_default }
#define ibc_applications_transfer_v1_QueryDenomTraceRequest_init_zero \
    {                                                                 \
        { {NULL}, NULL }                                              \
    }
#define ibc_applications_transfer_v1_QueryDenomTraceResponse_init_zero \
    { false, ibc_applications_transfer_v1_DenomTrace_init_zero }
#define ibc_applications_transfer_v1_QueryDenomTracesRequest_init_zero \
    { false, cosmos_base_query_v1beta1_PageRequest_init_zero }
#define ibc_applications_transfer_v1_QueryDenomTracesResponse_init_zero \
    { {{NULL}, NULL}, false, cosmos_base_query_v1beta1_PageResponse_init_zero }
#define ibc_applications_transfer_v1_QueryParamsRequest_init_zero \
    { 0 }
#define ibc_applications_transfer_v1_QueryParamsResponse_init_zero \
    { false, ibc_applications_transfer_v1_Params_init_zero }
#define ibc_applications_transfer_v1_QueryDenomHashRequest_init_zero \
    {                                                                \
        { {NULL}, NULL }                                             \
    }
#define ibc_applications_transfer_v1_QueryDenomHashResponse_init_zero \
    {                                                                 \
        { {NULL}, NULL }                                              \
    }
#define ibc_applications_transfer_v1_QueryEscrowAddressRequest_init_zero \
    {                                                                    \
        {{NULL}, NULL}, { {NULL}, NULL }                                 \
    }
#define ibc_applications_transfer_v1_QueryEscrowAddressResponse_init_zero \
    {                                                                     \
        { {NULL}, NULL }                                                  \
    }
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_init_zero \
    {                                                                          \
        { {NULL}, NULL }                                                       \
    }
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_init_zero \
    { false, cosmos_base_v1beta1_Coin_init_zero }

/* Field tags (for use in manual encoding/decoding) */
#define ibc_applications_transfer_v1_QueryDenomTraceRequest_hash_tag 1
#define ibc_applications_transfer_v1_QueryDenomTraceResponse_denom_trace_tag 1
#define ibc_applications_transfer_v1_QueryDenomTracesRequest_pagination_tag 1
#define ibc_applications_transfer_v1_QueryDenomTracesResponse_denom_traces_tag 1
#define ibc_applications_transfer_v1_QueryDenomTracesResponse_pagination_tag 2
#define ibc_applications_transfer_v1_QueryParamsResponse_params_tag 1
#define ibc_applications_transfer_v1_QueryDenomHashRequest_trace_tag 1
#define ibc_applications_transfer_v1_QueryDenomHashResponse_hash_tag 1
#define ibc_applications_transfer_v1_QueryEscrowAddressRequest_port_id_tag 1
#define ibc_applications_transfer_v1_QueryEscrowAddressRequest_channel_id_tag 2
#define ibc_applications_transfer_v1_QueryEscrowAddressResponse_escrow_address_tag 1
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_denom_tag 1
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_amount_tag 1

/* Struct field encoding specification for nanopb */
#define ibc_applications_transfer_v1_QueryDenomTraceRequest_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, hash, 1)
#define ibc_applications_transfer_v1_QueryDenomTraceRequest_CALLBACK pb_default_field_callback
#define ibc_applications_transfer_v1_QueryDenomTraceRequest_DEFAULT NULL

#define ibc_applications_transfer_v1_QueryDenomTraceResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, denom_trace, 1)
#define ibc_applications_transfer_v1_QueryDenomTraceResponse_CALLBACK NULL
#define ibc_applications_transfer_v1_QueryDenomTraceResponse_DEFAULT NULL
#define ibc_applications_transfer_v1_QueryDenomTraceResponse_denom_trace_MSGTYPE ibc_applications_transfer_v1_DenomTrace

#define ibc_applications_transfer_v1_QueryDenomTracesRequest_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, pagination, 1)
#define ibc_applications_transfer_v1_QueryDenomTracesRequest_CALLBACK NULL
#define ibc_applications_transfer_v1_QueryDenomTracesRequest_DEFAULT NULL
#define ibc_applications_transfer_v1_QueryDenomTracesRequest_pagination_MSGTYPE cosmos_base_query_v1beta1_PageRequest

#define ibc_applications_transfer_v1_QueryDenomTracesResponse_FIELDLIST(X, a) \
    X(a, CALLBACK, REPEATED, MESSAGE, denom_traces, 1)                        \
    X(a, STATIC, OPTIONAL, MESSAGE, pagination, 2)
#define ibc_applications_transfer_v1_QueryDenomTracesResponse_CALLBACK pb_default_field_callback
#define ibc_applications_transfer_v1_QueryDenomTracesResponse_DEFAULT NULL
#define ibc_applications_transfer_v1_QueryDenomTracesResponse_denom_traces_MSGTYPE ibc_applications_transfer_v1_DenomTrace
#define ibc_applications_transfer_v1_QueryDenomTracesResponse_pagination_MSGTYPE cosmos_base_query_v1beta1_PageResponse

#define ibc_applications_transfer_v1_QueryParamsRequest_FIELDLIST(X, a)

#define ibc_applications_transfer_v1_QueryParamsRequest_CALLBACK NULL
#define ibc_applications_transfer_v1_QueryParamsRequest_DEFAULT NULL

#define ibc_applications_transfer_v1_QueryParamsResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, params, 1)
#define ibc_applications_transfer_v1_QueryParamsResponse_CALLBACK NULL
#define ibc_applications_transfer_v1_QueryParamsResponse_DEFAULT NULL
#define ibc_applications_transfer_v1_QueryParamsResponse_params_MSGTYPE ibc_applications_transfer_v1_Params

#define ibc_applications_transfer_v1_QueryDenomHashRequest_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, trace, 1)
#define ibc_applications_transfer_v1_QueryDenomHashRequest_CALLBACK pb_default_field_callback
#define ibc_applications_transfer_v1_QueryDenomHashRequest_DEFAULT NULL

#define ibc_applications_transfer_v1_QueryDenomHashResponse_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, hash, 1)
#define ibc_applications_transfer_v1_QueryDenomHashResponse_CALLBACK pb_default_field_callback
#define ibc_applications_transfer_v1_QueryDenomHashResponse_DEFAULT NULL

#define ibc_applications_transfer_v1_QueryEscrowAddressRequest_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, STRING, port_id, 1)                               \
    X(a, CALLBACK, SINGULAR, STRING, channel_id, 2)
#define ibc_applications_transfer_v1_QueryEscrowAddressRequest_CALLBACK pb_default_field_callback
#define ibc_applications_transfer_v1_QueryEscrowAddressRequest_DEFAULT NULL

#define ibc_applications_transfer_v1_QueryEscrowAddressResponse_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, STRING, escrow_address, 1)
#define ibc_applications_transfer_v1_QueryEscrowAddressResponse_CALLBACK pb_default_field_callback
#define ibc_applications_transfer_v1_QueryEscrowAddressResponse_DEFAULT NULL

#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, STRING, denom, 1)
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_CALLBACK pb_default_field_callback
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_DEFAULT NULL

#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, amount, 1)
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_CALLBACK NULL
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_DEFAULT NULL
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_amount_MSGTYPE cosmos_base_v1beta1_Coin

extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryDenomTraceRequest_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryDenomTraceResponse_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryDenomTracesRequest_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryDenomTracesResponse_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryParamsRequest_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryParamsResponse_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryDenomHashRequest_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryDenomHashResponse_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryEscrowAddressRequest_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryEscrowAddressResponse_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_msg;
extern const pb_msgdesc_t ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ibc_applications_transfer_v1_QueryDenomTraceRequest_fields &ibc_applications_transfer_v1_QueryDenomTraceRequest_msg
#define ibc_applications_transfer_v1_QueryDenomTraceResponse_fields &ibc_applications_transfer_v1_QueryDenomTraceResponse_msg
#define ibc_applications_transfer_v1_QueryDenomTracesRequest_fields &ibc_applications_transfer_v1_QueryDenomTracesRequest_msg
#define ibc_applications_transfer_v1_QueryDenomTracesResponse_fields \
    &ibc_applications_transfer_v1_QueryDenomTracesResponse_msg
#define ibc_applications_transfer_v1_QueryParamsRequest_fields &ibc_applications_transfer_v1_QueryParamsRequest_msg
#define ibc_applications_transfer_v1_QueryParamsResponse_fields &ibc_applications_transfer_v1_QueryParamsResponse_msg
#define ibc_applications_transfer_v1_QueryDenomHashRequest_fields &ibc_applications_transfer_v1_QueryDenomHashRequest_msg
#define ibc_applications_transfer_v1_QueryDenomHashResponse_fields &ibc_applications_transfer_v1_QueryDenomHashResponse_msg
#define ibc_applications_transfer_v1_QueryEscrowAddressRequest_fields \
    &ibc_applications_transfer_v1_QueryEscrowAddressRequest_msg
#define ibc_applications_transfer_v1_QueryEscrowAddressResponse_fields \
    &ibc_applications_transfer_v1_QueryEscrowAddressResponse_msg
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_fields \
    &ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_msg
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_fields \
    &ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_msg

/* Maximum encoded size of messages (where known) */
/* ibc_applications_transfer_v1_QueryDenomTraceRequest_size depends on runtime parameters */
/* ibc_applications_transfer_v1_QueryDenomTracesResponse_size depends on runtime parameters */
/* ibc_applications_transfer_v1_QueryDenomHashRequest_size depends on runtime parameters */
/* ibc_applications_transfer_v1_QueryDenomHashResponse_size depends on runtime parameters */
/* ibc_applications_transfer_v1_QueryEscrowAddressRequest_size depends on runtime parameters */
/* ibc_applications_transfer_v1_QueryEscrowAddressResponse_size depends on runtime parameters */
/* ibc_applications_transfer_v1_QueryTotalEscrowForDenomRequest_size depends on runtime parameters */
#if defined(ibc_applications_transfer_v1_DenomTrace_size)
#define IBC_APPLICATIONS_TRANSFER_V1_IBC_APPLICATIONS_TRANSFER_V1_QUERY_PB_H_MAX_SIZE \
    ibc_applications_transfer_v1_QueryDenomTraceResponse_size
#define ibc_applications_transfer_v1_QueryDenomTraceResponse_size (6 + ibc_applications_transfer_v1_DenomTrace_size)
#endif
#if defined(cosmos_base_query_v1beta1_PageRequest_size)
#define ibc_applications_transfer_v1_QueryDenomTracesRequest_size (6 + cosmos_base_query_v1beta1_PageRequest_size)
#endif
#define ibc_applications_transfer_v1_QueryParamsRequest_size 0
#define ibc_applications_transfer_v1_QueryParamsResponse_size 6
#if defined(cosmos_base_v1beta1_Coin_size)
#define ibc_applications_transfer_v1_QueryTotalEscrowForDenomResponse_size (6 + cosmos_base_v1beta1_Coin_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
