/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/staking/v1beta1/tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_staking_v1beta1_MsgCreateValidator, cosmos_staking_v1beta1_MsgCreateValidator, 2)

PB_BIND(cosmos_staking_v1beta1_MsgCreateValidatorResponse, cosmos_staking_v1beta1_MsgCreateValidatorResponse, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgEditValidator, cosmos_staking_v1beta1_MsgEditValidator, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgEditValidatorResponse, cosmos_staking_v1beta1_MsgEditValidatorResponse, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgDelegate, cosmos_staking_v1beta1_MsgDelegate, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgDelegateResponse, cosmos_staking_v1beta1_MsgDelegateResponse, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgBeginRedelegate, cosmos_staking_v1beta1_MsgBeginRedelegate, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgBeginRedelegateResponse, cosmos_staking_v1beta1_MsgBeginRedelegateResponse, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgUndelegate, cosmos_staking_v1beta1_MsgUndelegate, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgUndelegateResponse, cosmos_staking_v1beta1_MsgUndelegateResponse, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgCancelUnbondingDelegation, cosmos_staking_v1beta1_MsgCancelUnbondingDelegation, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgCancelUnbondingDelegationResponse,
        cosmos_staking_v1beta1_MsgCancelUnbondingDelegationResponse, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgUpdateParams, cosmos_staking_v1beta1_MsgUpdateParams, AUTO)

PB_BIND(cosmos_staking_v1beta1_MsgUpdateParamsResponse, cosmos_staking_v1beta1_MsgUpdateParamsResponse, AUTO)
