/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/store/v1beta1/commit_info.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_store_v1beta1_CommitInfo, cosmos_store_v1beta1_CommitInfo, AUTO)

PB_BIND(cosmos_store_v1beta1_StoreInfo, cosmos_store_v1beta1_StoreInfo, AUTO)

PB_BIND(cosmos_store_v1beta1_CommitID, cosmos_store_v1beta1_CommitID, AUTO)
