/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ibc/applications/fee/v1/ack.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ibc_applications_fee_v1_IncentivizedAcknowledgement, ibc_applications_fee_v1_IncentivizedAcknowledgement, AUTO)
