/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_IBC_APPLICATIONS_FEE_V1_IBC_APPLICATIONS_FEE_V1_FEE_PB_H_INCLUDED
#define PB_IBC_APPLICATIONS_FEE_V1_IBC_APPLICATIONS_FEE_V1_FEE_PB_H_INCLUDED
#include <pb.h>

#include "amino/amino.pb.h"
#include "cosmos/base/v1beta1/coin.pb.h"
#include "cosmos/msg/v1/msg.pb.h"
#include "gogoproto/gogo.pb.h"
#include "ibc/core/channel/v1/channel.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Fee defines the ICS29 receive, acknowledgement and timeout fees */
typedef struct _ibc_applications_fee_v1_Fee {
    /* the packet receive fee */
    pb_callback_t recv_fee;
    /* the packet acknowledgement fee */
    pb_callback_t ack_fee;
    /* the packet timeout fee */
    pb_callback_t timeout_fee;
} ibc_applications_fee_v1_Fee;

/* PacketFee contains ICS29 relayer fees, refund address and optional list of permitted relayers */
typedef struct _ibc_applications_fee_v1_PacketFee {
    /* fee encapsulates the recv, ack and timeout fees associated with an IBC packet */
    bool has_fee;
    ibc_applications_fee_v1_Fee fee;
    /* the refund address for unspent fees */
    pb_callback_t refund_address;
    /* optional list of relayers permitted to receive fees */
    pb_callback_t relayers;
} ibc_applications_fee_v1_PacketFee;

/* PacketFees contains a list of type PacketFee */
typedef struct _ibc_applications_fee_v1_PacketFees {
    /* list of packet fees */
    pb_callback_t packet_fees;
} ibc_applications_fee_v1_PacketFees;

/* IdentifiedPacketFees contains a list of type PacketFee and associated PacketId */
typedef struct _ibc_applications_fee_v1_IdentifiedPacketFees {
    /* unique packet identifier comprised of the channel ID, port ID and sequence */
    bool has_packet_id;
    ibc_core_channel_v1_PacketId packet_id;
    /* list of packet fees */
    pb_callback_t packet_fees;
} ibc_applications_fee_v1_IdentifiedPacketFees;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ibc_applications_fee_v1_Fee_init_default         \
    {                                                    \
        {{NULL}, NULL}, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define ibc_applications_fee_v1_PacketFee_init_default                                    \
    {                                                                                     \
        false, ibc_applications_fee_v1_Fee_init_default, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define ibc_applications_fee_v1_PacketFees_init_default \
    {                                                   \
        { {NULL}, NULL }                                \
    }
#define ibc_applications_fee_v1_IdentifiedPacketFees_init_default          \
    {                                                                      \
        false, ibc_core_channel_v1_PacketId_init_default, { {NULL}, NULL } \
    }
#define ibc_applications_fee_v1_Fee_init_zero            \
    {                                                    \
        {{NULL}, NULL}, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define ibc_applications_fee_v1_PacketFee_init_zero                                    \
    {                                                                                  \
        false, ibc_applications_fee_v1_Fee_init_zero, {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define ibc_applications_fee_v1_PacketFees_init_zero \
    {                                                \
        { {NULL}, NULL }                             \
    }
#define ibc_applications_fee_v1_IdentifiedPacketFees_init_zero          \
    {                                                                   \
        false, ibc_core_channel_v1_PacketId_init_zero, { {NULL}, NULL } \
    }

/* Field tags (for use in manual encoding/decoding) */
#define ibc_applications_fee_v1_Fee_recv_fee_tag 1
#define ibc_applications_fee_v1_Fee_ack_fee_tag 2
#define ibc_applications_fee_v1_Fee_timeout_fee_tag 3
#define ibc_applications_fee_v1_PacketFee_fee_tag 1
#define ibc_applications_fee_v1_PacketFee_refund_address_tag 2
#define ibc_applications_fee_v1_PacketFee_relayers_tag 3
#define ibc_applications_fee_v1_PacketFees_packet_fees_tag 1
#define ibc_applications_fee_v1_IdentifiedPacketFees_packet_id_tag 1
#define ibc_applications_fee_v1_IdentifiedPacketFees_packet_fees_tag 2

/* Struct field encoding specification for nanopb */
#define ibc_applications_fee_v1_Fee_FIELDLIST(X, a) \
    X(a, CALLBACK, REPEATED, MESSAGE, recv_fee, 1)  \
    X(a, CALLBACK, REPEATED, MESSAGE, ack_fee, 2)   \
    X(a, CALLBACK, REPEATED, MESSAGE, timeout_fee, 3)
#define ibc_applications_fee_v1_Fee_CALLBACK pb_default_field_callback
#define ibc_applications_fee_v1_Fee_DEFAULT NULL
#define ibc_applications_fee_v1_Fee_recv_fee_MSGTYPE cosmos_base_v1beta1_Coin
#define ibc_applications_fee_v1_Fee_ack_fee_MSGTYPE cosmos_base_v1beta1_Coin
#define ibc_applications_fee_v1_Fee_timeout_fee_MSGTYPE cosmos_base_v1beta1_Coin

#define ibc_applications_fee_v1_PacketFee_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, fee, 1)               \
    X(a, CALLBACK, SINGULAR, STRING, refund_address, 2)   \
    X(a, CALLBACK, REPEATED, STRING, relayers, 3)
#define ibc_applications_fee_v1_PacketFee_CALLBACK pb_default_field_callback
#define ibc_applications_fee_v1_PacketFee_DEFAULT NULL
#define ibc_applications_fee_v1_PacketFee_fee_MSGTYPE ibc_applications_fee_v1_Fee

#define ibc_applications_fee_v1_PacketFees_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, packet_fees, 1)
#define ibc_applications_fee_v1_PacketFees_CALLBACK pb_default_field_callback
#define ibc_applications_fee_v1_PacketFees_DEFAULT NULL
#define ibc_applications_fee_v1_PacketFees_packet_fees_MSGTYPE ibc_applications_fee_v1_PacketFee

#define ibc_applications_fee_v1_IdentifiedPacketFees_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, packet_id, 1)                    \
    X(a, CALLBACK, REPEATED, MESSAGE, packet_fees, 2)
#define ibc_applications_fee_v1_IdentifiedPacketFees_CALLBACK pb_default_field_callback
#define ibc_applications_fee_v1_IdentifiedPacketFees_DEFAULT NULL
#define ibc_applications_fee_v1_IdentifiedPacketFees_packet_id_MSGTYPE ibc_core_channel_v1_PacketId
#define ibc_applications_fee_v1_IdentifiedPacketFees_packet_fees_MSGTYPE ibc_applications_fee_v1_PacketFee

extern const pb_msgdesc_t ibc_applications_fee_v1_Fee_msg;
extern const pb_msgdesc_t ibc_applications_fee_v1_PacketFee_msg;
extern const pb_msgdesc_t ibc_applications_fee_v1_PacketFees_msg;
extern const pb_msgdesc_t ibc_applications_fee_v1_IdentifiedPacketFees_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ibc_applications_fee_v1_Fee_fields &ibc_applications_fee_v1_Fee_msg
#define ibc_applications_fee_v1_PacketFee_fields &ibc_applications_fee_v1_PacketFee_msg
#define ibc_applications_fee_v1_PacketFees_fields &ibc_applications_fee_v1_PacketFees_msg
#define ibc_applications_fee_v1_IdentifiedPacketFees_fields &ibc_applications_fee_v1_IdentifiedPacketFees_msg

/* Maximum encoded size of messages (where known) */
/* ibc_applications_fee_v1_Fee_size depends on runtime parameters */
/* ibc_applications_fee_v1_PacketFee_size depends on runtime parameters */
/* ibc_applications_fee_v1_PacketFees_size depends on runtime parameters */
/* ibc_applications_fee_v1_IdentifiedPacketFees_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
