/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ibc/applications/fee/v1/fee.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ibc_applications_fee_v1_Fee, ibc_applications_fee_v1_Fee, AUTO)

PB_BIND(ibc_applications_fee_v1_PacketFee, ibc_applications_fee_v1_PacketFee, AUTO)

PB_BIND(ibc_applications_fee_v1_PacketFees, ibc_applications_fee_v1_PacketFees, AUTO)

PB_BIND(ibc_applications_fee_v1_IdentifiedPacketFees, ibc_applications_fee_v1_IdentifiedPacketFees, AUTO)
