/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ibc/applications/fee/v1/genesis.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ibc_applications_fee_v1_GenesisState, ibc_applications_fee_v1_GenesisState, AUTO)

PB_BIND(ibc_applications_fee_v1_FeeEnabledChannel, ibc_applications_fee_v1_FeeEnabledChannel, AUTO)

PB_BIND(ibc_applications_fee_v1_RegisteredPayee, ibc_applications_fee_v1_RegisteredPayee, AUTO)

PB_BIND(ibc_applications_fee_v1_RegisteredCounterpartyPayee, ibc_applications_fee_v1_RegisteredCounterpartyPayee, AUTO)

PB_BIND(ibc_applications_fee_v1_ForwardRelayerAddress, ibc_applications_fee_v1_ForwardRelayerAddress, AUTO)
