/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/feegrant/v1beta1/feegrant.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_feegrant_v1beta1_BasicAllowance, cosmos_feegrant_v1beta1_BasicAllowance, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_PeriodicAllowance, cosmos_feegrant_v1beta1_PeriodicAllowance, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_AllowedMsgAllowance, cosmos_feegrant_v1beta1_AllowedMsgAllowance, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_Grant, cosmos_feegrant_v1beta1_Grant, AUTO)
