/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/feegrant/v1beta1/query.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_feegrant_v1beta1_QueryAllowanceRequest, cosmos_feegrant_v1beta1_QueryAllowanceRequest, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_QueryAllowanceResponse, cosmos_feegrant_v1beta1_QueryAllowanceResponse, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_QueryAllowancesRequest, cosmos_feegrant_v1beta1_QueryAllowancesRequest, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_QueryAllowancesResponse, cosmos_feegrant_v1beta1_QueryAllowancesResponse, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_QueryAllowancesByGranterRequest, cosmos_feegrant_v1beta1_QueryAllowancesByGranterRequest,
        AUTO)

PB_BIND(cosmos_feegrant_v1beta1_QueryAllowancesByGranterResponse, cosmos_feegrant_v1beta1_QueryAllowancesByGranterResponse,
        AUTO)
