/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/feegrant/v1beta1/tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_feegrant_v1beta1_MsgGrantAllowance, cosmos_feegrant_v1beta1_MsgGrantAllowance, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_MsgGrantAllowanceResponse, cosmos_feegrant_v1beta1_MsgGrantAllowanceResponse, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_MsgRevokeAllowance, cosmos_feegrant_v1beta1_MsgRevokeAllowance, AUTO)

PB_BIND(cosmos_feegrant_v1beta1_MsgRevokeAllowanceResponse, cosmos_feegrant_v1beta1_MsgRevokeAllowanceResponse, AUTO)
