/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "tendermint/abci/types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tendermint_abci_Request, tendermint_abci_Request, 2)

PB_BIND(tendermint_abci_RequestEcho, tendermint_abci_RequestEcho, AUTO)

PB_BIND(tendermint_abci_RequestFlush, tendermint_abci_RequestFlush, AUTO)

PB_BIND(tendermint_abci_RequestInfo, tendermint_abci_RequestInfo, AUTO)

PB_BIND(tendermint_abci_RequestInitChain, tendermint_abci_RequestInitChain, AUTO)

PB_BIND(tendermint_abci_RequestQuery, tendermint_abci_RequestQuery, AUTO)

PB_BIND(tendermint_abci_RequestBeginBlock, tendermint_abci_RequestBeginBlock, 2)

PB_BIND(tendermint_abci_RequestCheckTx, tendermint_abci_RequestCheckTx, AUTO)

PB_BIND(tendermint_abci_RequestDeliverTx, tendermint_abci_RequestDeliverTx, AUTO)

PB_BIND(tendermint_abci_RequestEndBlock, tendermint_abci_RequestEndBlock, AUTO)

PB_BIND(tendermint_abci_RequestCommit, tendermint_abci_RequestCommit, AUTO)

PB_BIND(tendermint_abci_RequestListSnapshots, tendermint_abci_RequestListSnapshots, AUTO)

PB_BIND(tendermint_abci_RequestOfferSnapshot, tendermint_abci_RequestOfferSnapshot, AUTO)

PB_BIND(tendermint_abci_RequestLoadSnapshotChunk, tendermint_abci_RequestLoadSnapshotChunk, AUTO)

PB_BIND(tendermint_abci_RequestApplySnapshotChunk, tendermint_abci_RequestApplySnapshotChunk, AUTO)

PB_BIND(tendermint_abci_RequestPrepareProposal, tendermint_abci_RequestPrepareProposal, AUTO)

PB_BIND(tendermint_abci_RequestProcessProposal, tendermint_abci_RequestProcessProposal, AUTO)

PB_BIND(tendermint_abci_Response, tendermint_abci_Response, AUTO)

PB_BIND(tendermint_abci_ResponseException, tendermint_abci_ResponseException, AUTO)

PB_BIND(tendermint_abci_ResponseEcho, tendermint_abci_ResponseEcho, AUTO)

PB_BIND(tendermint_abci_ResponseFlush, tendermint_abci_ResponseFlush, AUTO)

PB_BIND(tendermint_abci_ResponseInfo, tendermint_abci_ResponseInfo, AUTO)

PB_BIND(tendermint_abci_ResponseInitChain, tendermint_abci_ResponseInitChain, AUTO)

PB_BIND(tendermint_abci_ResponseQuery, tendermint_abci_ResponseQuery, AUTO)

PB_BIND(tendermint_abci_ResponseBeginBlock, tendermint_abci_ResponseBeginBlock, AUTO)

PB_BIND(tendermint_abci_ResponseCheckTx, tendermint_abci_ResponseCheckTx, AUTO)

PB_BIND(tendermint_abci_ResponseDeliverTx, tendermint_abci_ResponseDeliverTx, AUTO)

PB_BIND(tendermint_abci_ResponseEndBlock, tendermint_abci_ResponseEndBlock, AUTO)

PB_BIND(tendermint_abci_ResponseCommit, tendermint_abci_ResponseCommit, AUTO)

PB_BIND(tendermint_abci_ResponseListSnapshots, tendermint_abci_ResponseListSnapshots, AUTO)

PB_BIND(tendermint_abci_ResponseOfferSnapshot, tendermint_abci_ResponseOfferSnapshot, AUTO)

PB_BIND(tendermint_abci_ResponseLoadSnapshotChunk, tendermint_abci_ResponseLoadSnapshotChunk, AUTO)

PB_BIND(tendermint_abci_ResponseApplySnapshotChunk, tendermint_abci_ResponseApplySnapshotChunk, AUTO)

PB_BIND(tendermint_abci_ResponsePrepareProposal, tendermint_abci_ResponsePrepareProposal, AUTO)

PB_BIND(tendermint_abci_ResponseProcessProposal, tendermint_abci_ResponseProcessProposal, AUTO)

PB_BIND(tendermint_abci_CommitInfo, tendermint_abci_CommitInfo, AUTO)

PB_BIND(tendermint_abci_ExtendedCommitInfo, tendermint_abci_ExtendedCommitInfo, AUTO)

PB_BIND(tendermint_abci_Event, tendermint_abci_Event, AUTO)

PB_BIND(tendermint_abci_EventAttribute, tendermint_abci_EventAttribute, AUTO)

PB_BIND(tendermint_abci_TxResult, tendermint_abci_TxResult, AUTO)

PB_BIND(tendermint_abci_Validator, tendermint_abci_Validator, AUTO)

PB_BIND(tendermint_abci_ValidatorUpdate, tendermint_abci_ValidatorUpdate, AUTO)

PB_BIND(tendermint_abci_VoteInfo, tendermint_abci_VoteInfo, AUTO)

PB_BIND(tendermint_abci_ExtendedVoteInfo, tendermint_abci_ExtendedVoteInfo, AUTO)

PB_BIND(tendermint_abci_Misbehavior, tendermint_abci_Misbehavior, AUTO)

PB_BIND(tendermint_abci_Snapshot, tendermint_abci_Snapshot, AUTO)
