/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_CRISIS_V1BETA1_COSMOS_CRISIS_V1BETA1_GENESIS_PB_H_INCLUDED
#define PB_COSMOS_CRISIS_V1BETA1_COSMOS_CRISIS_V1BETA1_GENESIS_PB_H_INCLUDED
#include <pb.h>

#include "amino/amino.pb.h"
#include "cosmos/base/v1beta1/coin.pb.h"
#include "gogoproto/gogo.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* GenesisState defines the crisis module's genesis state. */
typedef struct _cosmos_crisis_v1beta1_GenesisState {
    /* constant_fee is the fee used to verify the invariant in the crisis
 module. */
    bool has_constant_fee;
    cosmos_base_v1beta1_Coin constant_fee;
} cosmos_crisis_v1beta1_GenesisState;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_crisis_v1beta1_GenesisState_init_default \
    { false, cosmos_base_v1beta1_Coin_init_default }
#define cosmos_crisis_v1beta1_GenesisState_init_zero \
    { false, cosmos_base_v1beta1_Coin_init_zero }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_crisis_v1beta1_GenesisState_constant_fee_tag 3

/* Struct field encoding specification for nanopb */
#define cosmos_crisis_v1beta1_GenesisState_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, constant_fee, 3)
#define cosmos_crisis_v1beta1_GenesisState_CALLBACK NULL
#define cosmos_crisis_v1beta1_GenesisState_DEFAULT NULL
#define cosmos_crisis_v1beta1_GenesisState_constant_fee_MSGTYPE cosmos_base_v1beta1_Coin

extern const pb_msgdesc_t cosmos_crisis_v1beta1_GenesisState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_crisis_v1beta1_GenesisState_fields &cosmos_crisis_v1beta1_GenesisState_msg

/* Maximum encoded size of messages (where known) */
#if defined(cosmos_base_v1beta1_Coin_size)
#define COSMOS_CRISIS_V1BETA1_COSMOS_CRISIS_V1BETA1_GENESIS_PB_H_MAX_SIZE cosmos_crisis_v1beta1_GenesisState_size
#define cosmos_crisis_v1beta1_GenesisState_size (6 + cosmos_base_v1beta1_Coin_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
