/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/ics23/v1/proofs.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_ics23_v1_ExistenceProof, cosmos_ics23_v1_ExistenceProof, AUTO)

PB_BIND(cosmos_ics23_v1_NonExistenceProof, cosmos_ics23_v1_NonExistenceProof, AUTO)

PB_BIND(cosmos_ics23_v1_CommitmentProof, cosmos_ics23_v1_CommitmentProof, AUTO)

PB_BIND(cosmos_ics23_v1_LeafOp, cosmos_ics23_v1_LeafOp, AUTO)

PB_BIND(cosmos_ics23_v1_InnerOp, cosmos_ics23_v1_InnerOp, AUTO)

PB_BIND(cosmos_ics23_v1_ProofSpec, cosmos_ics23_v1_ProofSpec, AUTO)

PB_BIND(cosmos_ics23_v1_InnerSpec, cosmos_ics23_v1_InnerSpec, AUTO)

PB_BIND(cosmos_ics23_v1_BatchProof, cosmos_ics23_v1_BatchProof, AUTO)

PB_BIND(cosmos_ics23_v1_BatchEntry, cosmos_ics23_v1_BatchEntry, AUTO)

PB_BIND(cosmos_ics23_v1_CompressedBatchProof, cosmos_ics23_v1_CompressedBatchProof, AUTO)

PB_BIND(cosmos_ics23_v1_CompressedBatchEntry, cosmos_ics23_v1_CompressedBatchEntry, AUTO)

PB_BIND(cosmos_ics23_v1_CompressedExistenceProof, cosmos_ics23_v1_CompressedExistenceProof, AUTO)

PB_BIND(cosmos_ics23_v1_CompressedNonExistenceProof, cosmos_ics23_v1_CompressedNonExistenceProof, AUTO)
