/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_AUTH_V1BETA1_COSMOS_AUTH_V1BETA1_GENESIS_PB_H_INCLUDED
#define PB_COSMOS_AUTH_V1BETA1_COSMOS_AUTH_V1BETA1_GENESIS_PB_H_INCLUDED
#include <pb.h>

#include "amino/amino.pb.h"
#include "cosmos/auth/v1beta1/auth.pb.h"
#include "gogoproto/gogo.pb.h"
#include "google/protobuf/any.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* GenesisState defines the auth module's genesis state. */
typedef struct _cosmos_auth_v1beta1_GenesisState {
    /* params defines all the parameters of the module. */
    bool has_params;
    cosmos_auth_v1beta1_Params params;
    /* accounts are the accounts present at genesis. */
    pb_callback_t accounts;
} cosmos_auth_v1beta1_GenesisState;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_auth_v1beta1_GenesisState_init_default                    \
    {                                                                    \
        false, cosmos_auth_v1beta1_Params_init_default, { {NULL}, NULL } \
    }
#define cosmos_auth_v1beta1_GenesisState_init_zero                    \
    {                                                                 \
        false, cosmos_auth_v1beta1_Params_init_zero, { {NULL}, NULL } \
    }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_auth_v1beta1_GenesisState_params_tag 1
#define cosmos_auth_v1beta1_GenesisState_accounts_tag 2

/* Struct field encoding specification for nanopb */
#define cosmos_auth_v1beta1_GenesisState_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, params, 1)           \
    X(a, CALLBACK, REPEATED, MESSAGE, accounts, 2)
#define cosmos_auth_v1beta1_GenesisState_CALLBACK pb_default_field_callback
#define cosmos_auth_v1beta1_GenesisState_DEFAULT NULL
#define cosmos_auth_v1beta1_GenesisState_params_MSGTYPE cosmos_auth_v1beta1_Params
#define cosmos_auth_v1beta1_GenesisState_accounts_MSGTYPE google_protobuf_Any

extern const pb_msgdesc_t cosmos_auth_v1beta1_GenesisState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_auth_v1beta1_GenesisState_fields &cosmos_auth_v1beta1_GenesisState_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_auth_v1beta1_GenesisState_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
