/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/authz/v1beta1/query.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_authz_v1beta1_QueryGrantsRequest, cosmos_authz_v1beta1_QueryGrantsRequest, AUTO)

PB_BIND(cosmos_authz_v1beta1_QueryGrantsResponse, cosmos_authz_v1beta1_QueryGrantsResponse, AUTO)

PB_BIND(cosmos_authz_v1beta1_QueryGranterGrantsRequest, cosmos_authz_v1beta1_QueryGranterGrantsRequest, AUTO)

PB_BIND(cosmos_authz_v1beta1_QueryGranterGrantsResponse, cosmos_authz_v1beta1_QueryGranterGrantsResponse, AUTO)

PB_BIND(cosmos_authz_v1beta1_QueryGranteeGrantsRequest, cosmos_authz_v1beta1_QueryGranteeGrantsRequest, AUTO)

PB_BIND(cosmos_authz_v1beta1_QueryGranteeGrantsResponse, cosmos_authz_v1beta1_QueryGranteeGrantsResponse, AUTO)
