/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/authz/v1beta1/tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_authz_v1beta1_MsgGrant, cosmos_authz_v1beta1_MsgGrant, AUTO)

PB_BIND(cosmos_authz_v1beta1_MsgExecResponse, cosmos_authz_v1beta1_MsgExecResponse, AUTO)

PB_BIND(cosmos_authz_v1beta1_MsgExec, cosmos_authz_v1beta1_MsgExec, AUTO)

PB_BIND(cosmos_authz_v1beta1_MsgGrantResponse, cosmos_authz_v1beta1_MsgGrantResponse, AUTO)

PB_BIND(cosmos_authz_v1beta1_MsgRevoke, cosmos_authz_v1beta1_MsgRevoke, AUTO)

PB_BIND(cosmos_authz_v1beta1_MsgRevokeResponse, cosmos_authz_v1beta1_MsgRevokeResponse, AUTO)
