/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/gov/v1beta1/query.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_gov_v1beta1_QueryProposalRequest, cosmos_gov_v1beta1_QueryProposalRequest, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryProposalResponse, cosmos_gov_v1beta1_QueryProposalResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryProposalsRequest, cosmos_gov_v1beta1_QueryProposalsRequest, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryProposalsResponse, cosmos_gov_v1beta1_QueryProposalsResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryVoteRequest, cosmos_gov_v1beta1_QueryVoteRequest, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryVoteResponse, cosmos_gov_v1beta1_QueryVoteResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryVotesRequest, cosmos_gov_v1beta1_QueryVotesRequest, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryVotesResponse, cosmos_gov_v1beta1_QueryVotesResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryParamsRequest, cosmos_gov_v1beta1_QueryParamsRequest, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryParamsResponse, cosmos_gov_v1beta1_QueryParamsResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryDepositRequest, cosmos_gov_v1beta1_QueryDepositRequest, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryDepositResponse, cosmos_gov_v1beta1_QueryDepositResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryDepositsRequest, cosmos_gov_v1beta1_QueryDepositsRequest, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryDepositsResponse, cosmos_gov_v1beta1_QueryDepositsResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryTallyResultRequest, cosmos_gov_v1beta1_QueryTallyResultRequest, AUTO)

PB_BIND(cosmos_gov_v1beta1_QueryTallyResultResponse, cosmos_gov_v1beta1_QueryTallyResultResponse, AUTO)
