/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/gov/v1beta1/tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_gov_v1beta1_MsgSubmitProposal, cosmos_gov_v1beta1_MsgSubmitProposal, AUTO)

PB_BIND(cosmos_gov_v1beta1_MsgSubmitProposalResponse, cosmos_gov_v1beta1_MsgSubmitProposalResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_MsgVote, cosmos_gov_v1beta1_MsgVote, AUTO)

PB_BIND(cosmos_gov_v1beta1_MsgVoteResponse, cosmos_gov_v1beta1_MsgVoteResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_MsgVoteWeighted, cosmos_gov_v1beta1_MsgVoteWeighted, AUTO)

PB_BIND(cosmos_gov_v1beta1_MsgVoteWeightedResponse, cosmos_gov_v1beta1_MsgVoteWeightedResponse, AUTO)

PB_BIND(cosmos_gov_v1beta1_MsgDeposit, cosmos_gov_v1beta1_MsgDeposit, AUTO)

PB_BIND(cosmos_gov_v1beta1_MsgDepositResponse, cosmos_gov_v1beta1_MsgDepositResponse, AUTO)
