/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_BANK_MODULE_V1_COSMOS_BANK_MODULE_V1_MODULE_PB_H_INCLUDED
#define PB_COSMOS_BANK_MODULE_V1_COSMOS_BANK_MODULE_V1_MODULE_PB_H_INCLUDED
#include <pb.h>

#include "cosmos/app/v1alpha1/module.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Module is the config object of the bank module. */
typedef struct _cosmos_bank_module_v1_Module {
    /* blocked_module_accounts configures exceptional module accounts which should be blocked from receiving funds.
 If left empty it defaults to the list of account names supplied in the auth module configuration as
 module_account_permissions */
    pb_callback_t blocked_module_accounts_override;
    /* authority defines the custom module authority. If not set, defaults to the governance module. */
    pb_callback_t authority;
} cosmos_bank_module_v1_Module;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_bank_module_v1_Module_init_default \
    {                                             \
        {{NULL}, NULL}, { {NULL}, NULL }          \
    }
#define cosmos_bank_module_v1_Module_init_zero \
    {                                          \
        {{NULL}, NULL}, { {NULL}, NULL }       \
    }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_bank_module_v1_Module_blocked_module_accounts_override_tag 1
#define cosmos_bank_module_v1_Module_authority_tag 2

/* Struct field encoding specification for nanopb */
#define cosmos_bank_module_v1_Module_FIELDLIST(X, a)                      \
    X(a, CALLBACK, REPEATED, STRING, blocked_module_accounts_override, 1) \
    X(a, CALLBACK, SINGULAR, STRING, authority, 2)
#define cosmos_bank_module_v1_Module_CALLBACK pb_default_field_callback
#define cosmos_bank_module_v1_Module_DEFAULT NULL

extern const pb_msgdesc_t cosmos_bank_module_v1_Module_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_bank_module_v1_Module_fields &cosmos_bank_module_v1_Module_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_bank_module_v1_Module_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
