/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "penumbra/crypto/tct/v1/tct.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(penumbra_crypto_tct_v1_StateCommitment, penumbra_crypto_tct_v1_StateCommitment, AUTO)

PB_BIND(penumbra_crypto_tct_v1_MerkleRoot, penumbra_crypto_tct_v1_MerkleRoot, AUTO)

PB_BIND(penumbra_crypto_tct_v1_StateCommitmentProof, penumbra_crypto_tct_v1_StateCommitmentProof, AUTO)

PB_BIND(penumbra_crypto_tct_v1_MerklePathChunk, penumbra_crypto_tct_v1_MerklePathChunk, AUTO)
