/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "google/protobuf/descriptor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_protobuf_MessageOptions, google_protobuf_MessageOptions, 2)

PB_BIND(google_protobuf_UninterpretedOption, google_protobuf_UninterpretedOption, AUTO)

PB_BIND(google_protobuf_UninterpretedOption_NamePart, google_protobuf_UninterpretedOption_NamePart, AUTO)

PB_BIND(google_protobuf_FeatureSet, google_protobuf_FeatureSet, 2)

#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif
