/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_BANK_V1BETA1_COSMOS_BANK_V1BETA1_AUTHZ_PB_H_INCLUDED
#define PB_COSMOS_BANK_V1BETA1_COSMOS_BANK_V1BETA1_AUTHZ_PB_H_INCLUDED
#include <pb.h>

#include "amino/amino.pb.h"
#include "cosmos/base/v1beta1/coin.pb.h"
#include "cosmos_proto/cosmos.pb.h"
#include "gogoproto/gogo.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* SendAuthorization allows the grantee to spend up to spend_limit coins from
 the granter's account.

 Since: cosmos-sdk 0.43 */
typedef struct _cosmos_bank_v1beta1_SendAuthorization {
    pb_callback_t spend_limit;
    /* allow_list specifies an optional list of addresses to whom the grantee can send tokens on behalf of the
 granter. If omitted, any recipient is allowed.

 Since: cosmos-sdk 0.47 */
    pb_callback_t allow_list;
} cosmos_bank_v1beta1_SendAuthorization;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_bank_v1beta1_SendAuthorization_init_default \
    {                                                      \
        {{NULL}, NULL}, { {NULL}, NULL }                   \
    }
#define cosmos_bank_v1beta1_SendAuthorization_init_zero \
    {                                                   \
        {{NULL}, NULL}, { {NULL}, NULL }                \
    }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_bank_v1beta1_SendAuthorization_spend_limit_tag 1
#define cosmos_bank_v1beta1_SendAuthorization_allow_list_tag 2

/* Struct field encoding specification for nanopb */
#define cosmos_bank_v1beta1_SendAuthorization_FIELDLIST(X, a) \
    X(a, CALLBACK, REPEATED, MESSAGE, spend_limit, 1)         \
    X(a, CALLBACK, REPEATED, STRING, allow_list, 2)
#define cosmos_bank_v1beta1_SendAuthorization_CALLBACK pb_default_field_callback
#define cosmos_bank_v1beta1_SendAuthorization_DEFAULT NULL
#define cosmos_bank_v1beta1_SendAuthorization_spend_limit_MSGTYPE cosmos_base_v1beta1_Coin

extern const pb_msgdesc_t cosmos_bank_v1beta1_SendAuthorization_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_bank_v1beta1_SendAuthorization_fields &cosmos_bank_v1beta1_SendAuthorization_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_bank_v1beta1_SendAuthorization_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
