/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_APP_V1ALPHA1_COSMOS_APP_V1ALPHA1_QUERY_PB_H_INCLUDED
#define PB_COSMOS_APP_V1ALPHA1_COSMOS_APP_V1ALPHA1_QUERY_PB_H_INCLUDED
#include <pb.h>

#include "cosmos/app/v1alpha1/config.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* QueryConfigRequest is the Query/Config request type. */
typedef struct _cosmos_app_v1alpha1_QueryConfigRequest {
    char dummy_field;
} cosmos_app_v1alpha1_QueryConfigRequest;

/* QueryConfigRequest is the Query/Config response type. */
typedef struct _cosmos_app_v1alpha1_QueryConfigResponse {
    /* config is the current app config. */
    bool has_config;
    cosmos_app_v1alpha1_Config config;
} cosmos_app_v1alpha1_QueryConfigResponse;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_app_v1alpha1_QueryConfigRequest_init_default \
    { 0 }
#define cosmos_app_v1alpha1_QueryConfigResponse_init_default \
    { false, cosmos_app_v1alpha1_Config_init_default }
#define cosmos_app_v1alpha1_QueryConfigRequest_init_zero \
    { 0 }
#define cosmos_app_v1alpha1_QueryConfigResponse_init_zero \
    { false, cosmos_app_v1alpha1_Config_init_zero }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_app_v1alpha1_QueryConfigResponse_config_tag 1

/* Struct field encoding specification for nanopb */
#define cosmos_app_v1alpha1_QueryConfigRequest_FIELDLIST(X, a)

#define cosmos_app_v1alpha1_QueryConfigRequest_CALLBACK NULL
#define cosmos_app_v1alpha1_QueryConfigRequest_DEFAULT NULL

#define cosmos_app_v1alpha1_QueryConfigResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, config, 1)
#define cosmos_app_v1alpha1_QueryConfigResponse_CALLBACK NULL
#define cosmos_app_v1alpha1_QueryConfigResponse_DEFAULT NULL
#define cosmos_app_v1alpha1_QueryConfigResponse_config_MSGTYPE cosmos_app_v1alpha1_Config

extern const pb_msgdesc_t cosmos_app_v1alpha1_QueryConfigRequest_msg;
extern const pb_msgdesc_t cosmos_app_v1alpha1_QueryConfigResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_app_v1alpha1_QueryConfigRequest_fields &cosmos_app_v1alpha1_QueryConfigRequest_msg
#define cosmos_app_v1alpha1_QueryConfigResponse_fields &cosmos_app_v1alpha1_QueryConfigResponse_msg

/* Maximum encoded size of messages (where known) */
#define cosmos_app_v1alpha1_QueryConfigRequest_size 0
#if defined(cosmos_app_v1alpha1_Config_size)
#define COSMOS_APP_V1ALPHA1_COSMOS_APP_V1ALPHA1_QUERY_PB_H_MAX_SIZE cosmos_app_v1alpha1_QueryConfigResponse_size
#define cosmos_app_v1alpha1_QueryConfigResponse_size (6 + cosmos_app_v1alpha1_Config_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
