/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "tendermint/types/evidence.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tendermint_types_Evidence, tendermint_types_Evidence, 2)

PB_BIND(tendermint_types_DuplicateVoteEvidence, tendermint_types_DuplicateVoteEvidence, 2)

PB_BIND(tendermint_types_LightClientAttackEvidence, tendermint_types_LightClientAttackEvidence, 2)

PB_BIND(tendermint_types_EvidenceList, tendermint_types_EvidenceList, AUTO)
