/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "tendermint/types/types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tendermint_types_PartSetHeader, tendermint_types_PartSetHeader, AUTO)

PB_BIND(tendermint_types_Part, tendermint_types_Part, AUTO)

PB_BIND(tendermint_types_BlockID, tendermint_types_BlockID, AUTO)

PB_BIND(tendermint_types_Header, tendermint_types_Header, 2)

PB_BIND(tendermint_types_Data, tendermint_types_Data, AUTO)

PB_BIND(tendermint_types_Vote, tendermint_types_Vote, AUTO)

PB_BIND(tendermint_types_Commit, tendermint_types_Commit, AUTO)

PB_BIND(tendermint_types_CommitSig, tendermint_types_CommitSig, AUTO)

PB_BIND(tendermint_types_Proposal, tendermint_types_Proposal, AUTO)

PB_BIND(tendermint_types_SignedHeader, tendermint_types_SignedHeader, 2)

PB_BIND(tendermint_types_LightBlock, tendermint_types_LightBlock, 2)

PB_BIND(tendermint_types_BlockMeta, tendermint_types_BlockMeta, 2)

PB_BIND(tendermint_types_TxProof, tendermint_types_TxProof, AUTO)
