/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "tendermint/types/validator.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tendermint_types_ValidatorSet, tendermint_types_ValidatorSet, AUTO)

PB_BIND(tendermint_types_Validator, tendermint_types_Validator, AUTO)

PB_BIND(tendermint_types_SimpleValidator, tendermint_types_SimpleValidator, AUTO)
