/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_GOV_MODULE_V1_COSMOS_GOV_MODULE_V1_MODULE_PB_H_INCLUDED
#define PB_COSMOS_GOV_MODULE_V1_COSMOS_GOV_MODULE_V1_MODULE_PB_H_INCLUDED
#include <pb.h>

#include "cosmos/app/v1alpha1/module.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Module is the config object of the gov module. */
typedef struct _cosmos_gov_module_v1_Module {
    /* max_metadata_len defines the maximum proposal metadata length.
 Defaults to 255 if not explicitly set. */
    uint64_t max_metadata_len;
    /* authority defines the custom module authority. If not set, defaults to the governance module. */
    pb_callback_t authority;
} cosmos_gov_module_v1_Module;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_gov_module_v1_Module_init_default \
    {                                            \
        0, { {NULL}, NULL }                      \
    }
#define cosmos_gov_module_v1_Module_init_zero \
    {                                         \
        0, { {NULL}, NULL }                   \
    }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_gov_module_v1_Module_max_metadata_len_tag 1
#define cosmos_gov_module_v1_Module_authority_tag 2

/* Struct field encoding specification for nanopb */
#define cosmos_gov_module_v1_Module_FIELDLIST(X, a)     \
    X(a, STATIC, SINGULAR, UINT64, max_metadata_len, 1) \
    X(a, CALLBACK, SINGULAR, STRING, authority, 2)
#define cosmos_gov_module_v1_Module_CALLBACK pb_default_field_callback
#define cosmos_gov_module_v1_Module_DEFAULT NULL

extern const pb_msgdesc_t cosmos_gov_module_v1_Module_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_gov_module_v1_Module_fields &cosmos_gov_module_v1_Module_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_gov_module_v1_Module_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
