/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/orm/module/v1alpha1/module.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_orm_module_v1alpha1_Module, cosmos_orm_module_v1alpha1_Module, AUTO)
