/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "capability/v1/capability.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(capability_v1_Capability, capability_v1_Capability, AUTO)

PB_BIND(capability_v1_Owner, capability_v1_Owner, AUTO)

PB_BIND(capability_v1_CapabilityOwners, capability_v1_CapabilityOwners, AUTO)
