/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/upgrade/v1beta1/query.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_upgrade_v1beta1_QueryCurrentPlanRequest, cosmos_upgrade_v1beta1_QueryCurrentPlanRequest, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_QueryCurrentPlanResponse, cosmos_upgrade_v1beta1_QueryCurrentPlanResponse, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_QueryAppliedPlanRequest, cosmos_upgrade_v1beta1_QueryAppliedPlanRequest, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_QueryAppliedPlanResponse, cosmos_upgrade_v1beta1_QueryAppliedPlanResponse, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest, cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest,
        AUTO)

PB_BIND(cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse,
        cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_QueryModuleVersionsRequest, cosmos_upgrade_v1beta1_QueryModuleVersionsRequest, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_QueryModuleVersionsResponse, cosmos_upgrade_v1beta1_QueryModuleVersionsResponse, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_QueryAuthorityRequest, cosmos_upgrade_v1beta1_QueryAuthorityRequest, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_QueryAuthorityResponse, cosmos_upgrade_v1beta1_QueryAuthorityResponse, AUTO)
