/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_UPGRADE_V1BETA1_COSMOS_UPGRADE_V1BETA1_QUERY_PB_H_INCLUDED
#define PB_COSMOS_UPGRADE_V1BETA1_COSMOS_UPGRADE_V1BETA1_QUERY_PB_H_INCLUDED
#include <pb.h>

#include "cosmos/upgrade/v1beta1/upgrade.pb.h"
#include "google/api/annotations.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* QueryCurrentPlanRequest is the request type for the Query/CurrentPlan RPC
 method. */
typedef struct _cosmos_upgrade_v1beta1_QueryCurrentPlanRequest {
    char dummy_field;
} cosmos_upgrade_v1beta1_QueryCurrentPlanRequest;

/* QueryCurrentPlanResponse is the response type for the Query/CurrentPlan RPC
 method. */
typedef struct _cosmos_upgrade_v1beta1_QueryCurrentPlanResponse {
    /* plan is the current upgrade plan. */
    bool has_plan;
    cosmos_upgrade_v1beta1_Plan plan;
} cosmos_upgrade_v1beta1_QueryCurrentPlanResponse;

/* QueryCurrentPlanRequest is the request type for the Query/AppliedPlan RPC
 method. */
typedef struct _cosmos_upgrade_v1beta1_QueryAppliedPlanRequest {
    /* name is the name of the applied plan to query for. */
    pb_callback_t name;
} cosmos_upgrade_v1beta1_QueryAppliedPlanRequest;

/* QueryAppliedPlanResponse is the response type for the Query/AppliedPlan RPC
 method. */
typedef struct _cosmos_upgrade_v1beta1_QueryAppliedPlanResponse {
    /* height is the block height at which the plan was applied. */
    int64_t height;
} cosmos_upgrade_v1beta1_QueryAppliedPlanResponse;

/* QueryUpgradedConsensusStateRequest is the request type for the Query/UpgradedConsensusState
 RPC method. */
typedef struct _cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest {
    /* last height of the current chain must be sent in request
 as this is the height under which next consensus state is stored */
    int64_t last_height;
} cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest;

/* QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState
 RPC method. */
typedef struct _cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse {
    /* Since: cosmos-sdk 0.43 */
    pb_callback_t upgraded_consensus_state;
} cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse;

/* QueryModuleVersionsRequest is the request type for the Query/ModuleVersions
 RPC method.

 Since: cosmos-sdk 0.43 */
typedef struct _cosmos_upgrade_v1beta1_QueryModuleVersionsRequest {
    /* module_name is a field to query a specific module
 consensus version from state. Leaving this empty will
 fetch the full list of module versions from state */
    pb_callback_t module_name;
} cosmos_upgrade_v1beta1_QueryModuleVersionsRequest;

/* QueryModuleVersionsResponse is the response type for the Query/ModuleVersions
 RPC method.

 Since: cosmos-sdk 0.43 */
typedef struct _cosmos_upgrade_v1beta1_QueryModuleVersionsResponse {
    /* module_versions is a list of module names with their consensus versions. */
    pb_callback_t module_versions;
} cosmos_upgrade_v1beta1_QueryModuleVersionsResponse;

/* QueryAuthorityRequest is the request type for Query/Authority

 Since: cosmos-sdk 0.46 */
typedef struct _cosmos_upgrade_v1beta1_QueryAuthorityRequest {
    char dummy_field;
} cosmos_upgrade_v1beta1_QueryAuthorityRequest;

/* QueryAuthorityResponse is the response type for Query/Authority

 Since: cosmos-sdk 0.46 */
typedef struct _cosmos_upgrade_v1beta1_QueryAuthorityResponse {
    pb_callback_t address;
} cosmos_upgrade_v1beta1_QueryAuthorityResponse;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_init_default \
    { 0 }
#define cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_init_default \
    { false, cosmos_upgrade_v1beta1_Plan_init_default }
#define cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_init_default \
    {                                                               \
        { {NULL}, NULL }                                            \
    }
#define cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_init_default \
    { 0 }
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_init_default \
    { 0 }
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_init_default \
    {                                                                           \
        { {NULL}, NULL }                                                        \
    }
#define cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_init_default \
    {                                                                  \
        { {NULL}, NULL }                                               \
    }
#define cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_init_default \
    {                                                                   \
        { {NULL}, NULL }                                                \
    }
#define cosmos_upgrade_v1beta1_QueryAuthorityRequest_init_default \
    { 0 }
#define cosmos_upgrade_v1beta1_QueryAuthorityResponse_init_default \
    {                                                              \
        { {NULL}, NULL }                                           \
    }
#define cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_init_zero \
    { 0 }
#define cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_init_zero \
    { false, cosmos_upgrade_v1beta1_Plan_init_zero }
#define cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_init_zero \
    {                                                            \
        { {NULL}, NULL }                                         \
    }
#define cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_init_zero \
    { 0 }
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_init_zero \
    { 0 }
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_init_zero \
    {                                                                        \
        { {NULL}, NULL }                                                     \
    }
#define cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_init_zero \
    {                                                               \
        { {NULL}, NULL }                                            \
    }
#define cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_init_zero \
    {                                                                \
        { {NULL}, NULL }                                             \
    }
#define cosmos_upgrade_v1beta1_QueryAuthorityRequest_init_zero \
    { 0 }
#define cosmos_upgrade_v1beta1_QueryAuthorityResponse_init_zero \
    {                                                           \
        { {NULL}, NULL }                                        \
    }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_plan_tag 1
#define cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_name_tag 1
#define cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_height_tag 1
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_last_height_tag 1
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_upgraded_consensus_state_tag 2
#define cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_module_name_tag 1
#define cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_module_versions_tag 1
#define cosmos_upgrade_v1beta1_QueryAuthorityResponse_address_tag 1

/* Struct field encoding specification for nanopb */
#define cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_FIELDLIST(X, a)

#define cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_CALLBACK NULL
#define cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_DEFAULT NULL

#define cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, plan, 1)
#define cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_CALLBACK NULL
#define cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_DEFAULT NULL
#define cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_plan_MSGTYPE cosmos_upgrade_v1beta1_Plan

#define cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, name, 1)
#define cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_CALLBACK pb_default_field_callback
#define cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_DEFAULT NULL

#define cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT64, height, 1)
#define cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_CALLBACK NULL
#define cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_DEFAULT NULL

#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_FIELDLIST(X, a) \
    X(a, STATIC, SINGULAR, INT64, last_height, 1)
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_CALLBACK NULL
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_DEFAULT NULL

#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, BYTES, upgraded_consensus_state, 2)
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_CALLBACK pb_default_field_callback
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_DEFAULT NULL

#define cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, module_name, 1)
#define cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_CALLBACK pb_default_field_callback
#define cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_DEFAULT NULL

#define cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_FIELDLIST(X, a) \
    X(a, CALLBACK, REPEATED, MESSAGE, module_versions, 1)
#define cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_CALLBACK pb_default_field_callback
#define cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_DEFAULT NULL
#define cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_module_versions_MSGTYPE cosmos_upgrade_v1beta1_ModuleVersion

#define cosmos_upgrade_v1beta1_QueryAuthorityRequest_FIELDLIST(X, a)

#define cosmos_upgrade_v1beta1_QueryAuthorityRequest_CALLBACK NULL
#define cosmos_upgrade_v1beta1_QueryAuthorityRequest_DEFAULT NULL

#define cosmos_upgrade_v1beta1_QueryAuthorityResponse_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, address, 1)
#define cosmos_upgrade_v1beta1_QueryAuthorityResponse_CALLBACK pb_default_field_callback
#define cosmos_upgrade_v1beta1_QueryAuthorityResponse_DEFAULT NULL

extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_msg;
extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_msg;
extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_msg;
extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_msg;
extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_msg;
extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_msg;
extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_msg;
extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_msg;
extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryAuthorityRequest_msg;
extern const pb_msgdesc_t cosmos_upgrade_v1beta1_QueryAuthorityResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_fields &cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_msg
#define cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_fields &cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_msg
#define cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_fields &cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_msg
#define cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_fields &cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_msg
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_fields \
    &cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_msg
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_fields \
    &cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_msg
#define cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_fields &cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_msg
#define cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_fields &cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_msg
#define cosmos_upgrade_v1beta1_QueryAuthorityRequest_fields &cosmos_upgrade_v1beta1_QueryAuthorityRequest_msg
#define cosmos_upgrade_v1beta1_QueryAuthorityResponse_fields &cosmos_upgrade_v1beta1_QueryAuthorityResponse_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_size depends on runtime parameters */
/* cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateResponse_size depends on runtime parameters */
/* cosmos_upgrade_v1beta1_QueryModuleVersionsRequest_size depends on runtime parameters */
/* cosmos_upgrade_v1beta1_QueryModuleVersionsResponse_size depends on runtime parameters */
/* cosmos_upgrade_v1beta1_QueryAuthorityResponse_size depends on runtime parameters */
#define COSMOS_UPGRADE_V1BETA1_COSMOS_UPGRADE_V1BETA1_QUERY_PB_H_MAX_SIZE \
    cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_size
#define cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_size 11
#define cosmos_upgrade_v1beta1_QueryAuthorityRequest_size 0
#define cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_size 0
#define cosmos_upgrade_v1beta1_QueryUpgradedConsensusStateRequest_size 11
#if defined(cosmos_upgrade_v1beta1_Plan_size)
#define cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_size (6 + cosmos_upgrade_v1beta1_Plan_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
