/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/upgrade/v1beta1/tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_upgrade_v1beta1_MsgSoftwareUpgrade, cosmos_upgrade_v1beta1_MsgSoftwareUpgrade, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_MsgSoftwareUpgradeResponse, cosmos_upgrade_v1beta1_MsgSoftwareUpgradeResponse, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_MsgCancelUpgrade, cosmos_upgrade_v1beta1_MsgCancelUpgrade, AUTO)

PB_BIND(cosmos_upgrade_v1beta1_MsgCancelUpgradeResponse, cosmos_upgrade_v1beta1_MsgCancelUpgradeResponse, AUTO)
