/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/nft/v1beta1/event.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_nft_v1beta1_EventSend, cosmos_nft_v1beta1_EventSend, AUTO)

PB_BIND(cosmos_nft_v1beta1_EventMint, cosmos_nft_v1beta1_EventMint, AUTO)

PB_BIND(cosmos_nft_v1beta1_EventBurn, cosmos_nft_v1beta1_EventBurn, AUTO)
