/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "penumbra/core/keys/v1/keys.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(penumbra_core_keys_v1_Address, penumbra_core_keys_v1_Address, AUTO)

PB_BIND(penumbra_core_keys_v1_AddressView, penumbra_core_keys_v1_AddressView, AUTO)

PB_BIND(penumbra_core_keys_v1_AddressView_Decoded, penumbra_core_keys_v1_AddressView_Decoded, AUTO)

PB_BIND(penumbra_core_keys_v1_AddressView_Opaque, penumbra_core_keys_v1_AddressView_Opaque, AUTO)

PB_BIND(penumbra_core_keys_v1_PayloadKey, penumbra_core_keys_v1_PayloadKey, AUTO)

PB_BIND(penumbra_core_keys_v1_SpendKey, penumbra_core_keys_v1_SpendKey, AUTO)

PB_BIND(penumbra_core_keys_v1_FullViewingKey, penumbra_core_keys_v1_FullViewingKey, AUTO)

PB_BIND(penumbra_core_keys_v1_WalletId, penumbra_core_keys_v1_WalletId, AUTO)

PB_BIND(penumbra_core_keys_v1_Diversifier, penumbra_core_keys_v1_Diversifier, AUTO)

PB_BIND(penumbra_core_keys_v1_AddressIndex, penumbra_core_keys_v1_AddressIndex, AUTO)

PB_BIND(penumbra_core_keys_v1_IdentityKey, penumbra_core_keys_v1_IdentityKey, AUTO)

PB_BIND(penumbra_core_keys_v1_GovernanceKey, penumbra_core_keys_v1_GovernanceKey, AUTO)

PB_BIND(penumbra_core_keys_v1_ConsensusKey, penumbra_core_keys_v1_ConsensusKey, AUTO)
