/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ibc/core/client/v1/client.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ibc_core_client_v1_IdentifiedClientState, ibc_core_client_v1_IdentifiedClientState, AUTO)

PB_BIND(ibc_core_client_v1_ConsensusStateWithHeight, ibc_core_client_v1_ConsensusStateWithHeight, AUTO)

PB_BIND(ibc_core_client_v1_ClientConsensusStates, ibc_core_client_v1_ClientConsensusStates, AUTO)

PB_BIND(ibc_core_client_v1_Height, ibc_core_client_v1_Height, AUTO)

PB_BIND(ibc_core_client_v1_Params, ibc_core_client_v1_Params, AUTO)
