/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ibc/core/client/v1/genesis.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ibc_core_client_v1_GenesisState, ibc_core_client_v1_GenesisState, AUTO)

PB_BIND(ibc_core_client_v1_GenesisMetadata, ibc_core_client_v1_GenesisMetadata, AUTO)

PB_BIND(ibc_core_client_v1_IdentifiedGenesisMetadata, ibc_core_client_v1_IdentifiedGenesisMetadata, AUTO)
