/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "google/api/http.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_api_Http, google_api_Http, AUTO)

PB_BIND(google_api_HttpRule, google_api_HttpRule, AUTO)

PB_BIND(google_api_CustomHttpPattern, google_api_CustomHttpPattern, AUTO)
