/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "penumbra/core/component/community_pool/v1/community_pool.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(penumbra_core_component_community_pool_v1_CommunityPoolParameters,
        penumbra_core_component_community_pool_v1_CommunityPoolParameters, AUTO)

PB_BIND(penumbra_core_component_community_pool_v1_GenesisContent, penumbra_core_component_community_pool_v1_GenesisContent,
        AUTO)

PB_BIND(penumbra_core_component_community_pool_v1_CommunityPoolAssetBalancesRequest,
        penumbra_core_component_community_pool_v1_CommunityPoolAssetBalancesRequest, AUTO)

PB_BIND(penumbra_core_component_community_pool_v1_CommunityPoolAssetBalancesResponse,
        penumbra_core_component_community_pool_v1_CommunityPoolAssetBalancesResponse, AUTO)
