/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ibc/applications/interchain_accounts/host/v1/host.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ibc_applications_interchain_accounts_host_v1_Params, ibc_applications_interchain_accounts_host_v1_Params, AUTO)
