/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_IBC_APPLICATIONS_INTERCHAIN_ACCOUNTS_HOST_V1_IBC_APPLICATIONS_INTERCHAIN_ACCOUNTS_HOST_V1_HOST_PB_H_INCLUDED
#define PB_IBC_APPLICATIONS_INTERCHAIN_ACCOUNTS_HOST_V1_IBC_APPLICATIONS_INTERCHAIN_ACCOUNTS_HOST_V1_HOST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Params defines the set of on-chain interchain accounts parameters.
 The following parameters may be used to disable the host submodule. */
typedef struct _ibc_applications_interchain_accounts_host_v1_Params {
    /* host_enabled enables or disables the host submodule. */
    bool host_enabled;
    /* allow_messages defines a list of sdk message typeURLs allowed to be executed on a host chain. */
    pb_callback_t allow_messages;
} ibc_applications_interchain_accounts_host_v1_Params;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ibc_applications_interchain_accounts_host_v1_Params_init_default \
    {                                                                    \
        0, { {NULL}, NULL }                                              \
    }
#define ibc_applications_interchain_accounts_host_v1_Params_init_zero \
    {                                                                 \
        0, { {NULL}, NULL }                                           \
    }

/* Field tags (for use in manual encoding/decoding) */
#define ibc_applications_interchain_accounts_host_v1_Params_host_enabled_tag 1
#define ibc_applications_interchain_accounts_host_v1_Params_allow_messages_tag 2

/* Struct field encoding specification for nanopb */
#define ibc_applications_interchain_accounts_host_v1_Params_FIELDLIST(X, a) \
    X(a, STATIC, SINGULAR, BOOL, host_enabled, 1)                           \
    X(a, CALLBACK, REPEATED, STRING, allow_messages, 2)
#define ibc_applications_interchain_accounts_host_v1_Params_CALLBACK pb_default_field_callback
#define ibc_applications_interchain_accounts_host_v1_Params_DEFAULT NULL

extern const pb_msgdesc_t ibc_applications_interchain_accounts_host_v1_Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ibc_applications_interchain_accounts_host_v1_Params_fields &ibc_applications_interchain_accounts_host_v1_Params_msg

/* Maximum encoded size of messages (where known) */
/* ibc_applications_interchain_accounts_host_v1_Params_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
