/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "penumbra/cnidarium/v1/cnidarium.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(penumbra_cnidarium_v1_NonVerifiableKeyValueRequest, penumbra_cnidarium_v1_NonVerifiableKeyValueRequest, AUTO)

PB_BIND(penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key, penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key, AUTO)

PB_BIND(penumbra_cnidarium_v1_NonVerifiableKeyValueResponse, penumbra_cnidarium_v1_NonVerifiableKeyValueResponse, AUTO)

PB_BIND(penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value, penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value,
        AUTO)

PB_BIND(penumbra_cnidarium_v1_KeyValueRequest, penumbra_cnidarium_v1_KeyValueRequest, AUTO)

PB_BIND(penumbra_cnidarium_v1_KeyValueResponse, penumbra_cnidarium_v1_KeyValueResponse, AUTO)

PB_BIND(penumbra_cnidarium_v1_KeyValueResponse_Value, penumbra_cnidarium_v1_KeyValueResponse_Value, AUTO)

PB_BIND(penumbra_cnidarium_v1_PrefixValueRequest, penumbra_cnidarium_v1_PrefixValueRequest, AUTO)

PB_BIND(penumbra_cnidarium_v1_PrefixValueResponse, penumbra_cnidarium_v1_PrefixValueResponse, AUTO)

PB_BIND(penumbra_cnidarium_v1_WatchRequest, penumbra_cnidarium_v1_WatchRequest, AUTO)

PB_BIND(penumbra_cnidarium_v1_WatchResponse, penumbra_cnidarium_v1_WatchResponse, AUTO)

PB_BIND(penumbra_cnidarium_v1_WatchResponse_KeyValue, penumbra_cnidarium_v1_WatchResponse_KeyValue, AUTO)

PB_BIND(penumbra_cnidarium_v1_WatchResponse_NvKeyValue, penumbra_cnidarium_v1_WatchResponse_NvKeyValue, AUTO)
