/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PENUMBRA_CNIDARIUM_V1_PENUMBRA_CNIDARIUM_V1_CNIDARIUM_PB_H_INCLUDED
#define PB_PENUMBRA_CNIDARIUM_V1_PENUMBRA_CNIDARIUM_V1_CNIDARIUM_PB_H_INCLUDED
#include <pb.h>

#include "ibc/core/commitment/v1/commitment.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key {
    pb_callback_t inner;
} penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key;

/* Performs a key-value query against the nonverifiable storage,
 using a byte-encoded key. */
typedef struct _penumbra_cnidarium_v1_NonVerifiableKeyValueRequest {
    bool has_key;
    penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key key;
} penumbra_cnidarium_v1_NonVerifiableKeyValueRequest;

typedef struct _penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value {
    pb_callback_t value;
} penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value;

typedef struct _penumbra_cnidarium_v1_NonVerifiableKeyValueResponse {
    /* The value corresponding to the specified key, if it was found. */
    bool has_value;
    penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value value;
} penumbra_cnidarium_v1_NonVerifiableKeyValueResponse;

/* Performs a key-value query against the JMT, either by key or by key hash.

 Proofs are only supported by key. */
typedef struct _penumbra_cnidarium_v1_KeyValueRequest {
    /* If set, the key to fetch from storage. */
    pb_callback_t key;
    /* whether to return a proof */
    bool proof;
} penumbra_cnidarium_v1_KeyValueRequest;

typedef struct _penumbra_cnidarium_v1_KeyValueResponse_Value {
    pb_callback_t value;
} penumbra_cnidarium_v1_KeyValueResponse_Value;

typedef struct _penumbra_cnidarium_v1_KeyValueResponse {
    /* The value corresponding to the specified key, if it was found. */
    bool has_value;
    penumbra_cnidarium_v1_KeyValueResponse_Value value;
    /* A proof of existence or non-existence. */
    bool has_proof;
    ibc_core_commitment_v1_MerkleProof proof;
} penumbra_cnidarium_v1_KeyValueResponse;

/* Performs a prefixed key-value query, by string prefix. */
typedef struct _penumbra_cnidarium_v1_PrefixValueRequest {
    /* The prefix to fetch subkeys from storage. */
    pb_callback_t prefix;
} penumbra_cnidarium_v1_PrefixValueRequest;

typedef struct _penumbra_cnidarium_v1_PrefixValueResponse {
    pb_callback_t key;
    pb_callback_t value;
} penumbra_cnidarium_v1_PrefixValueResponse;

/* Requests a stream of new key-value pairs that have been committed to the state. */
typedef struct _penumbra_cnidarium_v1_WatchRequest {
    /* A regex for keys in the verifiable storage.

 Only key-value updates whose keys match this regex will be returned.
 Note that the empty string matches all keys.
 To exclude all keys, use the regex "$^", which matches no strings. */
    pb_callback_t key_regex;
    /* A regex for keys in the nonverifiable storage.

 Only key-value updates whose keys match this regex will be returned.
 Note that the empty string matches all keys.
 To exclude all keys, use the regex "$^", which matches no strings. */
    pb_callback_t nv_key_regex;
} penumbra_cnidarium_v1_WatchRequest;

/* Elements of the verifiable storage have string keys. */
typedef struct _penumbra_cnidarium_v1_WatchResponse_KeyValue {
    pb_callback_t key;
    pb_callback_t value;
    /* If set to true, the key-value pair was deleted.
 This allows distinguishing a deleted key-value pair from a key-value pair whose value is empty. */
    bool deleted;
} penumbra_cnidarium_v1_WatchResponse_KeyValue;

/* Elements of the nonverifiable storage have byte keys. */
typedef struct _penumbra_cnidarium_v1_WatchResponse_NvKeyValue {
    pb_callback_t key;
    pb_callback_t value;
    /* If set to true, the key-value pair was deleted.
 This allows distinguishing a deleted key-value pair from a key-value pair whose value is empty. */
    bool deleted;
} penumbra_cnidarium_v1_WatchResponse_NvKeyValue;

/* A key-value pair that has been committed to the state. */
typedef struct _penumbra_cnidarium_v1_WatchResponse {
    /* The state version the key-value pair was committed at. */
    uint64_t version;
    pb_size_t which_entry;
    union {
        penumbra_cnidarium_v1_WatchResponse_KeyValue kv;
        penumbra_cnidarium_v1_WatchResponse_NvKeyValue nv_kv;
    } entry;
} penumbra_cnidarium_v1_WatchResponse;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_init_default \
    { false, penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_init_default }
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_init_default \
    {                                                                       \
        { {NULL}, NULL }                                                    \
    }
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_init_default \
    { false, penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_init_default }
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_init_default \
    {                                                                          \
        { {NULL}, NULL }                                                       \
    }
#define penumbra_cnidarium_v1_KeyValueRequest_init_default \
    { {{NULL}, NULL}, 0 }
#define penumbra_cnidarium_v1_KeyValueResponse_init_default                      \
    {                                                                            \
        false, penumbra_cnidarium_v1_KeyValueResponse_Value_init_default, false, \
            ibc_core_commitment_v1_MerkleProof_init_default                      \
    }
#define penumbra_cnidarium_v1_KeyValueResponse_Value_init_default \
    {                                                             \
        { {NULL}, NULL }                                          \
    }
#define penumbra_cnidarium_v1_PrefixValueRequest_init_default \
    {                                                         \
        { {NULL}, NULL }                                      \
    }
#define penumbra_cnidarium_v1_PrefixValueResponse_init_default \
    {                                                          \
        {{NULL}, NULL}, { {NULL}, NULL }                       \
    }
#define penumbra_cnidarium_v1_WatchRequest_init_default \
    {                                                   \
        {{NULL}, NULL}, { {NULL}, NULL }                \
    }
#define penumbra_cnidarium_v1_WatchResponse_init_default                    \
    {                                                                       \
        0, 0, { penumbra_cnidarium_v1_WatchResponse_KeyValue_init_default } \
    }
#define penumbra_cnidarium_v1_WatchResponse_KeyValue_init_default \
    { {{NULL}, NULL}, {{NULL}, NULL}, 0 }
#define penumbra_cnidarium_v1_WatchResponse_NvKeyValue_init_default \
    { {{NULL}, NULL}, {{NULL}, NULL}, 0 }
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_init_zero \
    { false, penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_init_zero }
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_init_zero \
    {                                                                    \
        { {NULL}, NULL }                                                 \
    }
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_init_zero \
    { false, penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_init_zero }
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_init_zero \
    {                                                                       \
        { {NULL}, NULL }                                                    \
    }
#define penumbra_cnidarium_v1_KeyValueRequest_init_zero \
    { {{NULL}, NULL}, 0 }
#define penumbra_cnidarium_v1_KeyValueResponse_init_zero \
    { false, penumbra_cnidarium_v1_KeyValueResponse_Value_init_zero, false, ibc_core_commitment_v1_MerkleProof_init_zero }
#define penumbra_cnidarium_v1_KeyValueResponse_Value_init_zero \
    {                                                          \
        { {NULL}, NULL }                                       \
    }
#define penumbra_cnidarium_v1_PrefixValueRequest_init_zero \
    {                                                      \
        { {NULL}, NULL }                                   \
    }
#define penumbra_cnidarium_v1_PrefixValueResponse_init_zero \
    {                                                       \
        {{NULL}, NULL}, { {NULL}, NULL }                    \
    }
#define penumbra_cnidarium_v1_WatchRequest_init_zero \
    {                                                \
        {{NULL}, NULL}, { {NULL}, NULL }             \
    }
#define penumbra_cnidarium_v1_WatchResponse_init_zero                    \
    {                                                                    \
        0, 0, { penumbra_cnidarium_v1_WatchResponse_KeyValue_init_zero } \
    }
#define penumbra_cnidarium_v1_WatchResponse_KeyValue_init_zero \
    { {{NULL}, NULL}, {{NULL}, NULL}, 0 }
#define penumbra_cnidarium_v1_WatchResponse_NvKeyValue_init_zero \
    { {{NULL}, NULL}, {{NULL}, NULL}, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_inner_tag 1
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_key_tag 1
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_value_tag 1
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_value_tag 1
#define penumbra_cnidarium_v1_KeyValueRequest_key_tag 2
#define penumbra_cnidarium_v1_KeyValueRequest_proof_tag 3
#define penumbra_cnidarium_v1_KeyValueResponse_Value_value_tag 1
#define penumbra_cnidarium_v1_KeyValueResponse_value_tag 1
#define penumbra_cnidarium_v1_KeyValueResponse_proof_tag 2
#define penumbra_cnidarium_v1_PrefixValueRequest_prefix_tag 2
#define penumbra_cnidarium_v1_PrefixValueResponse_key_tag 1
#define penumbra_cnidarium_v1_PrefixValueResponse_value_tag 2
#define penumbra_cnidarium_v1_WatchRequest_key_regex_tag 1
#define penumbra_cnidarium_v1_WatchRequest_nv_key_regex_tag 2
#define penumbra_cnidarium_v1_WatchResponse_KeyValue_key_tag 1
#define penumbra_cnidarium_v1_WatchResponse_KeyValue_value_tag 2
#define penumbra_cnidarium_v1_WatchResponse_KeyValue_deleted_tag 3
#define penumbra_cnidarium_v1_WatchResponse_NvKeyValue_key_tag 1
#define penumbra_cnidarium_v1_WatchResponse_NvKeyValue_value_tag 2
#define penumbra_cnidarium_v1_WatchResponse_NvKeyValue_deleted_tag 3
#define penumbra_cnidarium_v1_WatchResponse_version_tag 1
#define penumbra_cnidarium_v1_WatchResponse_kv_tag 5
#define penumbra_cnidarium_v1_WatchResponse_nv_kv_tag 6

/* Struct field encoding specification for nanopb */
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, key, 1)
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_CALLBACK NULL
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_DEFAULT NULL
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_key_MSGTYPE penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key

#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, BYTES, inner, 1)
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_CALLBACK pb_default_field_callback
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_DEFAULT NULL

#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, value, 1)
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_CALLBACK NULL
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_DEFAULT NULL
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_value_MSGTYPE \
    penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value

#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, BYTES, value, 1)
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_CALLBACK pb_default_field_callback
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_DEFAULT NULL

#define penumbra_cnidarium_v1_KeyValueRequest_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, STRING, key, 2)                  \
    X(a, STATIC, SINGULAR, BOOL, proof, 3)
#define penumbra_cnidarium_v1_KeyValueRequest_CALLBACK pb_default_field_callback
#define penumbra_cnidarium_v1_KeyValueRequest_DEFAULT NULL

#define penumbra_cnidarium_v1_KeyValueResponse_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, value, 1)                  \
    X(a, STATIC, OPTIONAL, MESSAGE, proof, 2)
#define penumbra_cnidarium_v1_KeyValueResponse_CALLBACK NULL
#define penumbra_cnidarium_v1_KeyValueResponse_DEFAULT NULL
#define penumbra_cnidarium_v1_KeyValueResponse_value_MSGTYPE penumbra_cnidarium_v1_KeyValueResponse_Value
#define penumbra_cnidarium_v1_KeyValueResponse_proof_MSGTYPE ibc_core_commitment_v1_MerkleProof

#define penumbra_cnidarium_v1_KeyValueResponse_Value_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, BYTES, value, 1)
#define penumbra_cnidarium_v1_KeyValueResponse_Value_CALLBACK pb_default_field_callback
#define penumbra_cnidarium_v1_KeyValueResponse_Value_DEFAULT NULL

#define penumbra_cnidarium_v1_PrefixValueRequest_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, prefix, 2)
#define penumbra_cnidarium_v1_PrefixValueRequest_CALLBACK pb_default_field_callback
#define penumbra_cnidarium_v1_PrefixValueRequest_DEFAULT NULL

#define penumbra_cnidarium_v1_PrefixValueResponse_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, STRING, key, 1)                      \
    X(a, CALLBACK, SINGULAR, BYTES, value, 2)
#define penumbra_cnidarium_v1_PrefixValueResponse_CALLBACK pb_default_field_callback
#define penumbra_cnidarium_v1_PrefixValueResponse_DEFAULT NULL

#define penumbra_cnidarium_v1_WatchRequest_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, STRING, key_regex, 1)         \
    X(a, CALLBACK, SINGULAR, STRING, nv_key_regex, 2)
#define penumbra_cnidarium_v1_WatchRequest_CALLBACK pb_default_field_callback
#define penumbra_cnidarium_v1_WatchRequest_DEFAULT NULL

#define penumbra_cnidarium_v1_WatchResponse_FIELDLIST(X, a) \
    X(a, STATIC, SINGULAR, UINT64, version, 1)              \
    X(a, STATIC, ONEOF, MESSAGE, (entry, kv, entry.kv), 5)  \
    X(a, STATIC, ONEOF, MESSAGE, (entry, nv_kv, entry.nv_kv), 6)
#define penumbra_cnidarium_v1_WatchResponse_CALLBACK NULL
#define penumbra_cnidarium_v1_WatchResponse_DEFAULT NULL
#define penumbra_cnidarium_v1_WatchResponse_entry_kv_MSGTYPE penumbra_cnidarium_v1_WatchResponse_KeyValue
#define penumbra_cnidarium_v1_WatchResponse_entry_nv_kv_MSGTYPE penumbra_cnidarium_v1_WatchResponse_NvKeyValue

#define penumbra_cnidarium_v1_WatchResponse_KeyValue_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, STRING, key, 1)                         \
    X(a, CALLBACK, SINGULAR, BYTES, value, 2)                        \
    X(a, STATIC, SINGULAR, BOOL, deleted, 3)
#define penumbra_cnidarium_v1_WatchResponse_KeyValue_CALLBACK pb_default_field_callback
#define penumbra_cnidarium_v1_WatchResponse_KeyValue_DEFAULT NULL

#define penumbra_cnidarium_v1_WatchResponse_NvKeyValue_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, BYTES, key, 1)                            \
    X(a, CALLBACK, SINGULAR, BYTES, value, 2)                          \
    X(a, STATIC, SINGULAR, BOOL, deleted, 3)
#define penumbra_cnidarium_v1_WatchResponse_NvKeyValue_CALLBACK pb_default_field_callback
#define penumbra_cnidarium_v1_WatchResponse_NvKeyValue_DEFAULT NULL

extern const pb_msgdesc_t penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_KeyValueRequest_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_KeyValueResponse_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_KeyValueResponse_Value_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_PrefixValueRequest_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_PrefixValueResponse_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_WatchRequest_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_WatchResponse_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_WatchResponse_KeyValue_msg;
extern const pb_msgdesc_t penumbra_cnidarium_v1_WatchResponse_NvKeyValue_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_fields &penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_msg
#define penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_fields \
    &penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_msg
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_fields &penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_msg
#define penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_fields \
    &penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_msg
#define penumbra_cnidarium_v1_KeyValueRequest_fields &penumbra_cnidarium_v1_KeyValueRequest_msg
#define penumbra_cnidarium_v1_KeyValueResponse_fields &penumbra_cnidarium_v1_KeyValueResponse_msg
#define penumbra_cnidarium_v1_KeyValueResponse_Value_fields &penumbra_cnidarium_v1_KeyValueResponse_Value_msg
#define penumbra_cnidarium_v1_PrefixValueRequest_fields &penumbra_cnidarium_v1_PrefixValueRequest_msg
#define penumbra_cnidarium_v1_PrefixValueResponse_fields &penumbra_cnidarium_v1_PrefixValueResponse_msg
#define penumbra_cnidarium_v1_WatchRequest_fields &penumbra_cnidarium_v1_WatchRequest_msg
#define penumbra_cnidarium_v1_WatchResponse_fields &penumbra_cnidarium_v1_WatchResponse_msg
#define penumbra_cnidarium_v1_WatchResponse_KeyValue_fields &penumbra_cnidarium_v1_WatchResponse_KeyValue_msg
#define penumbra_cnidarium_v1_WatchResponse_NvKeyValue_fields &penumbra_cnidarium_v1_WatchResponse_NvKeyValue_msg

/* Maximum encoded size of messages (where known) */
/* penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_size depends on runtime parameters */
/* penumbra_cnidarium_v1_NonVerifiableKeyValueRequest_Key_size depends on runtime parameters */
/* penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_size depends on runtime parameters */
/* penumbra_cnidarium_v1_NonVerifiableKeyValueResponse_Value_size depends on runtime parameters */
/* penumbra_cnidarium_v1_KeyValueRequest_size depends on runtime parameters */
/* penumbra_cnidarium_v1_KeyValueResponse_size depends on runtime parameters */
/* penumbra_cnidarium_v1_KeyValueResponse_Value_size depends on runtime parameters */
/* penumbra_cnidarium_v1_PrefixValueRequest_size depends on runtime parameters */
/* penumbra_cnidarium_v1_PrefixValueResponse_size depends on runtime parameters */
/* penumbra_cnidarium_v1_WatchRequest_size depends on runtime parameters */
/* penumbra_cnidarium_v1_WatchResponse_size depends on runtime parameters */
/* penumbra_cnidarium_v1_WatchResponse_KeyValue_size depends on runtime parameters */
/* penumbra_cnidarium_v1_WatchResponse_NvKeyValue_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
