/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/slashing/v1beta1/genesis.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_slashing_v1beta1_GenesisState, cosmos_slashing_v1beta1_GenesisState, AUTO)

PB_BIND(cosmos_slashing_v1beta1_SigningInfo, cosmos_slashing_v1beta1_SigningInfo, AUTO)

PB_BIND(cosmos_slashing_v1beta1_ValidatorMissedBlocks, cosmos_slashing_v1beta1_ValidatorMissedBlocks, AUTO)

PB_BIND(cosmos_slashing_v1beta1_MissedBlock, cosmos_slashing_v1beta1_MissedBlock, AUTO)
