/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/slashing/v1beta1/query.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_slashing_v1beta1_QueryParamsRequest, cosmos_slashing_v1beta1_QueryParamsRequest, AUTO)

PB_BIND(cosmos_slashing_v1beta1_QueryParamsResponse, cosmos_slashing_v1beta1_QueryParamsResponse, AUTO)

PB_BIND(cosmos_slashing_v1beta1_QuerySigningInfoRequest, cosmos_slashing_v1beta1_QuerySigningInfoRequest, AUTO)

PB_BIND(cosmos_slashing_v1beta1_QuerySigningInfoResponse, cosmos_slashing_v1beta1_QuerySigningInfoResponse, AUTO)

PB_BIND(cosmos_slashing_v1beta1_QuerySigningInfosRequest, cosmos_slashing_v1beta1_QuerySigningInfosRequest, AUTO)

PB_BIND(cosmos_slashing_v1beta1_QuerySigningInfosResponse, cosmos_slashing_v1beta1_QuerySigningInfosResponse, AUTO)
