/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/group/v1/types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_group_v1_Member, cosmos_group_v1_Member, AUTO)

PB_BIND(cosmos_group_v1_MemberRequest, cosmos_group_v1_MemberRequest, AUTO)

PB_BIND(cosmos_group_v1_ThresholdDecisionPolicy, cosmos_group_v1_ThresholdDecisionPolicy, AUTO)

PB_BIND(cosmos_group_v1_PercentageDecisionPolicy, cosmos_group_v1_PercentageDecisionPolicy, AUTO)

PB_BIND(cosmos_group_v1_DecisionPolicyWindows, cosmos_group_v1_DecisionPolicyWindows, AUTO)

PB_BIND(cosmos_group_v1_GroupInfo, cosmos_group_v1_GroupInfo, AUTO)

PB_BIND(cosmos_group_v1_GroupMember, cosmos_group_v1_GroupMember, AUTO)

PB_BIND(cosmos_group_v1_GroupPolicyInfo, cosmos_group_v1_GroupPolicyInfo, AUTO)

PB_BIND(cosmos_group_v1_Proposal, cosmos_group_v1_Proposal, AUTO)

PB_BIND(cosmos_group_v1_TallyResult, cosmos_group_v1_TallyResult, AUTO)

PB_BIND(cosmos_group_v1_Vote, cosmos_group_v1_Vote, AUTO)
