/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/tx/v1beta1/service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_tx_v1beta1_GetTxsEventRequest, cosmos_tx_v1beta1_GetTxsEventRequest, AUTO)

PB_BIND(cosmos_tx_v1beta1_GetTxsEventResponse, cosmos_tx_v1beta1_GetTxsEventResponse, AUTO)

PB_BIND(cosmos_tx_v1beta1_BroadcastTxRequest, cosmos_tx_v1beta1_BroadcastTxRequest, AUTO)

PB_BIND(cosmos_tx_v1beta1_BroadcastTxResponse, cosmos_tx_v1beta1_BroadcastTxResponse, AUTO)

PB_BIND(cosmos_tx_v1beta1_SimulateRequest, cosmos_tx_v1beta1_SimulateRequest, 2)

PB_BIND(cosmos_tx_v1beta1_SimulateResponse, cosmos_tx_v1beta1_SimulateResponse, AUTO)

PB_BIND(cosmos_tx_v1beta1_GetTxRequest, cosmos_tx_v1beta1_GetTxRequest, AUTO)

PB_BIND(cosmos_tx_v1beta1_GetTxResponse, cosmos_tx_v1beta1_GetTxResponse, 2)

PB_BIND(cosmos_tx_v1beta1_GetBlockWithTxsRequest, cosmos_tx_v1beta1_GetBlockWithTxsRequest, AUTO)

PB_BIND(cosmos_tx_v1beta1_GetBlockWithTxsResponse, cosmos_tx_v1beta1_GetBlockWithTxsResponse, 2)

PB_BIND(cosmos_tx_v1beta1_TxDecodeRequest, cosmos_tx_v1beta1_TxDecodeRequest, AUTO)

PB_BIND(cosmos_tx_v1beta1_TxDecodeResponse, cosmos_tx_v1beta1_TxDecodeResponse, 2)

PB_BIND(cosmos_tx_v1beta1_TxEncodeRequest, cosmos_tx_v1beta1_TxEncodeRequest, 2)

PB_BIND(cosmos_tx_v1beta1_TxEncodeResponse, cosmos_tx_v1beta1_TxEncodeResponse, AUTO)

PB_BIND(cosmos_tx_v1beta1_TxEncodeAminoRequest, cosmos_tx_v1beta1_TxEncodeAminoRequest, AUTO)

PB_BIND(cosmos_tx_v1beta1_TxEncodeAminoResponse, cosmos_tx_v1beta1_TxEncodeAminoResponse, AUTO)

PB_BIND(cosmos_tx_v1beta1_TxDecodeAminoRequest, cosmos_tx_v1beta1_TxDecodeAminoRequest, AUTO)

PB_BIND(cosmos_tx_v1beta1_TxDecodeAminoResponse, cosmos_tx_v1beta1_TxDecodeAminoResponse, AUTO)
