/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COSMOS_EVIDENCE_V1BETA1_COSMOS_EVIDENCE_V1BETA1_QUERY_PB_H_INCLUDED
#define PB_COSMOS_EVIDENCE_V1BETA1_COSMOS_EVIDENCE_V1BETA1_QUERY_PB_H_INCLUDED
#include <pb.h>

#include "cosmos/base/query/v1beta1/pagination.pb.h"
#include "google/api/annotations.pb.h"
#include "google/protobuf/any.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* QueryEvidenceRequest is the request type for the Query/Evidence RPC method. */
typedef struct _cosmos_evidence_v1beta1_QueryEvidenceRequest {
    /* evidence_hash defines the hash of the requested evidence.
 Deprecated: Use hash, a HEX encoded string, instead. */
    pb_callback_t evidence_hash;
    /* hash defines the evidence hash of the requested evidence.

 Since: cosmos-sdk 0.47 */
    pb_callback_t hash;
} cosmos_evidence_v1beta1_QueryEvidenceRequest;

/* QueryEvidenceResponse is the response type for the Query/Evidence RPC method. */
typedef struct _cosmos_evidence_v1beta1_QueryEvidenceResponse {
    /* evidence returns the requested evidence. */
    bool has_evidence;
    google_protobuf_Any evidence;
} cosmos_evidence_v1beta1_QueryEvidenceResponse;

/* QueryEvidenceRequest is the request type for the Query/AllEvidence RPC
 method. */
typedef struct _cosmos_evidence_v1beta1_QueryAllEvidenceRequest {
    /* pagination defines an optional pagination for the request. */
    bool has_pagination;
    cosmos_base_query_v1beta1_PageRequest pagination;
} cosmos_evidence_v1beta1_QueryAllEvidenceRequest;

/* QueryAllEvidenceResponse is the response type for the Query/AllEvidence RPC
 method. */
typedef struct _cosmos_evidence_v1beta1_QueryAllEvidenceResponse {
    /* evidence returns all evidences. */
    pb_callback_t evidence;
    /* pagination defines the pagination in the response. */
    bool has_pagination;
    cosmos_base_query_v1beta1_PageResponse pagination;
} cosmos_evidence_v1beta1_QueryAllEvidenceResponse;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_evidence_v1beta1_QueryEvidenceRequest_init_default \
    {                                                             \
        {{NULL}, NULL}, { {NULL}, NULL }                          \
    }
#define cosmos_evidence_v1beta1_QueryEvidenceResponse_init_default \
    { false, google_protobuf_Any_init_default }
#define cosmos_evidence_v1beta1_QueryAllEvidenceRequest_init_default \
    { false, cosmos_base_query_v1beta1_PageRequest_init_default }
#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_init_default \
    { {{NULL}, NULL}, false, cosmos_base_query_v1beta1_PageResponse_init_default }
#define cosmos_evidence_v1beta1_QueryEvidenceRequest_init_zero \
    {                                                          \
        {{NULL}, NULL}, { {NULL}, NULL }                       \
    }
#define cosmos_evidence_v1beta1_QueryEvidenceResponse_init_zero \
    { false, google_protobuf_Any_init_zero }
#define cosmos_evidence_v1beta1_QueryAllEvidenceRequest_init_zero \
    { false, cosmos_base_query_v1beta1_PageRequest_init_zero }
#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_init_zero \
    { {{NULL}, NULL}, false, cosmos_base_query_v1beta1_PageResponse_init_zero }

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_evidence_v1beta1_QueryEvidenceRequest_evidence_hash_tag 1
#define cosmos_evidence_v1beta1_QueryEvidenceRequest_hash_tag 2
#define cosmos_evidence_v1beta1_QueryEvidenceResponse_evidence_tag 1
#define cosmos_evidence_v1beta1_QueryAllEvidenceRequest_pagination_tag 1
#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_evidence_tag 1
#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_pagination_tag 2

/* Struct field encoding specification for nanopb */
#define cosmos_evidence_v1beta1_QueryEvidenceRequest_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, BYTES, evidence_hash, 1)                \
    X(a, CALLBACK, SINGULAR, STRING, hash, 2)
#define cosmos_evidence_v1beta1_QueryEvidenceRequest_CALLBACK pb_default_field_callback
#define cosmos_evidence_v1beta1_QueryEvidenceRequest_DEFAULT NULL

#define cosmos_evidence_v1beta1_QueryEvidenceResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, evidence, 1)
#define cosmos_evidence_v1beta1_QueryEvidenceResponse_CALLBACK NULL
#define cosmos_evidence_v1beta1_QueryEvidenceResponse_DEFAULT NULL
#define cosmos_evidence_v1beta1_QueryEvidenceResponse_evidence_MSGTYPE google_protobuf_Any

#define cosmos_evidence_v1beta1_QueryAllEvidenceRequest_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, pagination, 1)
#define cosmos_evidence_v1beta1_QueryAllEvidenceRequest_CALLBACK NULL
#define cosmos_evidence_v1beta1_QueryAllEvidenceRequest_DEFAULT NULL
#define cosmos_evidence_v1beta1_QueryAllEvidenceRequest_pagination_MSGTYPE cosmos_base_query_v1beta1_PageRequest

#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_FIELDLIST(X, a) \
    X(a, CALLBACK, REPEATED, MESSAGE, evidence, 1)                       \
    X(a, STATIC, OPTIONAL, MESSAGE, pagination, 2)
#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_CALLBACK pb_default_field_callback
#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_DEFAULT NULL
#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_evidence_MSGTYPE google_protobuf_Any
#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_pagination_MSGTYPE cosmos_base_query_v1beta1_PageResponse

extern const pb_msgdesc_t cosmos_evidence_v1beta1_QueryEvidenceRequest_msg;
extern const pb_msgdesc_t cosmos_evidence_v1beta1_QueryEvidenceResponse_msg;
extern const pb_msgdesc_t cosmos_evidence_v1beta1_QueryAllEvidenceRequest_msg;
extern const pb_msgdesc_t cosmos_evidence_v1beta1_QueryAllEvidenceResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_evidence_v1beta1_QueryEvidenceRequest_fields &cosmos_evidence_v1beta1_QueryEvidenceRequest_msg
#define cosmos_evidence_v1beta1_QueryEvidenceResponse_fields &cosmos_evidence_v1beta1_QueryEvidenceResponse_msg
#define cosmos_evidence_v1beta1_QueryAllEvidenceRequest_fields &cosmos_evidence_v1beta1_QueryAllEvidenceRequest_msg
#define cosmos_evidence_v1beta1_QueryAllEvidenceResponse_fields &cosmos_evidence_v1beta1_QueryAllEvidenceResponse_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_evidence_v1beta1_QueryEvidenceRequest_size depends on runtime parameters */
/* cosmos_evidence_v1beta1_QueryAllEvidenceResponse_size depends on runtime parameters */
#if defined(google_protobuf_Any_size)
#define COSMOS_EVIDENCE_V1BETA1_COSMOS_EVIDENCE_V1BETA1_QUERY_PB_H_MAX_SIZE \
    cosmos_evidence_v1beta1_QueryEvidenceResponse_size
#define cosmos_evidence_v1beta1_QueryEvidenceResponse_size (6 + google_protobuf_Any_size)
#endif
#if defined(cosmos_base_query_v1beta1_PageRequest_size)
#define cosmos_evidence_v1beta1_QueryAllEvidenceRequest_size (6 + cosmos_base_query_v1beta1_PageRequest_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
