/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PENUMBRA_CORE_COMPONENT_FUNDING_V1_PENUMBRA_CORE_COMPONENT_FUNDING_V1_FUNDING_PB_H_INCLUDED
#define PB_PENUMBRA_CORE_COMPONENT_FUNDING_V1_PENUMBRA_CORE_COMPONENT_FUNDING_V1_FUNDING_PB_H_INCLUDED
#include <pb.h>

#include "penumbra/core/num/v1/num.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Funding component configuration data. */
typedef struct _penumbra_core_component_funding_v1_FundingParameters {
    char dummy_field;
} penumbra_core_component_funding_v1_FundingParameters;

/* Genesis data for the funding component. */
typedef struct _penumbra_core_component_funding_v1_GenesisContent {
    bool has_funding_params;
    penumbra_core_component_funding_v1_FundingParameters funding_params;
} penumbra_core_component_funding_v1_GenesisContent;

/* Indicates that a funding stream reward was paid. */
typedef struct _penumbra_core_component_funding_v1_EventFundingStreamReward {
    /* The recipient of the funding stream reward.
 This is a string value for future extensibility.
 Currently it will be either "community-pool"
 or an address. */
    pb_callback_t recipient;
    /* The epoch for which the reward was paid. */
    uint64_t epoch_index;
    /* The amount of the reward, in staking tokens. */
    bool has_reward_amount;
    penumbra_core_num_v1_Amount reward_amount;
} penumbra_core_component_funding_v1_EventFundingStreamReward;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define penumbra_core_component_funding_v1_FundingParameters_init_default \
    { 0 }
#define penumbra_core_component_funding_v1_GenesisContent_init_default \
    { false, penumbra_core_component_funding_v1_FundingParameters_init_default }
#define penumbra_core_component_funding_v1_EventFundingStreamReward_init_default \
    { {{NULL}, NULL}, 0, false, penumbra_core_num_v1_Amount_init_default }
#define penumbra_core_component_funding_v1_FundingParameters_init_zero \
    { 0 }
#define penumbra_core_component_funding_v1_GenesisContent_init_zero \
    { false, penumbra_core_component_funding_v1_FundingParameters_init_zero }
#define penumbra_core_component_funding_v1_EventFundingStreamReward_init_zero \
    { {{NULL}, NULL}, 0, false, penumbra_core_num_v1_Amount_init_zero }

/* Field tags (for use in manual encoding/decoding) */
#define penumbra_core_component_funding_v1_GenesisContent_funding_params_tag 1
#define penumbra_core_component_funding_v1_EventFundingStreamReward_recipient_tag 1
#define penumbra_core_component_funding_v1_EventFundingStreamReward_epoch_index_tag 2
#define penumbra_core_component_funding_v1_EventFundingStreamReward_reward_amount_tag 3

/* Struct field encoding specification for nanopb */
#define penumbra_core_component_funding_v1_FundingParameters_FIELDLIST(X, a)

#define penumbra_core_component_funding_v1_FundingParameters_CALLBACK NULL
#define penumbra_core_component_funding_v1_FundingParameters_DEFAULT NULL

#define penumbra_core_component_funding_v1_GenesisContent_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, funding_params, 1)
#define penumbra_core_component_funding_v1_GenesisContent_CALLBACK NULL
#define penumbra_core_component_funding_v1_GenesisContent_DEFAULT NULL
#define penumbra_core_component_funding_v1_GenesisContent_funding_params_MSGTYPE \
    penumbra_core_component_funding_v1_FundingParameters

#define penumbra_core_component_funding_v1_EventFundingStreamReward_FIELDLIST(X, a) \
    X(a, CALLBACK, SINGULAR, STRING, recipient, 1)                                  \
    X(a, STATIC, SINGULAR, UINT64, epoch_index, 2)                                  \
    X(a, STATIC, OPTIONAL, MESSAGE, reward_amount, 3)
#define penumbra_core_component_funding_v1_EventFundingStreamReward_CALLBACK pb_default_field_callback
#define penumbra_core_component_funding_v1_EventFundingStreamReward_DEFAULT NULL
#define penumbra_core_component_funding_v1_EventFundingStreamReward_reward_amount_MSGTYPE penumbra_core_num_v1_Amount

extern const pb_msgdesc_t penumbra_core_component_funding_v1_FundingParameters_msg;
extern const pb_msgdesc_t penumbra_core_component_funding_v1_GenesisContent_msg;
extern const pb_msgdesc_t penumbra_core_component_funding_v1_EventFundingStreamReward_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define penumbra_core_component_funding_v1_FundingParameters_fields &penumbra_core_component_funding_v1_FundingParameters_msg
#define penumbra_core_component_funding_v1_GenesisContent_fields &penumbra_core_component_funding_v1_GenesisContent_msg
#define penumbra_core_component_funding_v1_EventFundingStreamReward_fields \
    &penumbra_core_component_funding_v1_EventFundingStreamReward_msg

/* Maximum encoded size of messages (where known) */
/* penumbra_core_component_funding_v1_EventFundingStreamReward_size depends on runtime parameters */
#define PENUMBRA_CORE_COMPONENT_FUNDING_V1_PENUMBRA_CORE_COMPONENT_FUNDING_V1_FUNDING_PB_H_MAX_SIZE \
    penumbra_core_component_funding_v1_GenesisContent_size
#define penumbra_core_component_funding_v1_FundingParameters_size 0
#define penumbra_core_component_funding_v1_GenesisContent_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
