/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/autocli/v1/options.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_autocli_v1_ModuleOptions, cosmos_autocli_v1_ModuleOptions, AUTO)

PB_BIND(cosmos_autocli_v1_ServiceCommandDescriptor, cosmos_autocli_v1_ServiceCommandDescriptor, AUTO)

PB_BIND(cosmos_autocli_v1_ServiceCommandDescriptor_SubCommandsEntry,
        cosmos_autocli_v1_ServiceCommandDescriptor_SubCommandsEntry, AUTO)

PB_BIND(cosmos_autocli_v1_RpcCommandOptions, cosmos_autocli_v1_RpcCommandOptions, AUTO)

PB_BIND(cosmos_autocli_v1_RpcCommandOptions_FlagOptionsEntry, cosmos_autocli_v1_RpcCommandOptions_FlagOptionsEntry, AUTO)

PB_BIND(cosmos_autocli_v1_FlagOptions, cosmos_autocli_v1_FlagOptions, AUTO)

PB_BIND(cosmos_autocli_v1_PositionalArgDescriptor, cosmos_autocli_v1_PositionalArgDescriptor, AUTO)
