/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/autocli/v1/query.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_autocli_v1_AppOptionsRequest, cosmos_autocli_v1_AppOptionsRequest, AUTO)

PB_BIND(cosmos_autocli_v1_AppOptionsResponse, cosmos_autocli_v1_AppOptionsResponse, AUTO)

PB_BIND(cosmos_autocli_v1_AppOptionsResponse_ModuleOptionsEntry, cosmos_autocli_v1_AppOptionsResponse_ModuleOptionsEntry,
        AUTO)
