/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PENUMBRA_CORE_COMPONENT_AUCTION_V1_PENUMBRA_CORE_COMPONENT_AUCTION_V1_AUCTION_PB_H_INCLUDED
#define PB_PENUMBRA_CORE_COMPONENT_AUCTION_V1_PENUMBRA_CORE_COMPONENT_AUCTION_V1_AUCTION_PB_H_INCLUDED
#include <pb.h>

#include "google/protobuf/any.pb.h"
#include "penumbra/core/asset/v1/asset.pb.h"
#include "penumbra/core/component/dex/v1/dex.pb.h"
#include "penumbra/core/num/v1/num.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* The reason the auction ended. */
typedef enum _penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason {
    penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_REASON_UNSPECIFIED = 0,
    /* The auction ended due to reaching its terminal height. */
    penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_REASON_EXPIRED = 1,
    /* The auction ran out of reserves. */
    penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_REASON_FILLED = 2,
    /* The auction ended was terminated by the initiator. */
    penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_REASON_CLOSED_BY_OWNER = 3
} penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason;

/* Struct definitions */
/* The configuration parameters for the auction component. */
typedef struct _penumbra_core_component_auction_v1_AuctionParameters {
    char dummy_field;
} penumbra_core_component_auction_v1_AuctionParameters;

/* Genesis data for the auction component. */
typedef struct _penumbra_core_component_auction_v1_GenesisContent {
    /* The configuration parameters for the auction component at genesis. */
    bool has_params;
    penumbra_core_component_auction_v1_AuctionParameters params;
} penumbra_core_component_auction_v1_GenesisContent;

typedef struct _penumbra_core_component_auction_v1_AuctionStateByIdResponse {
    /* If present, the state of the auction. If not present, no such auction is known. */
    bool has_auction;
    google_protobuf_Any auction;
    /* The state of any DEX positions relevant to the returned auction.

 Could be empty, depending on the auction state. */
    pb_callback_t positions;
} penumbra_core_component_auction_v1_AuctionStateByIdResponse;

typedef struct _penumbra_core_component_auction_v1_AuctionStateByIdsRequest {
    /* The auction IDs to request. Only known IDs will be returned in the response. */
    pb_callback_t id;
} penumbra_core_component_auction_v1_AuctionStateByIdsRequest;

/* A unique identifier for an auction, obtained from hashing a domain separator
 along with the immutable part of an auction description. */
typedef struct _penumbra_core_component_auction_v1_AuctionId {
    pb_callback_t inner;
} penumbra_core_component_auction_v1_AuctionId;

typedef struct _penumbra_core_component_auction_v1_AuctionStateByIdRequest {
    bool has_id;
    penumbra_core_component_auction_v1_AuctionId id;
} penumbra_core_component_auction_v1_AuctionStateByIdRequest;

/* A bearer NFT tracking ownership of an auction and its proceeds. */
typedef struct _penumbra_core_component_auction_v1_AuctionNft {
    bool has_id;
    penumbra_core_component_auction_v1_AuctionId id;
    uint64_t seq;
} penumbra_core_component_auction_v1_AuctionNft;

/* Describes a Dutch auction using programmatic liquidity on the DEX. */
typedef struct _penumbra_core_component_auction_v1_DutchAuctionDescription {
    /* The value the seller wishes to auction. */
    bool has_input;
    penumbra_core_asset_v1_Value input;
    /* The asset ID of the target asset the seller wishes to acquire. */
    bool has_output_id;
    penumbra_core_asset_v1_AssetId output_id;
    /* The maximum output the seller can receive.

 This implicitly defines the starting price for the auction. */
    bool has_max_output;
    penumbra_core_num_v1_Amount max_output;
    /* The minimum output the seller is willing to receive.

 This implicitly defines the ending price for the auction. */
    bool has_min_output;
    penumbra_core_num_v1_Amount min_output;
    /* The block height at which the auction begins.

 This allows the seller to schedule an auction at a future time. */
    uint64_t start_height;
    /* The block height at which the auction ends.

 Together with `start_height`, `max_output`, and `min_output`,
 this implicitly defines the speed of the auction. */
    uint64_t end_height;
    /* The number of discrete price steps to use for the auction.

 `end_height - start_height` must be a multiple of `step_count`. */
    uint64_t step_count;
    /* A random nonce used to allow identical auctions to have
 distinct auction IDs. */
    pb_callback_t nonce;
} penumbra_core_component_auction_v1_DutchAuctionDescription;

typedef struct _penumbra_core_component_auction_v1_DutchAuctionState {
    /* The sequence number of the auction state.

 Dutch auctions move from:
 0 (opened) => 1 (closed) => n (withdrawn) */
    uint64_t seq;
    /* If present, the current position controlled by this auction. */
    bool has_current_position;
    penumbra_core_component_dex_v1_PositionId current_position;
    /* If present, the next trigger height to step down the price. */
    uint64_t next_trigger;
    /* The amount of the input asset directly owned by the auction.

 The auction may also own the input asset indirectly,
 via the reserves of `current_position` if it exists. */
    bool has_input_reserves;
    penumbra_core_num_v1_Amount input_reserves;
    /* The amount of the output asset directly owned by the auction.

 The auction may also own the output asset indirectly,
 via the reserves of `current_position` if it exists. */
    bool has_output_reserves;
    penumbra_core_num_v1_Amount output_reserves;
} penumbra_core_component_auction_v1_DutchAuctionState;

typedef struct _penumbra_core_component_auction_v1_AuctionStateByIdsResponse {
    /* The auction ID of the returned auction. */
    bool has_id;
    penumbra_core_component_auction_v1_AuctionId id;
    /* The state of the returned auction. */
    bool has_auction;
    penumbra_core_component_auction_v1_DutchAuctionState auction;
    /* The state of any DEX positions relevant to the returned auction.

 Could be empty, depending on the auction state. */
    pb_callback_t positions;
} penumbra_core_component_auction_v1_AuctionStateByIdsResponse;

typedef struct _penumbra_core_component_auction_v1_DutchAuction {
    /* The immutable data describing the auction and its auction ID. */
    bool has_description;
    penumbra_core_component_auction_v1_DutchAuctionDescription description;
    /* The mutable data describing the auction's execution. */
    bool has_state;
    penumbra_core_component_auction_v1_DutchAuctionState state;
} penumbra_core_component_auction_v1_DutchAuction;

/* Initiates a Dutch auction using protocol-controlled liquidity. */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionSchedule {
    bool has_description;
    penumbra_core_component_auction_v1_DutchAuctionDescription description;
} penumbra_core_component_auction_v1_ActionDutchAuctionSchedule;

/* Terminate the auction associated with the specified `auction_id` */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionEnd {
    /* The auction to end. */
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
} penumbra_core_component_auction_v1_ActionDutchAuctionEnd;

/* Withdraw funds from the ended auction associated with the specified `auction_id` */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw {
    /* The auction to withdraw funds from. */
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    /* The sequence number of the withdrawal. */
    uint64_t seq;
    /* A transparent (zero blinding factor) commitment to the
 auction's final reserves.

 The chain will check this commitment by recomputing it
 with the on-chain state. */
    bool has_reserves_commitment;
    penumbra_core_asset_v1_BalanceCommitment reserves_commitment;
} penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw;

/* A plan to a `ActionDutchAuctionWithdraw` which contains both private and public data. */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan {
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    uint64_t seq;
    bool has_reserves_input;
    penumbra_core_asset_v1_Value reserves_input;
    bool has_reserves_output;
    penumbra_core_asset_v1_Value reserves_output;
} penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan;

/* An `ActionDutchAuctionSchedule` augmented with additional metadata. */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView {
    bool has_action;
    penumbra_core_component_auction_v1_ActionDutchAuctionSchedule action;
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    bool has_input_metadata;
    penumbra_core_asset_v1_Metadata input_metadata;
    bool has_output_metadata;
    penumbra_core_asset_v1_Metadata output_metadata;
} penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView;

/* An `ActionDutchAuctionWithdraw` augmented with additional metadata. */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView {
    bool has_action;
    penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw action;
    /* A sequence of values that sum together to the provided
 reserves commitment. */
    pb_callback_t reserves;
} penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView;

typedef struct _penumbra_core_component_auction_v1_EventDutchAuctionScheduled {
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    bool has_description;
    penumbra_core_component_auction_v1_DutchAuctionDescription description;
} penumbra_core_component_auction_v1_EventDutchAuctionScheduled;

typedef struct _penumbra_core_component_auction_v1_EventDutchAuctionUpdated {
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    bool has_state;
    penumbra_core_component_auction_v1_DutchAuctionState state;
} penumbra_core_component_auction_v1_EventDutchAuctionUpdated;

typedef struct _penumbra_core_component_auction_v1_EventDutchAuctionEnded {
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    bool has_state;
    penumbra_core_component_auction_v1_DutchAuctionState state;
    penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason reason;
} penumbra_core_component_auction_v1_EventDutchAuctionEnded;

typedef struct _penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn {
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    bool has_state;
    penumbra_core_component_auction_v1_DutchAuctionState state;
} penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn;

/* A message emitted when value flows *into* the auction component. */
typedef struct _penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit {
    /* The asset ID being deposited into the Auction component. */
    bool has_asset_id;
    penumbra_core_asset_v1_AssetId asset_id;
    /* The previous balance of the asset in the Auction component. */
    bool has_previous_balance;
    penumbra_core_num_v1_Amount previous_balance;
    /* The new balance of the asset in the Auction component. */
    bool has_new_balance;
    penumbra_core_num_v1_Amount new_balance;
} penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit;

/* A message emitted when value flows *out* of the auction component. */
typedef struct _penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit {
    /* The asset ID being deposited into the Auction component. */
    bool has_asset_id;
    penumbra_core_asset_v1_AssetId asset_id;
    /* The previous balance of the asset in the Auction component. */
    bool has_previous_balance;
    penumbra_core_num_v1_Amount previous_balance;
    /* The new balance of the asset in the Auction component. */
    bool has_new_balance;
    penumbra_core_num_v1_Amount new_balance;
} penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_MIN \
    penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_REASON_UNSPECIFIED
#define _penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_MAX \
    penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_REASON_CLOSED_BY_OWNER
#define _penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_ARRAYSIZE                                                                               \
    ((penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason)(penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_REASON_CLOSED_BY_OWNER + \
                                                                        1))

#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_reason_ENUMTYPE \
    penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason

/* Initializer values for message structs */
#define penumbra_core_component_auction_v1_AuctionParameters_init_default {0}
#define penumbra_core_component_auction_v1_GenesisContent_init_default \
    {false, penumbra_core_component_auction_v1_AuctionParameters_init_default}
#define penumbra_core_component_auction_v1_AuctionStateByIdRequest_init_default \
    {false, penumbra_core_component_auction_v1_AuctionId_init_default}
#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_init_default \
    {                                                                            \
        false, google_protobuf_Any_init_default, { {NULL}, NULL }                \
    }
#define penumbra_core_component_auction_v1_AuctionStateByIdsRequest_init_default \
    {                                                                            \
        {                                                                        \
            {NULL}, NULL                                                         \
        }                                                                        \
    }
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_init_default \
    {                                                                             \
        false, penumbra_core_component_auction_v1_AuctionId_init_default, false,  \
            penumbra_core_component_auction_v1_DutchAuctionState_init_default, {  \
            {NULL}, NULL                                                          \
        }                                                                         \
    }
#define penumbra_core_component_auction_v1_AuctionId_init_default \
    {                                                             \
        {                                                         \
            {NULL}, NULL                                          \
        }                                                         \
    }
#define penumbra_core_component_auction_v1_AuctionNft_init_default \
    {false, penumbra_core_component_auction_v1_AuctionId_init_default, 0}
#define penumbra_core_component_auction_v1_DutchAuctionDescription_init_default                                      \
    {                                                                                                                \
        false, penumbra_core_asset_v1_Value_init_default, false, penumbra_core_asset_v1_AssetId_init_default, false, \
            penumbra_core_num_v1_Amount_init_default, false, penumbra_core_num_v1_Amount_init_default, 0, 0, 0, {    \
            {NULL}, NULL                                                                                             \
        }                                                                                                            \
    }
#define penumbra_core_component_auction_v1_DutchAuctionState_init_default \
    {0,                                                                   \
     false,                                                               \
     penumbra_core_component_dex_v1_PositionId_init_default,              \
     0,                                                                   \
     false,                                                               \
     penumbra_core_num_v1_Amount_init_default,                            \
     false,                                                               \
     penumbra_core_num_v1_Amount_init_default}
#define penumbra_core_component_auction_v1_DutchAuction_init_default                        \
    {false, penumbra_core_component_auction_v1_DutchAuctionDescription_init_default, false, \
     penumbra_core_component_auction_v1_DutchAuctionState_init_default}
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_init_default \
    {false, penumbra_core_component_auction_v1_DutchAuctionDescription_init_default}
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_init_default \
    {false, penumbra_core_component_auction_v1_AuctionId_init_default}
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_init_default \
    {false, penumbra_core_component_auction_v1_AuctionId_init_default, 0, false,   \
     penumbra_core_asset_v1_BalanceCommitment_init_default}
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_init_default \
    {false,                                                                            \
     penumbra_core_component_auction_v1_AuctionId_init_default,                        \
     0,                                                                                \
     false,                                                                            \
     penumbra_core_asset_v1_Value_init_default,                                        \
     false,                                                                            \
     penumbra_core_asset_v1_Value_init_default}
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_init_default  \
    {false, penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_init_default, \
     false, penumbra_core_component_auction_v1_AuctionId_init_default,                  \
     false, penumbra_core_asset_v1_Metadata_init_default,                               \
     false, penumbra_core_asset_v1_Metadata_init_default}
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_init_default                      \
    {                                                                                                       \
        false, penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_init_default, { {NULL}, NULL } \
    }
#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_init_default \
    {false, penumbra_core_component_auction_v1_AuctionId_init_default, false,      \
     penumbra_core_component_auction_v1_DutchAuctionDescription_init_default}
#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_init_default \
    {false, penumbra_core_component_auction_v1_AuctionId_init_default, false,    \
     penumbra_core_component_auction_v1_DutchAuctionState_init_default}
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_init_default \
    {false, penumbra_core_component_auction_v1_AuctionId_init_default, false,  \
     penumbra_core_component_auction_v1_DutchAuctionState_init_default,        \
     _penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_MIN}
#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_init_default \
    {false, penumbra_core_component_auction_v1_AuctionId_init_default, false,      \
     penumbra_core_component_auction_v1_DutchAuctionState_init_default}
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_init_default                    \
    {false, penumbra_core_asset_v1_AssetId_init_default, false, penumbra_core_num_v1_Amount_init_default, \
     false, penumbra_core_num_v1_Amount_init_default}
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_init_default                     \
    {false, penumbra_core_asset_v1_AssetId_init_default, false, penumbra_core_num_v1_Amount_init_default, \
     false, penumbra_core_num_v1_Amount_init_default}
#define penumbra_core_component_auction_v1_AuctionParameters_init_zero {0}
#define penumbra_core_component_auction_v1_GenesisContent_init_zero \
    {false, penumbra_core_component_auction_v1_AuctionParameters_init_zero}
#define penumbra_core_component_auction_v1_AuctionStateByIdRequest_init_zero \
    {false, penumbra_core_component_auction_v1_AuctionId_init_zero}
#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_init_zero \
    {                                                                         \
        false, google_protobuf_Any_init_zero, { {NULL}, NULL }                \
    }
#define penumbra_core_component_auction_v1_AuctionStateByIdsRequest_init_zero \
    {                                                                         \
        {                                                                     \
            {NULL}, NULL                                                      \
        }                                                                     \
    }
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_init_zero \
    {                                                                          \
        false, penumbra_core_component_auction_v1_AuctionId_init_zero, false,  \
            penumbra_core_component_auction_v1_DutchAuctionState_init_zero, {  \
            {NULL}, NULL                                                       \
        }                                                                      \
    }
#define penumbra_core_component_auction_v1_AuctionId_init_zero \
    {                                                          \
        {                                                      \
            {NULL}, NULL                                       \
        }                                                      \
    }
#define penumbra_core_component_auction_v1_AuctionNft_init_zero \
    {false, penumbra_core_component_auction_v1_AuctionId_init_zero, 0}
#define penumbra_core_component_auction_v1_DutchAuctionDescription_init_zero                                   \
    {                                                                                                          \
        false, penumbra_core_asset_v1_Value_init_zero, false, penumbra_core_asset_v1_AssetId_init_zero, false, \
            penumbra_core_num_v1_Amount_init_zero, false, penumbra_core_num_v1_Amount_init_zero, 0, 0, 0, {    \
            {NULL}, NULL                                                                                       \
        }                                                                                                      \
    }
#define penumbra_core_component_auction_v1_DutchAuctionState_init_zero \
    {0,                                                                \
     false,                                                            \
     penumbra_core_component_dex_v1_PositionId_init_zero,              \
     0,                                                                \
     false,                                                            \
     penumbra_core_num_v1_Amount_init_zero,                            \
     false,                                                            \
     penumbra_core_num_v1_Amount_init_zero}
#define penumbra_core_component_auction_v1_DutchAuction_init_zero                        \
    {false, penumbra_core_component_auction_v1_DutchAuctionDescription_init_zero, false, \
     penumbra_core_component_auction_v1_DutchAuctionState_init_zero}
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_init_zero \
    {false, penumbra_core_component_auction_v1_DutchAuctionDescription_init_zero}
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_init_zero \
    {false, penumbra_core_component_auction_v1_AuctionId_init_zero}
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_init_zero \
    {false, penumbra_core_component_auction_v1_AuctionId_init_zero, 0, false,   \
     penumbra_core_asset_v1_BalanceCommitment_init_zero}
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_init_zero \
    {false,                                                                         \
     penumbra_core_component_auction_v1_AuctionId_init_zero,                        \
     0,                                                                             \
     false,                                                                         \
     penumbra_core_asset_v1_Value_init_zero,                                        \
     false,                                                                         \
     penumbra_core_asset_v1_Value_init_zero}
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_init_zero  \
    {false, penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_init_zero, \
     false, penumbra_core_component_auction_v1_AuctionId_init_zero,                  \
     false, penumbra_core_asset_v1_Metadata_init_zero,                               \
     false, penumbra_core_asset_v1_Metadata_init_zero}
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_init_zero                      \
    {                                                                                                    \
        false, penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_init_zero, { {NULL}, NULL } \
    }
#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_init_zero \
    {false, penumbra_core_component_auction_v1_AuctionId_init_zero, false,      \
     penumbra_core_component_auction_v1_DutchAuctionDescription_init_zero}
#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_init_zero \
    {false, penumbra_core_component_auction_v1_AuctionId_init_zero, false,    \
     penumbra_core_component_auction_v1_DutchAuctionState_init_zero}
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_init_zero \
    {false, penumbra_core_component_auction_v1_AuctionId_init_zero, false,  \
     penumbra_core_component_auction_v1_DutchAuctionState_init_zero,        \
     _penumbra_core_component_auction_v1_EventDutchAuctionEnded_Reason_MIN}
#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_init_zero \
    {false, penumbra_core_component_auction_v1_AuctionId_init_zero, false,      \
     penumbra_core_component_auction_v1_DutchAuctionState_init_zero}
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_init_zero                 \
    {false, penumbra_core_asset_v1_AssetId_init_zero, false, penumbra_core_num_v1_Amount_init_zero, \
     false, penumbra_core_num_v1_Amount_init_zero}
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_init_zero                  \
    {false, penumbra_core_asset_v1_AssetId_init_zero, false, penumbra_core_num_v1_Amount_init_zero, \
     false, penumbra_core_num_v1_Amount_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define penumbra_core_component_auction_v1_GenesisContent_params_tag 1
#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_auction_tag 2
#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_positions_tag 3
#define penumbra_core_component_auction_v1_AuctionStateByIdsRequest_id_tag 1
#define penumbra_core_component_auction_v1_AuctionId_inner_tag 1
#define penumbra_core_component_auction_v1_AuctionStateByIdRequest_id_tag 1
#define penumbra_core_component_auction_v1_AuctionNft_id_tag 1
#define penumbra_core_component_auction_v1_AuctionNft_seq_tag 2
#define penumbra_core_component_auction_v1_DutchAuctionDescription_input_tag 1
#define penumbra_core_component_auction_v1_DutchAuctionDescription_output_id_tag 2
#define penumbra_core_component_auction_v1_DutchAuctionDescription_max_output_tag 3
#define penumbra_core_component_auction_v1_DutchAuctionDescription_min_output_tag 4
#define penumbra_core_component_auction_v1_DutchAuctionDescription_start_height_tag 5
#define penumbra_core_component_auction_v1_DutchAuctionDescription_end_height_tag 6
#define penumbra_core_component_auction_v1_DutchAuctionDescription_step_count_tag 7
#define penumbra_core_component_auction_v1_DutchAuctionDescription_nonce_tag 8
#define penumbra_core_component_auction_v1_DutchAuctionState_seq_tag 1
#define penumbra_core_component_auction_v1_DutchAuctionState_current_position_tag 2
#define penumbra_core_component_auction_v1_DutchAuctionState_next_trigger_tag 3
#define penumbra_core_component_auction_v1_DutchAuctionState_input_reserves_tag 4
#define penumbra_core_component_auction_v1_DutchAuctionState_output_reserves_tag 5
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_id_tag 1
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_auction_tag 2
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_positions_tag 3
#define penumbra_core_component_auction_v1_DutchAuction_description_tag 1
#define penumbra_core_component_auction_v1_DutchAuction_state_tag 2
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_description_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_auction_id_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_auction_id_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_seq_tag 2
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_reserves_commitment_tag 3
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_auction_id_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_seq_tag 2
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_reserves_input_tag 3
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_reserves_output_tag 4
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_action_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_auction_id_tag 2
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_input_metadata_tag 3
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_output_metadata_tag 4
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_action_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_reserves_tag 2
#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_auction_id_tag 1
#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_description_tag 2
#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_auction_id_tag 1
#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_state_tag 2
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_auction_id_tag 1
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_state_tag 2
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_reason_tag 3
#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_auction_id_tag 1
#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_state_tag 2
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_asset_id_tag 1
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_previous_balance_tag 2
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_new_balance_tag 3
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_asset_id_tag 1
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_previous_balance_tag 2
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_new_balance_tag 3

/* Struct field encoding specification for nanopb */
#define penumbra_core_component_auction_v1_AuctionParameters_FIELDLIST(X, a)

#define penumbra_core_component_auction_v1_AuctionParameters_CALLBACK NULL
#define penumbra_core_component_auction_v1_AuctionParameters_DEFAULT NULL

#define penumbra_core_component_auction_v1_GenesisContent_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, params, 1)
#define penumbra_core_component_auction_v1_GenesisContent_CALLBACK NULL
#define penumbra_core_component_auction_v1_GenesisContent_DEFAULT NULL
#define penumbra_core_component_auction_v1_GenesisContent_params_MSGTYPE penumbra_core_component_auction_v1_AuctionParameters

#define penumbra_core_component_auction_v1_AuctionStateByIdRequest_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, id, 1)
#define penumbra_core_component_auction_v1_AuctionStateByIdRequest_CALLBACK NULL
#define penumbra_core_component_auction_v1_AuctionStateByIdRequest_DEFAULT NULL
#define penumbra_core_component_auction_v1_AuctionStateByIdRequest_id_MSGTYPE penumbra_core_component_auction_v1_AuctionId

#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction, 2)                                     \
    X(a, CALLBACK, REPEATED, MESSAGE, positions, 3)
#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_CALLBACK pb_default_field_callback
#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_DEFAULT NULL
#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_auction_MSGTYPE google_protobuf_Any
#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_positions_MSGTYPE penumbra_core_component_dex_v1_Position

#define penumbra_core_component_auction_v1_AuctionStateByIdsRequest_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, id, 1)
#define penumbra_core_component_auction_v1_AuctionStateByIdsRequest_CALLBACK pb_default_field_callback
#define penumbra_core_component_auction_v1_AuctionStateByIdsRequest_DEFAULT NULL
#define penumbra_core_component_auction_v1_AuctionStateByIdsRequest_id_MSGTYPE penumbra_core_component_auction_v1_AuctionId

#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, id, 1)                                           \
    X(a, STATIC, OPTIONAL, MESSAGE, auction, 2)                                      \
    X(a, CALLBACK, REPEATED, MESSAGE, positions, 3)
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_CALLBACK pb_default_field_callback
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_DEFAULT NULL
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_id_MSGTYPE penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_auction_MSGTYPE \
    penumbra_core_component_auction_v1_DutchAuctionState
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_positions_MSGTYPE \
    penumbra_core_component_dex_v1_Position

#define penumbra_core_component_auction_v1_AuctionId_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, BYTES, inner, 1)
#define penumbra_core_component_auction_v1_AuctionId_CALLBACK pb_default_field_callback
#define penumbra_core_component_auction_v1_AuctionId_DEFAULT NULL

#define penumbra_core_component_auction_v1_AuctionNft_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, id, 1)                            \
    X(a, STATIC, SINGULAR, UINT64, seq, 2)
#define penumbra_core_component_auction_v1_AuctionNft_CALLBACK NULL
#define penumbra_core_component_auction_v1_AuctionNft_DEFAULT NULL
#define penumbra_core_component_auction_v1_AuctionNft_id_MSGTYPE penumbra_core_component_auction_v1_AuctionId

#define penumbra_core_component_auction_v1_DutchAuctionDescription_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, input, 1)                                      \
    X(a, STATIC, OPTIONAL, MESSAGE, output_id, 2)                                  \
    X(a, STATIC, OPTIONAL, MESSAGE, max_output, 3)                                 \
    X(a, STATIC, OPTIONAL, MESSAGE, min_output, 4)                                 \
    X(a, STATIC, SINGULAR, UINT64, start_height, 5)                                \
    X(a, STATIC, SINGULAR, UINT64, end_height, 6)                                  \
    X(a, STATIC, SINGULAR, UINT64, step_count, 7)                                  \
    X(a, CALLBACK, SINGULAR, BYTES, nonce, 8)
#define penumbra_core_component_auction_v1_DutchAuctionDescription_CALLBACK pb_default_field_callback
#define penumbra_core_component_auction_v1_DutchAuctionDescription_DEFAULT NULL
#define penumbra_core_component_auction_v1_DutchAuctionDescription_input_MSGTYPE penumbra_core_asset_v1_Value
#define penumbra_core_component_auction_v1_DutchAuctionDescription_output_id_MSGTYPE penumbra_core_asset_v1_AssetId
#define penumbra_core_component_auction_v1_DutchAuctionDescription_max_output_MSGTYPE penumbra_core_num_v1_Amount
#define penumbra_core_component_auction_v1_DutchAuctionDescription_min_output_MSGTYPE penumbra_core_num_v1_Amount

#define penumbra_core_component_auction_v1_DutchAuctionState_FIELDLIST(X, a) \
    X(a, STATIC, SINGULAR, UINT64, seq, 1)                                   \
    X(a, STATIC, OPTIONAL, MESSAGE, current_position, 2)                     \
    X(a, STATIC, SINGULAR, UINT64, next_trigger, 3)                          \
    X(a, STATIC, OPTIONAL, MESSAGE, input_reserves, 4)                       \
    X(a, STATIC, OPTIONAL, MESSAGE, output_reserves, 5)
#define penumbra_core_component_auction_v1_DutchAuctionState_CALLBACK NULL
#define penumbra_core_component_auction_v1_DutchAuctionState_DEFAULT NULL
#define penumbra_core_component_auction_v1_DutchAuctionState_current_position_MSGTYPE \
    penumbra_core_component_dex_v1_PositionId
#define penumbra_core_component_auction_v1_DutchAuctionState_input_reserves_MSGTYPE penumbra_core_num_v1_Amount
#define penumbra_core_component_auction_v1_DutchAuctionState_output_reserves_MSGTYPE penumbra_core_num_v1_Amount

#define penumbra_core_component_auction_v1_DutchAuction_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, description, 1)                     \
    X(a, STATIC, OPTIONAL, MESSAGE, state, 2)
#define penumbra_core_component_auction_v1_DutchAuction_CALLBACK NULL
#define penumbra_core_component_auction_v1_DutchAuction_DEFAULT NULL
#define penumbra_core_component_auction_v1_DutchAuction_description_MSGTYPE \
    penumbra_core_component_auction_v1_DutchAuctionDescription
#define penumbra_core_component_auction_v1_DutchAuction_state_MSGTYPE penumbra_core_component_auction_v1_DutchAuctionState

#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, description, 1)
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_description_MSGTYPE \
    penumbra_core_component_auction_v1_DutchAuctionDescription

#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId

#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)                                    \
    X(a, STATIC, SINGULAR, UINT64, seq, 2)                                            \
    X(a, STATIC, OPTIONAL, MESSAGE, reserves_commitment, 3)
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_reserves_commitment_MSGTYPE \
    penumbra_core_asset_v1_BalanceCommitment

#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)                                        \
    X(a, STATIC, SINGULAR, UINT64, seq, 2)                                                \
    X(a, STATIC, OPTIONAL, MESSAGE, reserves_input, 3)                                    \
    X(a, STATIC, OPTIONAL, MESSAGE, reserves_output, 4)
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_reserves_input_MSGTYPE penumbra_core_asset_v1_Value
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_reserves_output_MSGTYPE \
    penumbra_core_asset_v1_Value

#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, action, 1)                                            \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 2)                                        \
    X(a, STATIC, OPTIONAL, MESSAGE, input_metadata, 3)                                    \
    X(a, STATIC, OPTIONAL, MESSAGE, output_metadata, 4)
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_action_MSGTYPE \
    penumbra_core_component_auction_v1_ActionDutchAuctionSchedule
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_input_metadata_MSGTYPE \
    penumbra_core_asset_v1_Metadata
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_output_metadata_MSGTYPE \
    penumbra_core_asset_v1_Metadata

#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, action, 1)                                            \
    X(a, CALLBACK, REPEATED, MESSAGE, reserves, 2)
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_CALLBACK pb_default_field_callback
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_action_MSGTYPE \
    penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_reserves_MSGTYPE penumbra_core_asset_v1_ValueView

#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)                                    \
    X(a, STATIC, OPTIONAL, MESSAGE, description, 2)
#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_CALLBACK NULL
#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_DEFAULT NULL
#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_description_MSGTYPE \
    penumbra_core_component_auction_v1_DutchAuctionDescription

#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)                                  \
    X(a, STATIC, OPTIONAL, MESSAGE, state, 2)
#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_CALLBACK NULL
#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_DEFAULT NULL
#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_state_MSGTYPE \
    penumbra_core_component_auction_v1_DutchAuctionState

#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)                                \
    X(a, STATIC, OPTIONAL, MESSAGE, state, 2)                                     \
    X(a, STATIC, SINGULAR, UENUM, reason, 3)
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_CALLBACK NULL
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_DEFAULT NULL
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_state_MSGTYPE \
    penumbra_core_component_auction_v1_DutchAuctionState

#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)                                    \
    X(a, STATIC, OPTIONAL, MESSAGE, state, 2)
#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_CALLBACK NULL
#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_DEFAULT NULL
#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_state_MSGTYPE \
    penumbra_core_component_auction_v1_DutchAuctionState

#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, asset_id, 1)                                          \
    X(a, STATIC, OPTIONAL, MESSAGE, previous_balance, 2)                                  \
    X(a, STATIC, OPTIONAL, MESSAGE, new_balance, 3)
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_CALLBACK NULL
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_DEFAULT NULL
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_asset_id_MSGTYPE penumbra_core_asset_v1_AssetId
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_previous_balance_MSGTYPE \
    penumbra_core_num_v1_Amount
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_new_balance_MSGTYPE penumbra_core_num_v1_Amount

#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, asset_id, 1)                                         \
    X(a, STATIC, OPTIONAL, MESSAGE, previous_balance, 2)                                 \
    X(a, STATIC, OPTIONAL, MESSAGE, new_balance, 3)
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_CALLBACK NULL
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_DEFAULT NULL
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_asset_id_MSGTYPE penumbra_core_asset_v1_AssetId
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_previous_balance_MSGTYPE penumbra_core_num_v1_Amount
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_new_balance_MSGTYPE penumbra_core_num_v1_Amount

extern const pb_msgdesc_t penumbra_core_component_auction_v1_AuctionParameters_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_GenesisContent_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_AuctionStateByIdRequest_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_AuctionStateByIdResponse_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_AuctionStateByIdsRequest_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_AuctionStateByIdsResponse_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_AuctionId_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_AuctionNft_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_DutchAuctionDescription_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_DutchAuctionState_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_DutchAuction_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionEnd_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_EventDutchAuctionScheduled_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_EventDutchAuctionUpdated_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_EventDutchAuctionEnded_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define penumbra_core_component_auction_v1_AuctionParameters_fields &penumbra_core_component_auction_v1_AuctionParameters_msg
#define penumbra_core_component_auction_v1_GenesisContent_fields &penumbra_core_component_auction_v1_GenesisContent_msg
#define penumbra_core_component_auction_v1_AuctionStateByIdRequest_fields \
    &penumbra_core_component_auction_v1_AuctionStateByIdRequest_msg
#define penumbra_core_component_auction_v1_AuctionStateByIdResponse_fields \
    &penumbra_core_component_auction_v1_AuctionStateByIdResponse_msg
#define penumbra_core_component_auction_v1_AuctionStateByIdsRequest_fields \
    &penumbra_core_component_auction_v1_AuctionStateByIdsRequest_msg
#define penumbra_core_component_auction_v1_AuctionStateByIdsResponse_fields \
    &penumbra_core_component_auction_v1_AuctionStateByIdsResponse_msg
#define penumbra_core_component_auction_v1_AuctionId_fields &penumbra_core_component_auction_v1_AuctionId_msg
#define penumbra_core_component_auction_v1_AuctionNft_fields &penumbra_core_component_auction_v1_AuctionNft_msg
#define penumbra_core_component_auction_v1_DutchAuctionDescription_fields \
    &penumbra_core_component_auction_v1_DutchAuctionDescription_msg
#define penumbra_core_component_auction_v1_DutchAuctionState_fields &penumbra_core_component_auction_v1_DutchAuctionState_msg
#define penumbra_core_component_auction_v1_DutchAuction_fields &penumbra_core_component_auction_v1_DutchAuction_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionEnd_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_msg
#define penumbra_core_component_auction_v1_EventDutchAuctionScheduled_fields \
    &penumbra_core_component_auction_v1_EventDutchAuctionScheduled_msg
#define penumbra_core_component_auction_v1_EventDutchAuctionUpdated_fields \
    &penumbra_core_component_auction_v1_EventDutchAuctionUpdated_msg
#define penumbra_core_component_auction_v1_EventDutchAuctionEnded_fields \
    &penumbra_core_component_auction_v1_EventDutchAuctionEnded_msg
#define penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_fields \
    &penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_msg
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_fields \
    &penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_msg
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_fields \
    &penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_msg

/* Maximum encoded size of messages (where known) */
/* penumbra_core_component_auction_v1_AuctionStateByIdRequest_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_AuctionStateByIdResponse_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_AuctionStateByIdsRequest_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_AuctionStateByIdsResponse_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_AuctionId_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_AuctionNft_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_DutchAuctionDescription_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_DutchAuction_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionEnd_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_EventDutchAuctionScheduled_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_EventDutchAuctionUpdated_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_EventDutchAuctionEnded_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn_size depends on runtime parameters */
#define penumbra_core_component_auction_v1_AuctionParameters_size 0
#define penumbra_core_component_auction_v1_GenesisContent_size 2
#if defined(penumbra_core_component_dex_v1_PositionId_size)
#define PENUMBRA_CORE_COMPONENT_AUCTION_V1_PENUMBRA_CORE_COMPONENT_AUCTION_V1_AUCTION_PB_H_MAX_SIZE \
    penumbra_core_component_auction_v1_DutchAuctionState_size
#define penumbra_core_component_auction_v1_DutchAuctionState_size (76 + penumbra_core_component_dex_v1_PositionId_size)
#endif
#if defined(penumbra_core_asset_v1_AssetId_size)
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit_size (54 + penumbra_core_asset_v1_AssetId_size)
#define penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit_size (54 + penumbra_core_asset_v1_AssetId_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
