/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "penumbra/core/component/auction/v1/auction.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(penumbra_core_component_auction_v1_AuctionParameters, penumbra_core_component_auction_v1_AuctionParameters, AUTO)

PB_BIND(penumbra_core_component_auction_v1_GenesisContent, penumbra_core_component_auction_v1_GenesisContent, AUTO)

PB_BIND(penumbra_core_component_auction_v1_AuctionStateByIdRequest,
        penumbra_core_component_auction_v1_AuctionStateByIdRequest, AUTO)

PB_BIND(penumbra_core_component_auction_v1_AuctionStateByIdResponse,
        penumbra_core_component_auction_v1_AuctionStateByIdResponse, AUTO)

PB_BIND(penumbra_core_component_auction_v1_AuctionStateByIdsRequest,
        penumbra_core_component_auction_v1_AuctionStateByIdsRequest, AUTO)

PB_BIND(penumbra_core_component_auction_v1_AuctionStateByIdsResponse,
        penumbra_core_component_auction_v1_AuctionStateByIdsResponse, AUTO)

PB_BIND(penumbra_core_component_auction_v1_AuctionId, penumbra_core_component_auction_v1_AuctionId, AUTO)

PB_BIND(penumbra_core_component_auction_v1_AuctionNft, penumbra_core_component_auction_v1_AuctionNft, AUTO)

PB_BIND(penumbra_core_component_auction_v1_DutchAuctionDescription,
        penumbra_core_component_auction_v1_DutchAuctionDescription, AUTO)

PB_BIND(penumbra_core_component_auction_v1_DutchAuctionState, penumbra_core_component_auction_v1_DutchAuctionState, AUTO)

PB_BIND(penumbra_core_component_auction_v1_DutchAuction, penumbra_core_component_auction_v1_DutchAuction, 2)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionSchedule,
        penumbra_core_component_auction_v1_ActionDutchAuctionSchedule, AUTO)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionEnd, penumbra_core_component_auction_v1_ActionDutchAuctionEnd,
        AUTO)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw,
        penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw, AUTO)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan,
        penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan, AUTO)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView,
        penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView, 2)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView,
        penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView, AUTO)

PB_BIND(penumbra_core_component_auction_v1_EventDutchAuctionScheduled,
        penumbra_core_component_auction_v1_EventDutchAuctionScheduled, 2)

PB_BIND(penumbra_core_component_auction_v1_EventDutchAuctionUpdated,
        penumbra_core_component_auction_v1_EventDutchAuctionUpdated, AUTO)

PB_BIND(penumbra_core_component_auction_v1_EventDutchAuctionEnded, penumbra_core_component_auction_v1_EventDutchAuctionEnded,
        AUTO)

PB_BIND(penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn,
        penumbra_core_component_auction_v1_EventDutchAuctionWithdrawn, AUTO)

PB_BIND(penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit,
        penumbra_core_component_auction_v1_EventValueCircuitBreakerCredit, AUTO)

PB_BIND(penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit,
        penumbra_core_component_auction_v1_EventValueCircuitBreakerDebit, AUTO)
