/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "penumbra/core/component/auction/v1/auction.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(penumbra_core_component_auction_v1_AuctionParameters, penumbra_core_component_auction_v1_AuctionParameters, AUTO)

PB_BIND(penumbra_core_component_auction_v1_AuctionId, penumbra_core_component_auction_v1_AuctionId, AUTO)

PB_BIND(penumbra_core_component_auction_v1_DutchAuctionDescription,
        penumbra_core_component_auction_v1_DutchAuctionDescription, AUTO)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionSchedule,
        penumbra_core_component_auction_v1_ActionDutchAuctionSchedule, AUTO)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionEnd, penumbra_core_component_auction_v1_ActionDutchAuctionEnd,
        AUTO)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw,
        penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw, AUTO)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan,
        penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan, AUTO)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView,
        penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView, 2)

PB_BIND(penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView,
        penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView, AUTO)
