/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_PENUMBRA_CORE_COMPONENT_AUCTION_V1_PENUMBRA_CORE_COMPONENT_AUCTION_V1_AUCTION_PB_H_INCLUDED
#define PB_PENUMBRA_CORE_COMPONENT_AUCTION_V1_PENUMBRA_CORE_COMPONENT_AUCTION_V1_AUCTION_PB_H_INCLUDED
#include <pb.h>

#include "penumbra/core/asset/v1/asset.pb.h"
#include "penumbra/core/num/v1/num.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* The configuration parameters for the auction component. */
typedef struct _penumbra_core_component_auction_v1_AuctionParameters {
    char dummy_field;
} penumbra_core_component_auction_v1_AuctionParameters;

/* A unique identifier for an auction, obtained from hashing a domain separator
 along with the immutable part of an auction description. */
typedef struct _penumbra_core_component_auction_v1_AuctionId {
    pb_callback_t inner;
} penumbra_core_component_auction_v1_AuctionId;

/* Describes a Dutch auction using programmatic liquidity on the DEX. */
typedef struct _penumbra_core_component_auction_v1_DutchAuctionDescription {
    /* The value the seller wishes to auction. */
    bool has_input;
    penumbra_core_asset_v1_Value input;
    /* The asset ID of the target asset the seller wishes to acquire. */
    bool has_output_id;
    penumbra_core_asset_v1_AssetId output_id;
    /* The maximum output the seller can receive.

 This implicitly defines the starting price for the auction. */
    bool has_max_output;
    penumbra_core_num_v1_Amount max_output;
    /* The minimum output the seller is willing to receive.

 This implicitly defines the ending price for the auction. */
    bool has_min_output;
    penumbra_core_num_v1_Amount min_output;
    /* The block height at which the auction begins.

 This allows the seller to schedule an auction at a future time. */
    uint64_t start_height;
    /* The block height at which the auction ends.

 Together with `start_height`, `max_output`, and `min_output`,
 this implicitly defines the speed of the auction. */
    uint64_t end_height;
    /* The number of discrete price steps to use for the auction.

 `end_height - start_height` must be a multiple of `step_count`. */
    uint64_t step_count;
    /* A random nonce used to allow identical auctions to have
 distinct auction IDs. */
    pb_callback_t nonce;
} penumbra_core_component_auction_v1_DutchAuctionDescription;

/* Initiates a Dutch auction using protocol-controlled liquidity. */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionSchedule {
    bool has_description;
    penumbra_core_component_auction_v1_DutchAuctionDescription description;
} penumbra_core_component_auction_v1_ActionDutchAuctionSchedule;

/* Terminate the auction associated with the specified `auction_id` */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionEnd {
    /* The auction to end. */
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
} penumbra_core_component_auction_v1_ActionDutchAuctionEnd;

/* Withdraw funds from the ended auction associated with the specified `auction_id` */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw {
    /* The auction to withdraw funds from. */
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    /* The sequence number of the withdrawal. */
    uint64_t seq;
    /* A transparent (zero blinding factor) commitment to the
 auction's final reserves.

 The chain will check this commitment by recomputing it
 with the on-chain state. */
    bool has_reserves_commitment;
    penumbra_core_asset_v1_BalanceCommitment reserves_commitment;
} penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw;

/* A plan to a `ActionDutchAuctionWithdraw` which contains both private and public data. */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan {
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    uint64_t seq;
    bool has_reserves_input;
    penumbra_core_asset_v1_Value reserves_input;
    bool has_reserves_output;
    penumbra_core_asset_v1_Value reserves_output;
} penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan;

/* An `ActionDutchAuctionSchedule` augmented with additional metadata. */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView {
    bool has_action;
    penumbra_core_component_auction_v1_ActionDutchAuctionSchedule action;
    bool has_auction_id;
    penumbra_core_component_auction_v1_AuctionId auction_id;
    bool has_input_metadata;
    penumbra_core_asset_v1_Metadata input_metadata;
    bool has_output_metadata;
    penumbra_core_asset_v1_Metadata output_metadata;
} penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView;

/* An `ActionDutchAuctionWithdraw` augmented with additional metadata. */
typedef struct _penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView {
    bool has_action;
    penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw action;
    /* A sequence of values that sum together to the provided
 reserves commitment. */
    pb_callback_t reserves;
} penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define penumbra_core_component_auction_v1_AuctionParameters_init_default \
    { 0 }
#define penumbra_core_component_auction_v1_AuctionId_init_default \
    {                                                             \
        { {NULL}, NULL }                                          \
    }
#define penumbra_core_component_auction_v1_DutchAuctionDescription_init_default                                      \
    {                                                                                                                \
        false, penumbra_core_asset_v1_Value_init_default, false, penumbra_core_asset_v1_AssetId_init_default, false, \
            penumbra_core_num_v1_Amount_init_default, false, penumbra_core_num_v1_Amount_init_default, 0, 0, 0, {    \
            {NULL}, NULL                                                                                             \
        }                                                                                                            \
    }
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_init_default \
    { false, penumbra_core_component_auction_v1_DutchAuctionDescription_init_default }
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_init_default \
    { false, penumbra_core_component_auction_v1_AuctionId_init_default }
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_init_default  \
    {                                                                               \
        false, penumbra_core_component_auction_v1_AuctionId_init_default, 0, false, \
            penumbra_core_asset_v1_BalanceCommitment_init_default                   \
    }
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_init_default                  \
    {                                                                                                   \
        false, penumbra_core_component_auction_v1_AuctionId_init_default, 0, false,                     \
            penumbra_core_asset_v1_Value_init_default, false, penumbra_core_asset_v1_Value_init_default \
    }
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_init_default                                      \
    {                                                                                                                       \
        false, penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_init_default, false,                           \
            penumbra_core_component_auction_v1_AuctionId_init_default, false, penumbra_core_asset_v1_Metadata_init_default, \
            false, penumbra_core_asset_v1_Metadata_init_default                                                             \
    }
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_init_default                      \
    {                                                                                                       \
        false, penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_init_default, { {NULL}, NULL } \
    }
#define penumbra_core_component_auction_v1_AuctionParameters_init_zero \
    { 0 }
#define penumbra_core_component_auction_v1_AuctionId_init_zero \
    {                                                          \
        { {NULL}, NULL }                                       \
    }
#define penumbra_core_component_auction_v1_DutchAuctionDescription_init_zero                                   \
    {                                                                                                          \
        false, penumbra_core_asset_v1_Value_init_zero, false, penumbra_core_asset_v1_AssetId_init_zero, false, \
            penumbra_core_num_v1_Amount_init_zero, false, penumbra_core_num_v1_Amount_init_zero, 0, 0, 0, {    \
            {NULL}, NULL                                                                                       \
        }                                                                                                      \
    }
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_init_zero \
    { false, penumbra_core_component_auction_v1_DutchAuctionDescription_init_zero }
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_init_zero \
    { false, penumbra_core_component_auction_v1_AuctionId_init_zero }
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_init_zero  \
    {                                                                            \
        false, penumbra_core_component_auction_v1_AuctionId_init_zero, 0, false, \
            penumbra_core_asset_v1_BalanceCommitment_init_zero                   \
    }
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_init_zero                                      \
    {                                                                                                                    \
        false, penumbra_core_component_auction_v1_AuctionId_init_zero, 0, false, penumbra_core_asset_v1_Value_init_zero, \
            false, penumbra_core_asset_v1_Value_init_zero                                                                \
    }
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_init_zero                                   \
    {                                                                                                                 \
        false, penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_init_zero, false,                        \
            penumbra_core_component_auction_v1_AuctionId_init_zero, false, penumbra_core_asset_v1_Metadata_init_zero, \
            false, penumbra_core_asset_v1_Metadata_init_zero                                                          \
    }
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_init_zero                      \
    {                                                                                                    \
        false, penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_init_zero, { {NULL}, NULL } \
    }

/* Field tags (for use in manual encoding/decoding) */
#define penumbra_core_component_auction_v1_AuctionId_inner_tag 1
#define penumbra_core_component_auction_v1_DutchAuctionDescription_input_tag 1
#define penumbra_core_component_auction_v1_DutchAuctionDescription_output_id_tag 2
#define penumbra_core_component_auction_v1_DutchAuctionDescription_max_output_tag 3
#define penumbra_core_component_auction_v1_DutchAuctionDescription_min_output_tag 4
#define penumbra_core_component_auction_v1_DutchAuctionDescription_start_height_tag 5
#define penumbra_core_component_auction_v1_DutchAuctionDescription_end_height_tag 6
#define penumbra_core_component_auction_v1_DutchAuctionDescription_step_count_tag 7
#define penumbra_core_component_auction_v1_DutchAuctionDescription_nonce_tag 8
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_description_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_auction_id_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_auction_id_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_seq_tag 2
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_reserves_commitment_tag 3
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_auction_id_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_seq_tag 2
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_reserves_input_tag 3
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_reserves_output_tag 4
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_action_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_auction_id_tag 2
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_input_metadata_tag 3
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_output_metadata_tag 4
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_action_tag 1
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_reserves_tag 2

/* Struct field encoding specification for nanopb */
#define penumbra_core_component_auction_v1_AuctionParameters_FIELDLIST(X, a)

#define penumbra_core_component_auction_v1_AuctionParameters_CALLBACK NULL
#define penumbra_core_component_auction_v1_AuctionParameters_DEFAULT NULL

#define penumbra_core_component_auction_v1_AuctionId_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, BYTES, inner, 1)
#define penumbra_core_component_auction_v1_AuctionId_CALLBACK pb_default_field_callback
#define penumbra_core_component_auction_v1_AuctionId_DEFAULT NULL

#define penumbra_core_component_auction_v1_DutchAuctionDescription_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, input, 1)                                      \
    X(a, STATIC, OPTIONAL, MESSAGE, output_id, 2)                                  \
    X(a, STATIC, OPTIONAL, MESSAGE, max_output, 3)                                 \
    X(a, STATIC, OPTIONAL, MESSAGE, min_output, 4)                                 \
    X(a, STATIC, SINGULAR, UINT64, start_height, 5)                                \
    X(a, STATIC, SINGULAR, UINT64, end_height, 6)                                  \
    X(a, STATIC, SINGULAR, UINT64, step_count, 7)                                  \
    X(a, CALLBACK, SINGULAR, BYTES, nonce, 8)
#define penumbra_core_component_auction_v1_DutchAuctionDescription_CALLBACK pb_default_field_callback
#define penumbra_core_component_auction_v1_DutchAuctionDescription_DEFAULT NULL
#define penumbra_core_component_auction_v1_DutchAuctionDescription_input_MSGTYPE penumbra_core_asset_v1_Value
#define penumbra_core_component_auction_v1_DutchAuctionDescription_output_id_MSGTYPE penumbra_core_asset_v1_AssetId
#define penumbra_core_component_auction_v1_DutchAuctionDescription_max_output_MSGTYPE penumbra_core_num_v1_Amount
#define penumbra_core_component_auction_v1_DutchAuctionDescription_min_output_MSGTYPE penumbra_core_num_v1_Amount

#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, description, 1)
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_description_MSGTYPE \
    penumbra_core_component_auction_v1_DutchAuctionDescription

#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId

#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)                                    \
    X(a, STATIC, SINGULAR, UINT64, seq, 2)                                            \
    X(a, STATIC, OPTIONAL, MESSAGE, reserves_commitment, 3)
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_reserves_commitment_MSGTYPE \
    penumbra_core_asset_v1_BalanceCommitment

#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 1)                                        \
    X(a, STATIC, SINGULAR, UINT64, seq, 2)                                                \
    X(a, STATIC, OPTIONAL, MESSAGE, reserves_input, 3)                                    \
    X(a, STATIC, OPTIONAL, MESSAGE, reserves_output, 4)
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_reserves_input_MSGTYPE penumbra_core_asset_v1_Value
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_reserves_output_MSGTYPE \
    penumbra_core_asset_v1_Value

#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, action, 1)                                            \
    X(a, STATIC, OPTIONAL, MESSAGE, auction_id, 2)                                        \
    X(a, STATIC, OPTIONAL, MESSAGE, input_metadata, 3)                                    \
    X(a, STATIC, OPTIONAL, MESSAGE, output_metadata, 4)
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_CALLBACK NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_action_MSGTYPE \
    penumbra_core_component_auction_v1_ActionDutchAuctionSchedule
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_auction_id_MSGTYPE \
    penumbra_core_component_auction_v1_AuctionId
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_input_metadata_MSGTYPE \
    penumbra_core_asset_v1_Metadata
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_output_metadata_MSGTYPE \
    penumbra_core_asset_v1_Metadata

#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_FIELDLIST(X, a) \
    X(a, STATIC, OPTIONAL, MESSAGE, action, 1)                                            \
    X(a, CALLBACK, REPEATED, MESSAGE, reserves, 2)
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_CALLBACK pb_default_field_callback
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_DEFAULT NULL
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_action_MSGTYPE \
    penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_reserves_MSGTYPE penumbra_core_asset_v1_ValueView

extern const pb_msgdesc_t penumbra_core_component_auction_v1_AuctionParameters_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_AuctionId_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_DutchAuctionDescription_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionEnd_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_msg;
extern const pb_msgdesc_t penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define penumbra_core_component_auction_v1_AuctionParameters_fields &penumbra_core_component_auction_v1_AuctionParameters_msg
#define penumbra_core_component_auction_v1_AuctionId_fields &penumbra_core_component_auction_v1_AuctionId_msg
#define penumbra_core_component_auction_v1_DutchAuctionDescription_fields \
    &penumbra_core_component_auction_v1_DutchAuctionDescription_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionEnd_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionEnd_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_msg
#define penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_fields \
    &penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_msg

/* Maximum encoded size of messages (where known) */
/* penumbra_core_component_auction_v1_AuctionId_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_DutchAuctionDescription_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionSchedule_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionEnd_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionWithdraw_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawPlan_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionScheduleView_size depends on runtime parameters */
/* penumbra_core_component_auction_v1_ActionDutchAuctionWithdrawView_size depends on runtime parameters */
#define PENUMBRA_CORE_COMPONENT_AUCTION_V1_PENUMBRA_CORE_COMPONENT_AUCTION_V1_AUCTION_PB_H_MAX_SIZE \
    penumbra_core_component_auction_v1_AuctionParameters_size
#define penumbra_core_component_auction_v1_AuctionParameters_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
