/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/distribution/v1beta1/query.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_distribution_v1beta1_QueryParamsRequest, cosmos_distribution_v1beta1_QueryParamsRequest, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryParamsResponse, cosmos_distribution_v1beta1_QueryParamsResponse, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryValidatorDistributionInfoRequest,
        cosmos_distribution_v1beta1_QueryValidatorDistributionInfoRequest, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryValidatorDistributionInfoResponse,
        cosmos_distribution_v1beta1_QueryValidatorDistributionInfoResponse, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryValidatorOutstandingRewardsRequest,
        cosmos_distribution_v1beta1_QueryValidatorOutstandingRewardsRequest, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryValidatorOutstandingRewardsResponse,
        cosmos_distribution_v1beta1_QueryValidatorOutstandingRewardsResponse, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryValidatorCommissionRequest,
        cosmos_distribution_v1beta1_QueryValidatorCommissionRequest, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryValidatorCommissionResponse,
        cosmos_distribution_v1beta1_QueryValidatorCommissionResponse, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryValidatorSlashesRequest, cosmos_distribution_v1beta1_QueryValidatorSlashesRequest,
        AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryValidatorSlashesResponse, cosmos_distribution_v1beta1_QueryValidatorSlashesResponse,
        AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryDelegationRewardsRequest, cosmos_distribution_v1beta1_QueryDelegationRewardsRequest,
        AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryDelegationRewardsResponse,
        cosmos_distribution_v1beta1_QueryDelegationRewardsResponse, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryDelegationTotalRewardsRequest,
        cosmos_distribution_v1beta1_QueryDelegationTotalRewardsRequest, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryDelegationTotalRewardsResponse,
        cosmos_distribution_v1beta1_QueryDelegationTotalRewardsResponse, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryDelegatorValidatorsRequest,
        cosmos_distribution_v1beta1_QueryDelegatorValidatorsRequest, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryDelegatorValidatorsResponse,
        cosmos_distribution_v1beta1_QueryDelegatorValidatorsResponse, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryDelegatorWithdrawAddressRequest,
        cosmos_distribution_v1beta1_QueryDelegatorWithdrawAddressRequest, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryDelegatorWithdrawAddressResponse,
        cosmos_distribution_v1beta1_QueryDelegatorWithdrawAddressResponse, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryCommunityPoolRequest, cosmos_distribution_v1beta1_QueryCommunityPoolRequest, AUTO)

PB_BIND(cosmos_distribution_v1beta1_QueryCommunityPoolResponse, cosmos_distribution_v1beta1_QueryCommunityPoolResponse, AUTO)
