/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/mint/v1beta1/tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_mint_v1beta1_MsgUpdateParams, cosmos_mint_v1beta1_MsgUpdateParams, AUTO)

PB_BIND(cosmos_mint_v1beta1_MsgUpdateParamsResponse, cosmos_mint_v1beta1_MsgUpdateParamsResponse, AUTO)
