name: Proto Update

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at 00:00 (UTC)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  
jobs:
  proto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          pip install grpcio-tools


      - name: Install buf
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64" -o buf && chmod +x buf && sudo mv buf /usr/local/bin/

      - name: Check buf version
        run: buf --version

      - name: Run make proto
        run: make proto

      - name: Check for changes in proto
        id: changes
        run: |
          git add proto/
          if git diff --cached --quiet -- proto/; then
            echo "No changes detected in proto/"
            echo "changes=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Changes detected in proto/:"
            git diff --cached --stat -- proto/
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Check for existing PR
        id: check-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --state open --search "Update generated proto files" --json number --jq 'length')
          echo "PR_EXISTS=$PR_EXISTS"
          if [ "$PR_EXISTS" -gt 0 ]; then
            echo "An open PR already exists."
            echo "pr_exists=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "No open PR found."
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR if changes exist and no PR is open
        if: steps.changes.outputs.changes == 'true' && steps.check-pr.outputs.pr_exists == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update generated proto files"
          title: "Update generated proto files"
          body: "This PR updates the generated proto files."
          branch: proto-update-${{ github.run_id }}
          base: dev
          delete-branch: true
          draft: true