/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cosmos/vesting/v1beta1/tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_vesting_v1beta1_MsgCreateVestingAccount, cosmos_vesting_v1beta1_MsgCreateVestingAccount, AUTO)

PB_BIND(cosmos_vesting_v1beta1_MsgCreateVestingAccountResponse, cosmos_vesting_v1beta1_MsgCreateVestingAccountResponse, AUTO)

PB_BIND(cosmos_vesting_v1beta1_MsgCreatePermanentLockedAccount, cosmos_vesting_v1beta1_MsgCreatePermanentLockedAccount, AUTO)

PB_BIND(cosmos_vesting_v1beta1_MsgCreatePermanentLockedAccountResponse,
        cosmos_vesting_v1beta1_MsgCreatePermanentLockedAccountResponse, AUTO)

PB_BIND(cosmos_vesting_v1beta1_MsgCreatePeriodicVestingAccount, cosmos_vesting_v1beta1_MsgCreatePeriodicVestingAccount, AUTO)

PB_BIND(cosmos_vesting_v1beta1_MsgCreatePeriodicVestingAccountResponse,
        cosmos_vesting_v1beta1_MsgCreatePeriodicVestingAccountResponse, AUTO)
